### ISSUE TITLE
URI Variables in CoAP are not supported

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#1015]
[Smart coffee machine Thing](http://plugfest.thingweb.io:8083/smart-coffee-machine) produces CoAP forms even if there are uri variables for that affordance. But there is no support for that in CoAP so those forms are not usable at all. Either the support for URI variables should be implemented or forms should not be generated for coap in that case.

**Comment by relu91** [comment]
Are we talking about the server side or the client side? Giving a look at the code it seems that now URIVariables are handled by the server.  @JKRhb can you verify if this is still an issue?

**Comment by JKRhb** [comment]
Hmm, I guess the problem here is that for HTTP, forms like

```js
{
    "href": "http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/availableResourceLevel{?id}",
    "contentType": "application/json",
    "op": ["readproperty", "writeproperty"]
},
```

are generated, while for CoAP, only forms like

```js
{
    "href": "coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/availableResourceLevel",
    "contentType": "application/json",
    "op": ["writeproperty", "readproperty"]
},
```

without the actual URI variables are generated, right?

**Comment by JKRhb** [comment]
I guess we need to implement this function in the HTTP server also for the CoAP server or move it to the core package to use it across protocol binding implementations:

https://github.com/eclipse-thingweb/node-wot/blob/c8177c2526e4759a06b0ffe3bec2a04b48ffdd39/packages/binding-http/src/http-server.ts#L264-L296

**Comment by egekorkan** [comment]
So it seems that it is just about the TD generation. Regarding core or not:

One issue I see with moving to core would mean that uri variables would be generated for all protocols, whether they support it or not. I am not convinced on myself but I think it would be better to manage forms as much as possible in the binding level 🤔

**Comment by JKRhb** [comment]
> One issue I see with moving to core would mean that uri variables would be generated for all protocols, whether they support it or not. I am not convinced on myself but I think it would be better to manage forms as much as possible in the binding level 🤔

Oh, yeah, I was rather thinking about moving the function itself to the core package and then let the binding implementations use it in their implementations :) I now tried to implement the feature in #1078 – could you have a look if that resolves the issue?

**Comment by egekorkan** [comment]
> moving the function itself to the core package and then let the binding implementations use it in their implementations :) 

Ok that makes sense, thank you!
