### ISSUE TITLE
coap URI  created by wot-servient uses pr and ac

### ISSUE THREAD

**Issue by yagizyalcintas** [eclipse/thingweb.node-wot#102]
Default wot-servient uses 
`http://<ip>/servient/properties/<property_name> ` and 
`http://<ip>/servient/actions/<action_name> `  for http
but for coap it uses:
`coap://<ip>/servient/pr/<property_name>` and 
`coap://<ip>/servient/ac/<action_name>`

The way servient creates the uri s should not differ for different protocols.

**Comment by danielpeintner** [comment]
The current behavior is technically not wrong but I agree that it would be better to _harmonize_ CoAP URIs and HTTP URIs.

@mkovatsc, others:  were there any good reasons for the current behavior?

If there is no strong counter argument I would do that change...
