### ISSUE TITLE
wot-servient.conf is "misleading" for mqtt

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#104]
There is no documentation when used `wot-servient -h` on how to use it for mqtt. If someone builds node-wot and does the initial tests with `counter.js` it will not work out of the box since the configuration uses username, password and client id. None of these are necessary to set up a connection.
I would suggest to remove username, password and client id from the default configuration but document them on `wot-servient -h` such that it works out of the box

**Comment by danielpeintner** [comment]
@egekorkan can we close this issue?
(fixed in your commit https://github.com/eclipse/thingweb.node-wot/commit/e9dde20590bbcf353dfca528f0005969aceeb8fb ?)

**Comment by egekorkan** [comment]
fixed by https://github.com/eclipse/thingweb.node-wot/commit/e9dde20590bbcf353dfca528f0005969aceeb8fb
