### ISSUE TITLE
Reading all properties doesn't return application/json in the header

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#105]
This results in the response not being displayed as JSON. It is valid JSON though.

**Comment by danielpeintner** [comment]
@egekorkan please take a look at https://github.com/eclipse/thingweb.node-wot/commit/8917ee5a0aff3c9b06e20129d4235362d6023925.

It should resolve the issue.

**Comment by egekorkan** [comment]
seems to be fixed
