### ISSUE TITLE
Language Negotiation

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#110]
node-wot provides a Web server that hands out the TDs of the Things hosted by the node-wot Servient. The code is in the http server binding, in the handler for GET requests.

At the level for serving TDs, we need to add support for the `Accept-Language` header field. It must be checked, and then we need code that transforms multi-lang TDs into a single-lang TD with `@language` set accordingly.

**Comment by danielpeintner** [comment]
The idea is to replace `"title"`/`"description"` with the matching language field in `"titles"`/`"descriptions".`

This works fine for `"description"` but I do believe this might cause issues with `"title"` given that `"title"` is used for URI building (e.g., `"http://192.168.178.24:8080/counter/properties/count"`);

Any thoughts/opinions?

**Comment by mkovatsc** [comment]
Well, actually I remember writing some code that resolves name conflicts within the Servient when there are multiple Things with the same name/title. In that sense, there has not been any strict coupling to the URI -- which should never be expected by anyone anyway.

I don't see a problem, as the mapping to a free URI path is done upon exposing a Thing, a unique event within its life cycle. The mapping from the name/title directly to the URI path has been a convenience aspect only from the beginning and has been brittle anyway (urlencode...).

**Comment by danielpeintner** [comment]
OK.

Language Negotiation has been implemented in  https://github.com/eclipse/thingweb.node-wot/commit/e037e64f7b1f2a2847d5a97cb9a525fc96e91c14.

As discussed, we may want to add a a config option (wot-servient.conf.json) to switch off language negotiation given that it might surprise people when using a browser (e.g., fetching a TD from a browser might return the requested TD in the configured browser language)

**Comment by mkovatsc** [comment]
Was also interop tested with Hitachi. Closing.
