### ISSUE TITLE
Problem creating 2 wot servers (nice to have)

### ISSUE THREAD

**Issue by erkann-sen** [eclipse/thingweb.node-wot#117]
when creating two servers after each other, 2nd one gives problem saying port is used,
I know it can be done by changing default port 8080 to sth else and creating 2nd one or creating it at the same time with 2 files in argument
But it will be nice to have having an argument like "--httpport 8081" or in small version "-hp 8081" to assign port when creating the server 
example command: wotservient sth.js -hp 8081

**Comment by danielpeintner** [comment]
Question: Wouldn't we need a *similar* argument for CoAP and such then?
