### ISSUE TITLE
Troubles Installing on Windows

### ISSUE THREAD

**Issue by anismek** [eclipse/thingweb.node-wot#121]
After a successful _npm install_ I got the following error trace when trying _npm run build_.
Could you please help me ?

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 verbose lifecycle @~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle @~prebuild: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\z0041kev\git\eclipse\thingweb.node-wot\node_modules\.bin;C:\Users\z0041kev\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\z0041kev\bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Go\bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs;C:\Users\z0041kev\AppData\Local\Microsoft\WindowsApps;C:\Users\z0041kev\go\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Java\jdk1.8.0_201\bin;C:\Program Files\Apache Software Foundation\apache-maven-3.6.1\bin;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32\Lib\venv\scripts\nt;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\setuptools;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pip\_vendor\distlib;C:\Users\z0041kev\AppData\Local\Programs\Python\Python37-32\Lib\distutils\command;C:\Users\z0041kev\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
8 verbose lifecycle @~prebuild: CWD: C:\Users\z0041kev\git\eclipse\thingweb.node-wot
9 silly lifecycle @~prebuild: Args: [ '/d /s /c', 'npm run bootstrap' ]
10 silly lifecycle @~prebuild: Returned: code: 1  signal: null
11 info lifecycle @~prebuild: Failed to exec prebuild script
12 verbose stack Error: @ prebuild: `npm run bootstrap`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
12 verbose stack     at EventEmitter.emit (events.js:198:13)
12 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid @
14 verbose cwd C:\Users\z0041kev\git\eclipse\thingweb.node-wot
15 verbose Windows_NT 10.0.17134
16 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
17 verbose node v10.16.0
18 verbose npm  v6.9.0
19 error code ELIFECYCLE
20 error errno 1
21 error @ prebuild: `npm run bootstrap`
21 error Exit status 1
22 error Failed at the @ prebuild script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
`

**Comment by wiresio** [comment]
Did you install the Windows build tools?

`npm install -g --production windows-build-tools`

**Comment by anismek** [comment]
> Did you install the Windows build tools as administrator?
> 
> `npm install -g --production windows-build-tools`

Mea culpa ! I did run that command indeed but unfortunately not with administrator privileges part: so it did not succeed and I missed that.
Now things seem to work as expected.

Thanks a lot.
