### ISSUE TITLE
Outdated examples

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#123]
In the `examples` folder we seem to have some outdated examples that refer to *old* node-wot versions.

Do we plan to update them, or asked differently do we actually need them?
(e.g., https://github.com/eclipse/thingweb.node-wot/blob/master/examples/servients/coap-servient/package.json links to version `"0.4.0"`)

IF we need (or want) them we might need to spend some time to update them.

Any opinions?

**Comment by danielpeintner** [comment]
PR https://github.com/eclipse/thingweb.node-wot/pull/178 should resolve this issue

**Comment by egekorkan** [comment]
Isn't this fixed now and be closed?

**Comment by danielpeintner** [comment]
Yes, but I kept the issue open because the process of creating JS examples is only partially automated.

So far I do not have a better way of solving it --> let's close the issue.
