### ISSUE TITLE
writemultipleproperties and writeallproperties are generated even if no property is writeable

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#124]
If I have an exposer that has multiple properties but all are readOnly, in the forms array in the root level, the op still has `writeallproperties` and `writemultipleproperties`. The counter example already shows this issue

**Comment by danielpeintner** [comment]
@egekorkan can you create a a test-case that shows the issue?

**Comment by egekorkan** [comment]
Sure! Just for precision, the test would be at `thingweb.node-wot/packages/core/test/ServerTest.ts` and I would create a Thing with two readOnly properties. In the exposedThing, I would then check to make sure that the root forms don't have writeallproperties or writemultipleproperties?

Just for now, you can see this happening with counter.js example.

**Comment by egekorkan** [comment]
The issue is in the http-binding in [this line](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-server.ts#L193) where these op values are always added

**Comment by danielpeintner** [comment]
https://github.com/eclipse/thingweb.node-wot/commit/7d0858614ec0833439caa4349c4a2013a80911a4 should resolve the issue. Can you confirm?

**Comment by egekorkan** [comment]
I can confirm that this issue is solved, now read/write for multiple properties are added according the the readOnly/writeOnly property keys
