### ISSUE TITLE
Writing for all properties do not work

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#125]
In the counter example, if I change the script such that the properties are not readOnly, I still cannot write using `writeallproperties`. So doing a PUT or POST request to `counter/all/properties` returns method not allowed. Is this the intended way of doing it?

**Comment by danielpeintner** [comment]
I don't think writeAll methods and other recent updates are part of the master branch.

Instead there is a `next-api-2019` branch that is still WIP that has support for these features and is  also backed with some test-cases.
see https://github.com/eclipse/thingweb.node-wot/blob/next-api-2019/packages/core/test/ClientTest.ts#L331-L353

**Comment by danielpeintner** [comment]
@egekorkan  the `next-api-2019` branch has been merged into `master` and [writeMultipleProperties(...)](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L246-L263) should work as expected now.

Please reopen if you encounter any issues
