### ISSUE TITLE
[question] MQTT properties are only observable by behavior

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#126]
When we generate a servient via `wot-servient` command and by allowing only MQTT in the configuration, the TD generated has the following snippet:
```
	"properties": {
		"count": {
			"type": "integer",
			"description": "current counter value",
			"iot:Custom": "example annotation",
			"observable": true,
			"readOnly": true,
			"writeOnly": false,
			"forms": [{
				"href": "mqtt://test.mosquitto.org/counter/properties/count",
				"contentType": "application/json",
				"op": ["observeproperty", "unobserveproperty"]
			}]
		},
```
It seems wrong since I should be able to read this property due to `readOnly:true` but `readproperty` is not present in the `op` values.
Also as a side note, what if we actually want to say that this property is `observeOnly`?

**Comment by danielpeintner** [comment]
Do you mean that
`"op": ["observeproperty", "unobserveproperty"]`

should be
`"op": ["readproperty", "observeproperty", "unobserveproperty"]`

?. That would be *my* expectation.

> Also as a side note, what if we actually want to say that this property is observeOnly?

This seems to be a question for the TD specification, right?

**Comment by egekorkan** [comment]
> Do you mean that
"op": ["observeproperty", "unobserveproperty"]

> should be
"op": ["readproperty", "observeproperty", "unobserveproperty"]

Yes, sorry for the confusion.

**Comment by egekorkan** [comment]
One way to implement this would be to pass the retain option with the publish option as can be seen [here](https://www.npmjs.com/package/mqtt#publish)

**Comment by egekorkan** [comment]
Also an additional issue about this, the TD generated says observable:false but the forms with MQTT have an op value with `observeproperty`

**Comment by mjkoster** [comment]
The binding information (op values) should be the ultimate source of truth for what operations are supported on a particular URL. The meta0properties readOnly and writeOnly are more of hints. 

I guess we include observe as a type of read, but I agree readOnly could be confusing.

Looks like another reason to structure the hints as readable, observable,  and writable instead of read-only and write-only.

**Comment by egekorkan** [comment]
Available on master branch, closing
