### ISSUE TITLE
readAllProperties in client is not available

### ISSUE THREAD

**Issue by MuthuramanCT** [eclipse/thingweb.node-wot#127]
Correct me if its already available. 

- readAllProperties is possible by http request but we don't have specific function to readAllProperties option in the client. Like read() and invoke().

**Comment by danielpeintner** [comment]
> readAllProperties is possible by http request but we don't have specific function to readAllProperties option in the client. Like read() and invoke().

This is partly correct.

The code in the master branch does not contain `readAllProperties()` given that it belongs to an *older* style of API.

However, we are currently working on the updated API (see https://w3c.github.io/wot-scripting-api/) which contains `readAllProperties()`. The work is done in a "next-api-2019" branch (see https://github.com/eclipse/thingweb.node-wot/blob/next-api-2019/packages/core/src/consumed-thing.ts#L213-L218).

We plan to merge this branch into the master *soon* ...

**Comment by MuthuramanCT** [comment]
@danielpeintner Thanks for your update.
