### ISSUE TITLE
Automated changelog

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#13]
Copied from https://github.com/thingweb/node-wot/issues/26.

We already use conventional commit messages for thingweb.node-wot. What is missing is an automated changelog.

Options:
* commitizen & conventional-changelog: https://commitizen.github.io/cz-cli/
* https://github.com/semantic-release/semantic-release

**Comment by relu91** [comment]
Is this still something desirable? I know that @danielpeintner prefers a more manual approach. We should get a resolution 😃

**Comment by danielpeintner** [comment]
At the moment we not really have *any* changelog.

Conventional commit messages might help to create "automated changelogs" but this also requires some proper checking. 
My personal take on that is that we do *not* need it.

**Comment by danielpeintner** [comment]
GitHub release process supports automatic release-notes

See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
