### ISSUE TITLE
Missing dependency in the latest release

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#133]
Trying to install the latest version of CLI module results in the following error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @node-wot/binding-mqtt@0.6.3-SNAPSHOT.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@node-wot/cli'
npm ERR! notarget
```
It seems that `@node-wot/binding-mqtt` version has not been bumped or updated.

**Comment by danielpeintner** [comment]
Sorry, MQTT has not been properly published on NPM.

Please try again. It should be available now, see https://www.npmjs.com/package/@node-wot/binding-mqtt

**Comment by relu91** [comment]
Perfect! thank you, problem solved 👍
