### ISSUE TITLE
[binding-mqtt] MqttBrokerServer crashes when there is no payload

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#139]
Disclaimer: Currently testing in 0.6.3 version but this didn't seem to change in the 0.7.0

In [the line 144 of the MqttBrokerServer.ts](https://github.com/eclipse/thingweb.node-wot/blob/a00cc12e3cf31bdb36affd770111c2b788dc8bcc/packages/binding-mqtt/src/mqtt-broker-server.ts#L144) there is a direct `JSON.parse` code that automatically tries to parse the payload while assuming that payload exists in the first place. Maybe there is no payload or the payload is not JSON (which is mostly the case in the MQTT world). This results in the servient crashing with a message like "Unexpected end of JSON input". 

**To reproduce:**
- Start a servient with MQTT binding and that has an action
- Use an MQTT client like mosquitto or MQTTFX
- Send an empty payload. In mosquitto's CLI version the command looks like this: `mosquitto_pub -t "/PanTilt/actions/goHome" -h "test.mosquitto.org" -p "1883" -m ""` and in MQTTFX it would be a simply empty payload.
- Look at the servient's console output

**Solution proposals**
Not sure but, I would suggest using ContentSerdes like the other bindings?
The minimal remedy would be a try catch at this `JSON.parse`.

**Comment by danielpeintner** [comment]
@wiresio may I ask you to look into the issue and propose a fix?

**Comment by wiresio** [comment]
I just tested having no issues with examples/script/mqtt-publish.js and examples/scripts/mqtt-subscribe.js where I changed in mqtt-publish.js:
`thing.emitEvent("counterEvent", counter);`
to
`thing.emitEvent("counterEvent", /*counter*/);`
Am I missing something?

**Comment by egekorkan** [comment]
The issue happens not when the Exposed Thing publishes something but when it receives something in a subscribed topic.

**Comment by egekorkan** [comment]
And also the issue may not present itself when the Consumer is also implemented in node-wot since it might always send a JSON payload

**Comment by danielpeintner** [comment]
fixed with https://github.com/eclipse/thingweb.node-wot/pull/159
