### ISSUE TITLE
[binding-mqtt] MQTT binding forces adding properties as events

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#141]
I have an Exposed Thing with both MQTT and HTTP servers, i.e.:
```
servient.addServer(httpServer);
servient.addServer(mqttServer);
```
For the WoT.produce, I add a TD with no Events but with a property interaction called `panPosition`, i.e.:
```
this.WoT.produce(
    {
      ....
      title : "PanTilt",
      properties:{
      	panPosition:{
		title:"Pan Position",
		readOnly: true,
		type: "number"
	}
      }
    ....
    });
```
Upon running this script, I get the following errors:
```
(node:7888) UnhandledPromiseRejectionWarning: Error: ExposedThing 'PanTilt', no event found for 'panPosition'
    at /home/pi/wot-pantilt/node_modules/@node-wot/core/dist/exposed-thing.js:283:24
    at new Promise (<anonymous>)
    at Object.ExposedThing.subscribeEvent (/home/pi/wot-pantilt/node_modules/@node-wot/core/dist/exposed-thing.js:273:16)
    at _loop_1 (/home/pi/wot-pantilt/node_modules/@node-wot/binding-mqtt/dist/mqtt-broker-server.js:54:23)
    at /home/pi/wot-pantilt/node_modules/@node-wot/binding-mqtt/dist/mqtt-broker-server.js:74:17
    at new Promise (<anonymous>)
    at MqttBrokerServer.expose (/home/pi/wot-pantilt/node_modules/@node-wot/binding-mqtt/dist/mqtt-broker-server.js:49:16)
    at /home/pi/wot-pantilt/node_modules/@node-wot/core/dist/servient.js:196:77
    at Array.forEach (<anonymous>)
    at Servient.expose (/home/pi/wot-pantilt/node_modules/@node-wot/core/dist/servient.js:196:22)
```
This means that it is expecting an event for the property I have added. I have added no events. 
If I remove the addition of the mqttServer, the problem is solved, it is not expecting an event. Also if I add `panPosition` as an event, it is also solved. Funny enough, when I add the events, the properties are still added to the TD with MQTT binding only for `observeproperty` and `unobserveproperty`. Similar for the events, there are HTTP and MQTT forms, however, this is what I would expect anyways.

I find this very misleading. I understand that MQTT is event based but in this case, it should either:
- Ignore properties for the mqtt binding
- Make the property observable and not try to add events.

Note: This issue didn't exist in the 0.6.x version

**Comment by danielpeintner** [comment]
The problem is this code part (see https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-mqtt/src/mqtt-broker-server.ts#L105-L131)

we walk over properties and try to `subscribeEvent()`.
I think it should be `observeProperty()`.

Let me look into it more closely and I will provide a fix

**Comment by danielpeintner** [comment]
Please test and close if it resolves the issue

**Comment by egekorkan** [comment]
seems to be fixed :) Could you push to npm as a snapshot

**Comment by danielpeintner** [comment]
0.7.0-SNAPSHOT.3 has been published
