### ISSUE TITLE
Cannot use TD.x in Typescript files

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#143]
I have the following Typescript file:
```
import * as WoT from "wot-typescript-definitions"
...
export class WotDevice {
    public thing: WoT.ExposedThing;
    public WoT: WoT.WoT;
    public td: WoT.ThingDescription;

...
        this.thing.setActionHandler("tiltTo", (angle) => { 		         
        	return new Promise((resolve, reject) => {
	            if (!ajv.validate(this.td.actions.tiltTo.input, angle)) {
	                reject(new Error ("Invalid input"));
	            }
	            else {
	                resolve(this.tiltTo(angle));
	            }
	        }); 
        });
...
}
```
When I run tsc to build the .js files, I get the following error:
```
src/base.ts:337:40 - error TS2339: Property 'actions' does not exist on type 'ThingDescription'.
  Property 'actions' does not exist on type 'object'.

337              if (!ajv.validate(this.td.actions.tiltTo.input, angle)) {

```
I get the same error for all the actions, events, properties that I use in the same way. 
When I look in the wot-typescript-definitions, ThingDescription is defined as the following:
`export declare type ThingDescription = object | { [key: string]: any; };`

Is this the source of the problem? I think since it is not explicitly defined, I get this error. In the 0.6.x version this didn't exist and if I use `thing.actions`, I get the same error, which I can understand since `ConsumedThing.actions`, which is inherited by ExposedThing, is removed in the 0.7.x style of the API.

**Comment by danielpeintner** [comment]
`this.td.actions` does not exist anymore with the latest scripting API.

What you need to do is to call  [`getThingDescription()`](https://www.w3.org/TR/2019/WD-wot-scripting-api-20191028/#the-getthingdescription-method) and get the information and/or metadata from there...

**Comment by egekorkan** [comment]
I have tried this as well since the td is actually obtained from getThingDescription() but during build time, it says that ThingDescription does not have actions. In runtime this is not an issue, it works and gets the actions element.

**Comment by danielpeintner** [comment]
Can you please share the full sample so that we can reproduce the issue.

**Comment by danielpeintner** [comment]
According to my understanding this is a TypeScript issue.
`object` without any additional information should be able to be "any" object.

Changing `object` to `any` might be a temporary solution for now but I don't think it is correct given that it could be a `number` in the end which is surely wrong.

I wonder whether we can change the existing definition `type ThingDescription = object | { [key: string]: any; };` to something else that is still accurate and also works in your use-cases...

**Comment by egekorkan** [comment]
> I wonder whether we can change the existing definition type ThingDescription = object | { [key: string]: any; }; to something else that is still accurate and also works in your use-cases...

I think this is the way to go but I cannot contribute to what it should be :(

**Comment by adriankast** [comment]
For me using only `{ [key: string]: any}` works, which is in my opinion preferable (because that should match exactly what we are trying to constrain, at least I don't understand the advantage of `| object`, maybe somebody can share thoughts regarding this?). But also `object & { [key: string]: any}` would work (as [intersection type](https://www.typescriptlang.org/docs/handbook/advanced-types.html#intersection-types) ).

**Comment by danielpeintner** [comment]
@egekorkan  can you please check whether `object & { [key: string]: any}` works for you?
This seems like the best approach to me.

@adriankast  the rational to use also `object` is to match with the Scripting API that types it as `object` (see 
https://www.w3.org/TR/wot-scripting-api/#dom-thingdescription)

**Comment by egekorkan** [comment]
Sadly I still get the same error :( However `{ [key: string]: any}` works

**Comment by danielpeintner** [comment]
with https://github.com/eclipse/thingweb.node-wot/commit/d6f5ee13e41675df9d769fe2cb519b0456796eee the definition is changed to `ThingDescription = { [key: string]: any; };`

**Comment by egekorkan** [comment]
This fix works :) Closing
