### ISSUE TITLE
[exposed-thing] Not handling unknown names in emitEvent

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#146]
In the scripting API spec, in the Exposed Thing interface, one has the the [emitEvent method](https://w3c.github.io/wot-scripting-api/#the-emitevent-method) where it says:

> If an Event with the name _name_ is not found in this.getThingDescription().events, throw NotFoundError and terminate these steps.

I find this pattern good but sadly it is not implemented in node-wot. I can try to emit an event with an unknown name and all the information I get in the console is `HttpServer on port 8080 got internal error on invoke '/counter/actions/decrement': Cannot read property 'getState' of undefined` which is not NotFoundError.

To reproduce:
- Open the counter example
- Change [this line](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js#L140) and replace `"change"` with e.g. `"change123"`.

Concrete line where the fixe(s) should be applied to:
- emitEvent: https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/exposed-thing.ts#L85

**Comment by danielpeintner** [comment]
commit should resolve the issue. Please reopen if this is not the case....

**Comment by egekorkan** [comment]
I am not authorized to reopen the issue but the fix has only silenced the issue by checking if the name exists and emitting, however, it should throw the error NotFoundError if the name does not exist. Now the event is never emitted and the script is not aware of the mistake at all.

**Comment by danielpeintner** [comment]
>  it should throw the error NotFoundError if the name does not exist.

I believe there is no such error named `NotFoundError`..
Good enough to throw the following?

`throw new Error("NotFoundError for event '" + name + "'");`

**Comment by egekorkan** [comment]
I think for the developer it is fine to throw this error but in order to respect the Scripting API spec, a new error type should be created since if one uses node-wot as a dependency they will not necessarily understand this string of error description and will need to parse and filter the string.

**Comment by danielpeintner** [comment]
for the time being let's throw a default error (see https://github.com/eclipse/thingweb.node-wot/commit/06e3236a7d8b151959b97ced86441048b6bc53f5)

**Comment by egekorkan** [comment]
This is implemented, closing
