### ISSUE TITLE
[question] Forcing writeable for readOnly properties

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#148]
The implementation of [setPropertyWriteHandler](https://w3c.github.io/wot-scripting-api/#the-setpropertywritehandler-method) in node-wot makes a property writeable even if it was specified to be readOnly in the TD given in the argument of `produce()` method. This can be seen [here](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/exposed-thing.ts#L136). 

I don't see why this decision was taken. Shouldn't the user be warned that this property cannot take a `propertyWriteHandler`? Scripting API does not specify such behavior and can result in two Scripting API implementations to expose a different TD. By the way, I am not saying that this is necessarily bad but either there is something missing in the Scripting API or there was a discussion I have missed.

**Comment by danielpeintner** [comment]
I believe the [reference](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/exposed-thing.ts#L136) you are pointing to comes from a time where a TD was programmatically created (e.g., `addProperty("name", handler, ..)`).

I think with the current API I tend to agree with @egekorkan that readOnly attributes should not allow for setting write handlers.

Note: There is a *related* issue: see https://github.com/w3c/wot-scripting-api/issues/106

**Comment by danielpeintner** [comment]
@egekorkan  does https://github.com/eclipse/thingweb.node-wot/commit/faf786ea8d28712036495e4f50671bb309e3f57c resolve the issue for you?

**Comment by egekorkan** [comment]
I confirm that this is fixed but the other way around, i.e. setting a read handler for a writeOnly property still works. I think the same should be done for this case as well.

**Comment by danielpeintner** [comment]
Good catch, fixed with https://github.com/eclipse/thingweb.node-wot/commit/3b24497f53f256fb15a95c109d178ca00489cf61

**Comment by egekorkan** [comment]
I can confirm that this is implemented now as well, closing :)
