### ISSUE TITLE
[question] Should a property value serilized inside exposed thing descriptor?

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#149]
Hi, we are doing some tests with thingweb.node-wot. In particular, we are creating a simple thing that virtualizes an accelerometer. After exposing the thing and retrieve his description from the HTTP endpoint, we receive this JSON (simplified):
```javascript
{
  "title": "DA00AW2K-3-measure",
  "properties": {
    "AccX": {
      "type": "float",
      /* other fields */
      "forms": [ /*form definitions */],
      "value": 0.99774169921875 // here
    }
  }
}
```
My question is: should the current value of the Acceleration be exposed inside the TD? 
Or am I missing something and the JSON retrieved by the servient URL is not the TD but a state serialization of the Web Thing?

Thank you for your time.

**Comment by egekorkan** [comment]
The value, which is usually dynamically changing, shouldn't be inside the TD. If it is a constant value, I think the best way is to use the `const` keyword, i.e.:
```
"myConstantProperty": {
      "type": "number", // can be omitted since const gives the type anyways
      "const": 0.99774169921875,
      "forms": [ /*form definitions */]
    }
```
Normally, the acceleration should be read upon executing a readproperty operation.

**Comment by relu91** [comment]
That's exactly my point. So why does the value being serialized there? My lab co-workers pinpointed this [line](https://github.com/eclipse/thingweb.node-wot/blob/06e3236a7d8b151959b97ced86441048b6bc53f5/packages/core/src/exposed-thing.ts#L169). Is it a bug or a feature? 😄

**Comment by egekorkan** [comment]
I am not 100% sure but @danielpeintner can confirm? This part of the code is actually not visible to the Consumer of the Exposed Thing, thus has nothing to do with the TD. This basically reads the property value but internally. 
I think another way to look at it is with writeproperty() on an Exposed Thing. Even if the property is not writeable, you can still call this method as seen [in the counter example](https://github.com/eclipse/thingweb.node-wot/blob/06e3236a7d8b151959b97ced86441048b6bc53f5/examples/scripts/counter.js#L108)

**Comment by relu91** [comment]
Thanks @egekorkan.  Just to clarify a little bit the problem. I'm reading the property through an HTTP GET not from the js APIs. That line of code posted above should be called each time a `readproperty` operation is called.

**Comment by egekorkan** [comment]
For an HTTP based readproperty request (defaults to HTTP GET), you would be interacting with a ConsumedThing and [this line in consumed-thing.ts](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L159) would be executed. This has then calls the readResource method from the specific client (HTTP, CoAP etc.) at [this line](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L173)

**Comment by egekorkan** [comment]
I have understood the issue which is actually a rather important bug. If one sets their own read handler for a property, with the call of the read handler, the TD is changed by node-wot and the `value` key is added with the value gotten from the custom property handler.

To reproduce:
- Take the counter.js example
- Add the following lines to the very beginning:
```
function myPropertyHandler(){
		return new Promise((resolve, reject) => {
			// read something
			resolve(12);
		});
    }
```
- Add the following line after `thing.writeProperty("lastChange", (new Date()).toISOString());`

```
thing.setPropertyReadHandler("count",myPropertyHandler);
```
- Do a GET request to the TD at `http://localhost:8080/counter/`
- Do a GET request to the count property at `http://localhost:8080/counter/properties/count`. You should get `12` as the response payload
- Do again a GET request to the TD at `http://localhost:8080/counter/`
- Notice that there is now a new key in the property `count` called `value` with a value of 12

I have tested this with the GitHub version of node-wot

**Comment by egekorkan** [comment]
Thank you for finding it @relu91 !

**Comment by danielpeintner** [comment]
Mhh, I wonder whether we really need to store the value internally like the comments says
> `// update internal state in case writeHandler wants to get the value`

If so the alternative would be to *clean* the TD once `getThingDescription()` is called. Essentially removing all `value` in properties.

Other "clean-up" is done already.. see https://github.com/eclipse/thingweb.node-wot/blob/master/packages/td-tools/src/td-parser.ts#L189-L200

I would tend to change `serializeTD()` accordingly to not break anything else. Any opinions?

**Comment by egekorkan** [comment]
I would not try to clean anything with getThingDescription since the programmer is allowed to put extra keys into the TD.

**Comment by danielpeintner** [comment]
With https://github.com/eclipse/thingweb.node-wot/commit/b4ead67ef8b7e7c1aacb3c43bd0976bc89c74851 we do not store the value internally anymore. If we encounter any issue we can bring back the *old* behavior....

**Comment by egekorkan** [comment]
I confirm that this is resolved now

**Comment by relu91** [comment]
Hi, sorry for catching up a little bit late! Thank you @egekorkan for pinpointing the problem! and also thank you @danielpeintner for fixing the issue. I'd just add my two cents about the chosen solution. 

In general, I prefer to not store values of properties automatically inside the thing state. It feels like an early optimization problem. Users could decide to create caching mechanisms for properties values as they need, following the application scenario. 

So I agree with the final decision, but I'd rather remove the commented code. I'm afraid that it will stay there forever since no one will have ever the context to decide whether or not to reintroduce the comment line... even if there is a link pointing to this issue. It's not a complex algorithm so I think it won't hurt too much to remove the line completely.

**Comment by danielpeintner** [comment]
fair arguments https://github.com/eclipse/thingweb.node-wot/commit/15c344eb5b239fc8f537c275f5a9b644157322ed
