### ISSUE TITLE
[binding-http] Unsubscribing from an Event does not work

### ISSUE THREAD

**Issue by adriankast** [eclipse/thingweb.node-wot#151]
# Setup
- thingweb.node-wot v0.7.0-SNAPSHOT.3
- consumed Thing with http form
# Doing
- subscribe to an Event with the `subscribeEvent(name, listener, options?)` function of a consumed Thing
- trying to unsubscribe from the mentioned Event with the `unsubscribeEvent(name)` of the same Thing
# Expected Behavior
The given `listener` should not be called anymore and no further http `GET` requests being sent, for the mentioned event.
# Observed Behavior
- The function `unsubscribeEvent` calls `unlinkResource` of the protocol binding, which for http sends a `DELETE` Request to the event form. This leads to the error:
```Javascript
http-client.js?7d6f:334 Uncaught (in promise) Error: Client error: Method Not Allowed
    at HttpClient.checkResponse (http-client.js?7d6f:334)
    at IncomingMessage.eval (http-client.js?7d6f:133)
    at IncomingMessage.emit (events.js:199)
    at endReadableNT (_stream_readable.js:1141)
    at processTicksAndRejections (internal/process/task_queues.js:81)
```
while the `listener` function is still being called and the longpoll protocoll kept alive (-> further http `GET` requests are sent)

**Comment by egekorkan** [comment]
This issue is also present in CoAP. In order to stop observing, the client should send a GET request with Observe option set to 1. At the moment it sends a DELETE request, like in HTTP, which is semantically incorrect since we don't want to delete the resource itself but just the observation.

**Comment by danielpeintner** [comment]
fixed by https://github.com/eclipse/thingweb.node-wot/pull/233
