### ISSUE TITLE
[proposal][binding-mqtt] Adding writeable property feature

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#152]
For a node-wot exposed thing:
In the current state, there is no way to write to a property through MQTT since only `observeproperty` and `unobserveproperty` are added for the forms no matter what, as mentioned in #126. In addition to `readproperty`, we can add the writeproperty functionality where a separate form is created with an `href` like `mqtt://myBroker/myThing/properties/myProperty/writeproperty` where the expected MQTT method would be to publish to this topic. This implies that the Exposed Thing should subscribe to this topic, like an action. [Bindings Template](https://w3c.github.io/wot-binding-templates/#mqtt-vocabulary) already explains how the default value for a `writeproperty` in MQTT should be. This would also imply that [line 150](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-mqtt/src/mqtt-broker-server.ts#L150) should be changed since there would be 5 segments in the topic.

Finally, a `writeproperty` form would look like the following:
```
        {
          "href": "mqtt://myBroker/myThing/properties/myProperty/writeproperty",
          "op": ["writeproperty"],
          "contentType": "application/json",
          "mqv:controlPacketValue": "PUBLISH"
        }
```

**Comment by danielpeintner** [comment]
@wiresio any opinion/proposal?

**Comment by wiresio** [comment]
I do not like the fact that we introduce the "deeper" level _writeproperty_. Isn't it sufficient to evaluate the "op" key to find out about the actual operation?

**Comment by egekorkan** [comment]
In this case it is not possible since if I have two subscribers to the property of the exposed thing (publisher) and when one of them also publishes to the topic, then the other subscribers will think that the exposed thing has published a new property value. Maybe the exposed thing was offline but the broker will still notify the subscribers. In the end, all we are doing with a TD is describing the broker and not necessarily the exposed thing.

If we don't want to change the topic, we will need to identify the publisher and make sure that it is the exposed thing. This would imply a change in the broker since the brokers should not do this and the subscribers should not care who publishes (source [here](https://stackoverflow.com/a/48114255/3806426)).

I think it is necessary to change the topic (i.e. href). We do this already for observable properties in the http binding since a GET request can be for a `readproperty` or `observeproperty` and there is the additional `/observable` in the href as a result.

In the end, nothing should change for the Consumer since it just looks at the `op` value that it is interested in and copy-pastes the topic to subscribe and nothing would/should change if the topic had 10 or 20 levels.

**Comment by wiresio** [comment]
> We do this already for observable properties in the http binding since a GET request can be for a readproperty or observeproperty and there is the additional /observable in the href as a result.

I wasn't aware of this. So, then your proposal makes sense.

**Comment by danielpeintner** [comment]
@egekorkan could you add  an `else if (segments.length === 5 ) {` after line https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-mqtt/src/mqtt-broker-server.ts#L150 and handle it accordingly

**Comment by egekorkan** [comment]
Available on master branch, closing
