### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#167]
// running `npm outdated` in each folder shows outdated dependencies.. //

Issues with _latest_ dependencies

### rxjs
Updating rxjs dependency from "5.4.3" to "6.x.x" (e.g., 6.5.4) fails due to breaking changes.

https://stackoverflow.com/questions/50176029/rxjs-subscription-has-no-exported-member-subscription

Look into whether "rxjs-compat" might be a solution OR try the migration path.

### mocha
see --compilers flag
https://github.com/mochajs/mocha/wiki/compilers-deprecation

* "mocha": "3.5.3" --> "mocha": "7.0.1"
* "mocha-typescript": "1.1.8" --> "mocha-typescript": "1.1.17"
* "test": "mocha --compilers ts:ts-node/register" -->
"test": "mocha --require ts-node/register \"test/**/*.{js,ts}\""

Issue: the tests hang after being finsished for core, mqtt, .. (anything open or not properly closed? https://stackoverflow.com/questions/51046665/mocha-hangs-after-tests-have-finished)

Related? : https://github.com/mochajs/mocha/issues/2407

**Comment by danielpeintner** [comment]
We did update *some* dependencies. Moreover I think this is an ongoing process. Hence closing this issue.

**Comment by egekorkan** [comment]
https://david-dm.org/ we can also use this to track and show all the dependencies

**Comment by danielpeintner** [comment]
> https://david-dm.org/ we can also use this to track and show all the dependencies

Looks interesting. Since we have multiple package.json files I am not sure it will work though...
