### ISSUE TITLE
Timeline for CBOR implementation?

### ISSUE THREAD

**Issue by Citrullin** [eclipse/thingweb.node-wot#168]
Hey, I just wanted to know, if there is a timeline for the CBOR implementation and if so, what is it? 
Thanks :)
Have a nice day/week.

**Comment by danielpeintner** [comment]
Hi @Citrullin,

there is no decided milestone or date we can share when CBOR (and likely other content types) are available.
Having said that, you are encouraged and welcome to support us.

A good entry point is `ContentSerdes` (see https://github.com/eclipse/thingweb.node-wot/tree/master/packages/core/src/codecs).

Thanks!

**Comment by Citrullin** [comment]
Thanks, I will take a look, when I implement something for WoT. :)
