### ISSUE TITLE
Fix OPCUA tests

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#169]
OPCUA tests cause issues

see https://travis-ci.org/eclipse/thingweb.node-wot/builds/651908408?utm_source=github_status&utm_medium=notification

```
  1 failing

  1) OPCUA client test

       "before all" hook for "should read a property":

     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/build/eclipse/thingweb.node-wot/packages/binding-opcua/test/opcua-client-test.ts)
```

So far all tests are skipped (see https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-opcua/test/opcua-client-test.ts#L30)

@lukesmolo can you look into it

**Comment by lukesmolo** [comment]
ok, it perfectly works on my machine, with node v13.6.0. By the logs it seems it is not able to instantiate the opcua server simulator. Let me check with different nodejs versions, I'll let you know

**Comment by lukesmolo** [comment]
Ok, solved. For some reason, in the third configuration of travis the OPC UA server requires a lot of time to start, so I needed to increment the timeout.

**Comment by danielpeintner** [comment]
solved by https://github.com/eclipse/thingweb.node-wot/pull/172.

Thanks!
