### ISSUE TITLE
package "integration-tests" needed?

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#170]
The package [`integration-tests`](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/integration-tests) contains a single test file w.r.t. basic TD parsing.

Do we need this package?
TD parsing should be part of `td-tools`...

Any comments/opinions?

**Comment by egekorkan** [comment]
+1 ,i.e. could be removed

**Comment by wiresio** [comment]
+1 Please remove.
