### ISSUE TITLE
How to install new/different versions of NodeJS, e.g., on Raspberry Pi?

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#18]
Using NPM, you can install NodeJS independent from the usually outdated package managers such as apt. This is nicely done by [n](https://www.npmjs.com/package/n):

```
sudo npm cache clean -f
sudo npm install -g n
```

To get the "stable" version:
```
sudo n stable
```

To get the "latest" version:
```
sudo n latest
```

Finally, make the `node` command available through:
```
sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/node
```

**Comment by rolandma** [comment]
I run 
`$ curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -` 
to update the package repository then the Rpi was able to find and install the latest version of Node Js, and that also resolved my problem when I run npm install which I had problem with on npm v1.x.x

**Comment by rolandma** [comment]
Somehow I installed the latest version of NodeJS, v11.0.0, which is not supported for to build, I had to remove the whole v11 and delete the file in usr/local/bin/node for the run build to continue.

**Comment by wiresio** [comment]
Resolved by updating Readme
