### ISSUE TITLE
Following the README.md steps to set up `wot-runtime` doesn't seem to work

### ISSUE THREAD

**Issue by jenlincode** [eclipse/thingweb.node-wot#180]
Hello! I followed the steps on the README.md at https://github.com/eclipse/thingweb.node-wot/blob/master/README.md and it seems calling `wot-runtime` doesn't work:

> How to get the library
> As a Node.js dependency
> If you want to use node-wot as a library in your Node.js application, you can use npm to install the node-wot packages that you need. To do so, cd inside you application folder, and run:
> 
> npm install @node-wot/core
> npm install @node-wot/binding-coap
> Alternatively you can add @node-wot/<package-name>as a dependency to your package.json.
> 
> As a dev dependency (debugging)
> If you want to develop applications for wot-runtime, you can use the command-line interface to run and debug your local scripts. First, install the CLI module as a dev-dependency:
> 
> npm install @node-wot/cli --save-dev
> Then to start .js files in the current directory use the following command wot-runtime (or node packages\cli\dist\cli.js):
> 
> For example, if you want to run a specific file or a list of files just append the file paths:
> 
> wot-runtime script1.js ./src/script2.js
> Finally, to debug use the option --inspect or --inspect-brk if you want to hang until your debug client is connected. Then start Chrome Dev Tools or vscode debugger or your preferred v8 inspector to debug your code.
> 
> For further details check: wot-runtime --help

**Comment by danielpeintner** [comment]
Note:
`wot-runtime` and `node packages\cli\dist\cli.js` are interchangeable.

There is following description in the README.md
> Without the "Link Packages" step, the `wot-servient` command is not available and `node` needs to be used 

@jenlincode is this the pitfall?

**Comment by jenlincode** [comment]
So I've typed:

`npm install @node-wot/core`
`npm install @node-wot/binding-http'
`npm install @node-wot/cli --save-dev`

And that didn't work, so I added:

`npm run link`

But then I ran into the issue `package.json` doesn't exist. (This is an empty directory.) So I moved the package.json over from my cloned node-wot directory.

But I ran into another error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'link' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose stack Error: missing script: link
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
5 verbose cwd C:\Users\jenlin\Documents\web-of-things\airobotics\test
6 verbose Windows_NT 10.0.18363
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "link"
8 verbose node v10.16.3
9 verbose npm  v6.9.0
10 error missing script: link
11 verbose exit [ 1, true ]

**Comment by danielpeintner** [comment]
node-wot can be run in 2 different ways.
1. as a command-line-interface (cli)
   * via `wot-runtime` or `node packages\cli\dist\cli.js`
2. as a Node.js dependency
   * via `npm install @node-wot/core`, `npm install @node-wot/binding-coap`, ...

If this is not clear I ask you to suggest changes to the readme so that we can improve.

May I also ask you which of the 2 ways you try to run your code. According to your message it seems that you are kind of doing both.

Note: I do not suggest mixing the 2 different ways.

**Comment by relu91** [comment]
Exactly as @danielpeintner is suggesting you are supposed to choose between using node-wot as a CLI command **or** as a library. Mixing the two processes described above might create problems. 

>  I'm trying to get essentially a 'lean' install of node-wot as a library for production

if you are targeting production I think you should go with the first option.

> If this is not clear I ask you to suggest changes to the readme so that we can improve.

Maybe just add a statement right after "How to get the library" saying "choose one of the following modes: " and create a list of the installation options. I guess it might help

**Comment by jenlincode** [comment]
Just to be more clear, I've never been able to get `wot-runtime` to work, and I was asking what the steps are to get it to run. I understand it's the same as `node packages\cli\dist\cli.js` -- which is the command-line-interface I was able to run.

**Comment by jenlincode** [comment]
> 2. as a Node.js dependency
>    
>    * via `npm install @node-wot/core`, `npm install @node-wot/binding-coap`, 

Yes, but as a Node.js dependency, how do you get node-wot to run?

**Comment by relu91** [comment]
I've just tried these steps:
```
mkdir testWoT
cd testWoT
npm init --yes
npm install @node-wot/cli --save-dev
touch main.js
node_modules/.bin/wot-servient main.js
```
Maybe it is just a naming issue; in the latest public cli package the entry point is called `wot-servient` not `wot-runtime`. 

> Can you clarify if it is used as a dependency, is WoT or WotHelpers exposed or run? I'd like an example of what you mean as a dependency.

I am not quite sure of what you mean here, but you could check the example folder (which is now under refactoring) and see that WoT and WoTHelpers are injected and available inside the script ([see here](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js)).

Anyway, I am making a tool to make easier to set-up a WoT application. it might help you in the future check it out [here](https://github.com/UniBO-PRISMLab/wam). **Disclaimer** it is in a very early alpha stage 🤣 .

**Comment by jenlincode** [comment]
> I've just tried these steps:
> 
> ```
> mkdir testWoT
> cd testWoT
> npm init --yes
> npm install @node-wot/cli --save-dev
> touch main.js
> node_modules/.bin/wot-servient main.js
> ```
> 
> Maybe it is just a naming issue; in the latest public cli package the entry point is called `wot-servient` not `wot-runtime`.

Thank you! That was exactly the issue! In the README.md, the step said:

```
For example, if you want to run a specific file or a list of files just append the file paths:

wot-runtime script1.js ./src/script2.js
```

It should be renamed to:
`wot-servient script1.js ./src/script2.js` 

I had run `wot-servient` before, but I was wondering what `wot-runtime` was. Much appreciated for the clarification!

> Anyway, I am making a tool to make easier to set-up a WoT application. it might help you in the future check it out [here](https://github.com/UniBO-PRISMLab/wam). **Disclaimer** it is in a very early alpha stage 🤣 .

Thank you! 👍

**Comment by danielpeintner** [comment]
> It should be renamed to:
> wot-servient script1.js ./src/script2.js

Thanks @jenlincode and @relu91 
fixed with https://github.com/eclipse/thingweb.node-wot/commit/c91674ac9123744b66a850b1d3e5fec725681cc7
