### ISSUE TITLE
[binding-http] Cannot explicitely configure no security in HTTP

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#181]
The http configuration part of the configuration file cannot accept `nosec` for the security scheme, i.e.:
```
        "http": {
            "port": 8080,
            "security": {
                "scheme": "nosec"
            }
        }
```
results in the error message `HttpServer does not allow security without TLS (HTTPS)`
This is happening due to the logic in [this line](https://github.com/eclipse/thingweb.node-wot/blob/a2f1bed088804cdc388d3db73625f06d2efbbbed/packages/binding-http/src/http-server.ts#L79).

I think that it should be possible to specify no security explicitely in the configuration file. At the moment, one has to forget the scheme to specify no security whereas TD specification is not following this logic.

**Comment by fillobotto** [comment]
Moreover I'm not able to use any other security scheme expect for Basic auth.
I'm trying to use Bearer auth but the serialized TD overwrites both `security `and `securityDefinitions ` with [basic auth](https://github.com/eclipse/thingweb.node-wot/blob/f6a814b0231951ded560ba3abb13c818b8a99fff/packages/binding-http/src/http-server.ts#L259)

**Comment by danielpeintner** [comment]
@fillobotto May I ask you to provide a simple test in [http-server-test.ts](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/test/http-server-test.ts) so that
1. We know your input
2. We can fix the issue and have a test for it

If you don't feel comfortable enough please provide some pseudo code to show what you do and what your input looks like.

@egekorkan may I ask you the same. A simple test...

Thanks!

**Comment by egekorkan** [comment]
In order to reproduce,, use the following wot-servient.conf.json with the counter.js script:
```json
{
    "http": {
        "port": 8080,
        "security": {
            "scheme": "nosec"
        }
    }
}
```

**Comment by egekorkan** [comment]
The following added to http-server.ts causes the test to fail:
```js
  @test async "should start and stop a server with no security"() {
    let httpServer = new HttpServer({ port: 58080, security: {scheme: "nosec"}}); //failing also with NoSec

    await httpServer.start(null);
    expect(httpServer.getSecurityScheme()).to.eq("NoSec"); // the actual test we want
    await httpServer.stop();
  }
```
which requires a function to get the security scheme in the http-server.ts

```js
  public getSecurityScheme(): Object {
    return this.securityScheme;
  }
```

If this function is not wanted, the expect can be changed to:
```js
    await httpServer.start(null);
    expect(httpServer.getPort()).to.eq(58080); // some dummy thing to test
```
since the fail happens in starting anyways

**Comment by fillobotto** [comment]
I simply use the following servient.conf.json:

```
{
        "port": 8080,
        "allowSelfSigned": true,
        "serverKey": "security/privatekey.pem",
        "serverCert": "security/certificate.pem",
        "security": {
            "scheme": "bearer"
        }
    }
```
If I expose a Thing through a servient with the following configuration, the resulting TD outputs:

```
"securityDefinitions": {
    "basic_sc": {
        "scheme": "basic",
        "in": "header"
    },
},
"security": [ "basic_sc"],
```

**Comment by relu91** [comment]
@danielpeintner This week I am trying to implement oAuth2.0 for node-wot as discussed with @sebastiankb. I can look at this. I'd probably need to fix this to test oAuth2.0 anyway... 😄 of course if are not already solved it.

**Comment by danielpeintner** [comment]
> @danielpeintner This week I am trying to implement oAuth2.0 for node-wot as discussed with @sebastiankb. I can look at this. I'd probably need to fix this to test oAuth2.0 anyway... 😄 of course if are not already solved it.

@relu91 great. I started a PR yesterday that fixed the issue from @egekorkan  but I did not look into the case reported by @fillobotto.
Is it ok for you if we merge the first part of the fix and you look into the rest?

**Comment by relu91** [comment]
Sounds perfect! 👍

**Comment by danielpeintner** [comment]
I merged https://github.com/eclipse/thingweb.node-wot/pull/196 which fixes the first part of this issue reported by @egekorkan.

@relu91 feel free to go ahead with your planned updates. Thanks!

**Comment by relu91** [comment]
Closing, PR #203 solved the issue.
