### ISSUE TITLE
Install & run netconf/opcua cli examples

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#182]
We are about to clean-up the examples and to add appropriate documentation.

Looking at 
`examples\servients\netconf-cli` OR
`examples\servients\opcua-cli`

I failed to even install the cli.

For example running
`npm install `
in folder` examples\servients\netconf-cli` fails with the following message.

```
npm WARN notsup Unsupported engine for link@0.1.5: wanted: {"node":"> 0.4.x < 0.9.0"} (current: {"node":"10.17.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: link@0.1.5

npm WARN notsup Unsupported engine for link@0.1.5: wanted: {"node":"> 0.4.x < 0.9.0"} (current: {"node":"10.17.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: link@0.1.5

npm WARN notsup Unsupported engine for link@0.1.5: wanted: {"node":"> 0.4.x < 0.9.0"} (current: {"node":"10.17.0","npm":"6.13.7"})
npm WARN notsup Not compatible with your version of node/npm: link@0.1.5
```

What is the correct way of installing and running?
Shall we add documentation?

@lukesmolo may I ask you to provide feedback. Thanks!

**Comment by lukesmolo** [comment]
It sounds quite strange, I actually used them till the last PR. Let me check.

**Comment by lukesmolo** [comment]
Regarding the instructions, for installing the cli:
`$ npm install`
`$ npm run build`

The `npm install` command actually uses `npm link` in order to link the local packages of _node-wot_ installed globally through `sudo npm run link` as described in the Installation guide in the README.

I do not have your warnings, they could depend on (maybe) the node version. I am currently using the 13.6.0. Anyway, the problem is about `npm link` and it could be easily solved if we avoid to use it. But for the moment we need to link the bindings from the local installation of _node-wot,_ since the new netconf and opcua bindings are still not published on the _npm registry_.

**Comment by danielpeintner** [comment]
> The npm install command actually uses npm link in order to link the local packages of node-wot installed globally through sudo npm run link as described in the Installation guide in the README.

Ahh, I see that might be the problem.

Let me check next week but think it is *safer* NOT to use npm link...

> But for the moment we need to link the bindings from the local installation of node-wot, since the new netconf and opcua bindings are still not published on the npm registry.

We could publish a snapshot soon and get rid of npm link.
 @lukesmolo What do you think?

**Comment by lukesmolo** [comment]
That would be perfect. Please let me know as soon as it has been published, so I can adjust the dependencies properly.

**Comment by danielpeintner** [comment]
snapshot versions have been pushed on NPM
https://www.npmjs.com/package/@node-wot/binding-netconf
https://www.npmjs.com/package/@node-wot/binding-opcua

**Comment by lukesmolo** [comment]
Ok, it should be fixed by this [PR](https://github.com/eclipse/thingweb.node-wot/pull/184).

**Comment by danielpeintner** [comment]
Thanks @lukesmolo. Building works!

I did give it a try and I would like to add a README.md so that everyone knows what he/she can do like the following (any improvements are welcome):


======
## Installing and building the CLI 
```
$ npm install
$ npm run build
```

## Running script
e.g.,
```
$  node dist\netconf-cli.js ..\..\..\examples\scripts\counter.js
$ node dist\opcua-cli.js ..\..\..\examples\scripts\counter.js
```
======


Everything seems to work first. The counter example creates statement
`counter ready`

However the server stops working right after the statement as IF it shuts down. Is this an issue on Windows or what can people do to keep the service up?
Is it client only?

**Comment by lukesmolo** [comment]
Yes, it is meant to be only client side. I already wrote some instructions to run the example [here](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-opcua#optional-opc-ua-server-simulator). Maybe we can re-use them. Please let me know if you need something more.

**Comment by danielpeintner** [comment]
Thanks, I will link the instructions and the additional information...

https://github.com/eclipse/thingweb.node-wot/commit/8c35fd1664d710ab173e18beba9474e1a2be1d60
