### ISSUE TITLE
[Question] Do we need wot-servient command/shortcut

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#183]
The commands `wot-servient` (with additional link) and `node packages\cli\dist\cli.js` are interchangeable.

In recent issues and discussions having 2 possibilities to achieve the same caused some issues.

I wonder whether we actually need `wot-servient`.

Cons
* Confuses people (stick to *one* possibility)
* requires additional link step (with Windows issues)
* makes README.md a lot more verbose and unreadable

Pros
* it is *shorter*
* ??else??

Hence, my personal take is that I would like to remove any mentioning of wot-servient in README.md. If someone still wants to use it it s fine but I think it makes our lifes a lot easier without...

Any opinions?

@sebastiankb @egekorkan @wiresio @h0ru5 @mkovatsc

**Comment by danielpeintner** [comment]
@relu91 @jenlincode others?

**Comment by relu91** [comment]
I'd vote for leaving it. Using command aliases is a common way to use packages in node. For example, mocha is always used through its alias. Taking from a user perspective, he should never use `node node_packages/@node-wot/cli/dist/dist/cli.js`.  Just my two cents.

**Comment by wiresio** [comment]
Would also leave both, although I'm only using cli.js.

**Comment by egekorkan** [comment]
I would also vote for leaving the wot-servient.

Similar to @relu91, I would also say that cli.js should never be used directly and be used only through the alias.

The advantage of wot-servient is that it is shorter but also that the path to cli.js is very cryptic and very unfriendly for a beginner. I would remove the cli.js information from the README.md and move it to a section like FAQ so that it wouldn't confuse people and in a way recommend everyone to use the alias.

Maybe an explainer on what wot-servient does would be good so that people can make their choices.

**Comment by jenlincode** [comment]
> Maybe an explainer on what wot-servient does would be good so that people can make their choices.

^^ This -- other than the syntax differences between wot-serient and using cli.js, it would be good to get a clear description on the differences so people can make the right choice for their set up needs.

**Comment by danielpeintner** [comment]
> Similar to @relu91, I would also say that cli.js should never be used directly and be used only through the alias.

Mhh, I think this is a rather strong statement. I tend to rather not make such statements due to 
* at least on Windows it causes issues (at least on my machine. not sure about others?)
* it requires an additional step
* it makes it difficult if one explores with different branches/versions on the same machine

**Comment by egekorkan** [comment]
I do agree that it is a strong statement :) Regarding its negative effects:
- Windows issues: These should be then fixed and should not be a limitation
- I think the additional step is justified. Making it optional, like it is at the moment, confuses more people.
- Exploring different branches and so on is an advanced requirement that is still possible by using the cli.js. We are not expecting newcomers to have such a need. By using an FAQ section that says "I cannot/don't want to use `wot-servient` command. What should I do?" where the answer shows where it is linked to and also links on how to use node-wot as a dependency.

**Comment by relu91** [comment]
>* it requires an additional step
>* it makes it difficult if one explores with different branches/versions on the same machine

I agree with @egekorkan. As a user of node-wot (i.e. if I npm install @node-wot/cli) first I don't need additional step, because the wot-servient is already generated, second I wouldn't explore branches or more dev related stuff.

**Comment by relu91** [comment]
I think now we have a pretty stable solution and `wot-servient` works pretty well also on windows. Feel free to re-open if you feel otherwise!
