### ISSUE TITLE
[installation] Reevaluate whether Python 2.7 is necessary for node-gyp

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#188]
I think that there is some old requirements about node-gyp in the installation instructions of the main README.md

It says:

> Linux
> Meet the node-gyp requirements:
> 
> Python 2.7 (v3.x.x is not supported)

However, the node-gyp repository says that Python 3.x is supported. See [here](https://github.com/nodejs/node-gyp#installation)

**Comment by danielpeintner** [comment]
@egekorkan any update? Did you have time to look into the issue?

**Comment by egekorkan** [comment]
I sadly cannot remove Python 2 to really test it. I can however try on a new Raspberry Pi in a week. In the meantime, @relu91 could you try to change python2 to python3 in your Dockerfile PR #298 and test whether that works?

**Comment by relu91** [comment]
Tested in Docker python 3 works. I am making a PR to clean the things up.
