### ISSUE TITLE
How to use environment variables in WoT script?

### ISSUE THREAD

**Issue by philiptran** [eclipse/thingweb.node-wot#190]
Our WoT script needs to access some configuration via environment variables. When using the _process.env_ to get the environment variable, the following error is thrown:

```
const API_URL = process.env.API_URL
ReferenceError: process is not defined
```

**Comment by danielpeintner** [comment]
Question: How do you use node-wot?
* via the CLI interface (calling `wot-servient` / `node packages\cli\dist\cli.js`) OR
* via NPM package dependency (`npm install @node-wot/core` etc.)

**Comment by philiptran** [comment]
I use it via NPM package dependency and run the script using `node @node-wot/cli/dist/cli.js counter.js`. The process.env is being used in the `counter.js` script.

**Comment by danielpeintner** [comment]
> I use it via NPM package dependency and run the script using `node @node-wot/cli/dist/cli.js counter.js`. The process.env is being used in the `counter.js` script.

Mhh, this reads a bit contradictory to me.

You should either
1. use CLI without *explicit* NPM package dependency (CLI brings it own dependencies with it) and run `node packages\cli\dist\cli.js examples\scripts\counter.js`
 OR
2. Use NPM package dependency and run simply run `node sample-script.js` (e.g., [HTTP](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-http#http-protocol-binding-of-node-wot))

**Comment by relu91** [comment]
Anyway, I've just checked and it seems that environment variables are not exported to CLI scripts. I am opening an issue. https://github.com/eclipse/thingweb.node-wot/blob/b428faae483b3a8dce937a02ce8255365e8b71b3/packages/core/src/servient.ts#L104-L141

**Comment by philiptran** [comment]
Thanks to today's webex call that we have a better idea on using node-wot as npm dependency. However, we are using the CLI in an independent project without cloning the node-wot code repository. The root cause of this issue is the `process` is not exported to CLI script as @relu91 has rightly pointed out.

Attached is a sample project that demonstrates our usage:

[test-wot.zip](https://github.com/eclipse/thingweb.node-wot/files/4354645/test-wot.zip)

**Comment by relu91** [comment]
For the record, I don't know if it is the case to export the entire process object to scripts...  Are you using `process` for something else? 😀

**Comment by philiptran** [comment]
I need to use `process.env` and `process.cwd()` currently. Can you share the security concerns if the entire process object is exported to WoT scripts? I thought it is no different from initializing the Servient object directly in a nodejs application.

**Comment by relu91** [comment]
Well. with `process` you can basically do whatever you want. For example, create a new process, kill it, get info about memory, PID etc. They are all considered low-level API and I am not sure that a WoT script should be able to fiddle with that stuff. Surely, not a normal script. 

Script sandbox is still under development so I guess there is no consensus on much a script "can do". For now, I think we should play safe and just export env and cwd variables. What do you think @danielpeintner @egekorkan?

**Comment by egekorkan** [comment]
I also agree with @relu91 . If this is really needed, you should look into using node-wot as a dependency.

**Comment by philiptran** [comment]
Agree with @relu91. Thanks for the explanation.

**Comment by relu91** [comment]
Closing, related issues solved in https://github.com/eclipse/thingweb.node-wot/pull/319
