### ISSUE TITLE
Logging level 0 does not suppress logging messages

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#193]
I set the log level to 0 or error in the wot-servient.conf.json by
```json
    "servient": {
        "clientOnly":true
    },
    "log": {
        "level": 0
    },
```

and I use a consumer implementation. However, I still get log messages such as 

> Helpers found scheme 'http'
> Helpers found scheme 'http'
> Helpers found scheme 'http'
> Helpers found scheme 'http'
> Helpers found scheme 'http'
> Helpers found scheme 'http'
> Helpers found scheme 'coap'
> Helpers found scheme 'coap'
> Helpers found scheme 'coap'
> Helpers found scheme 'mqtt'
> ConsumedThing 'TemperatureController' chose cached client for 'http'
> form: [object Object]
> ConsumedThing 'TemperatureController' reading http://localhost:8080/TemperatureController/properties/temperature
> HttpClient got Form 'methodName' GET
> HttpClient applying form
> HttpClient got Form 'contentType' application/json
> HttpClient (readResource) sending GET to /TemperatureController/properties/temperature
> HttpClient received 200 from /TemperatureController/properties/temperature
> ContentSerdes deserializing from application/json

**Comment by danielpeintner** [comment]
@egekorkan while I think having support for setting log level makes perfect sense I was trying to find code dealing with the following option

```
"log": {
        "level": 0
    }
```

The only thing I found was mentioning in https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/wot-servient.conf.json.md.

Do I miss anything here? Does anyone know?
There should be something in https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/src/cli-default-servient.ts right?

**Comment by relu91** [comment]
I agree that is a very welcomed feature! However, it seems not implemented. As you pointed out the "enable log" action simply does not do anything.

https://github.com/eclipse/thingweb.node-wot/blob/b428faae483b3a8dce937a02ce8255365e8b71b3/packages/cli/src/cli-default-servient.ts#L131-L153

[Stackoverflow](https://stackoverflow.com/questions/1215392/how-to-quickly-and-conveniently-disable-all-console-log-statements-in-my-code) suggests overriding the console's methods with empty functions. I don't know if it is the best solution... but it could work for the default servient implementation.

**Comment by danielpeintner** [comment]
@fatadel may I ask you to look into that issue?

**Comment by fatadel** [comment]
@danielpeintner sure!

**Comment by fatadel** [comment]
@danielpeintner Please find out my PR for this issue - https://github.com/eclipse/thingweb.node-wot/pull/251.
