### ISSUE TITLE
Run node-wot in docker container

### ISSUE THREAD

**Issue by wiresio** [eclipse/thingweb.node-wot#197]
@hyperloris - @relu91 pointed me to: https://github.com/hyperloris/dockerfiles/blob/master/node-wot/Dockerfile which looks good to me. Would you mind submitting a PR such that we can add your code? Thanks!

**Comment by hyperloris** [comment]
No problem, I'll submit a PR as soon as possible.

**Comment by wiresio** [comment]
Great, thank you!

**Comment by wiresio** [comment]
Was merged into master via: https://github.com/eclipse/thingweb.node-wot/pull/198
