### ISSUE TITLE
Question: How to choose the binding to use on client side when thing description has several ?

### ISSUE THREAD

**Issue by franckOL** [eclipse/thingweb.node-wot#199]
For exemple i get a TD  by http request by want To interact with websocket.  Aldo i m not able To get the TD by websocket channel

**Comment by egekorkan** [comment]
This is not possible at the moment but there are discussions on it in the Scripting API task force. For now, I would suggest to etiher:
- fetch the TD and remove the  unwanted forms
- do not include other bindings than websockets

Regarding use of WS, it seems that the client side is not implemented at all. All the methods [here](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-websockets/src/ws-client.ts) do nothing

**Comment by relu91** [comment]
We are also using the workaround that @egekorkan suggested above. Are there any plans to define an algorithm for choosing one form over the other? I think is essential to start a discussion about this point. 
For starting, a simple fall back mechanisms could be implemented (thanks to @hyperloris and @lukesmolo for the nice discussion about it). 

In pseudo-code:

```
if cachedClient != null :
    return client.performAffordance(affordance)

for each form in forms:
    client = getClientForForm(form)
    result = client.performAffordance(affordance)
    if( result != error):
       cachedClient = client
       break;

return result
```

**Comment by danielpeintner** [comment]
> We are also using the workaround that @egekorkan suggested above. Are there any plans to define an algorithm for choosing one form over the other?

The scripting API will shortly provide an option which can be passed along with each interaction request to specify the `formIndex` that a client wants to use.
Note: this is an optional option.

**Comment by relu91** [comment]
Nice! 🥳  but since it is optional I would like to have a default behavior like the one presented above.

**Comment by danielpeintner** [comment]
`formIndex` option is defined in the scripting API and implemented by node-wot.
