### ISSUE TITLE
[consumed-thing]observeProperty creates infinite request loop

### ISSUE THREAD

**Issue by erkann-sen** [eclipse/thingweb.node-wot#202]
I have tried observeEvent and observeProperty, both have similar logic but it creates an issue with property for http-binding. 
In events observe command creates a GET request and response returns only if a new Event occures, when event is emitted from consumed thing it also unsubscribes every device, and consumer starts observing event again by sending a GET request.
The same logic happens in properties too, but the GET request to a property responds immediately, and then consumer tries observing again and gets another immediate response. So it creates an infinite get request loop.
The code run should be like events, response should only return when value of a property is changed

**Comment by danielpeintner** [comment]
@erkann-sen is this issue still present?

Looking at the code in https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts I do not really see any difference between  `observeProperty` and `subscribeEvent` ?

**Comment by erkann-sen** [comment]
@danielpeintner, @egekorkan tried with and without the changes in "issue-230" and found out an interesting issue, issue still exist but with a catch

The infinite loop exist only if a property does not have observable field set when creating (in other words if "observable": false)
it still allows calling observeProperty function, it does not give an error (it can say this property is not observable), it returns the current value of the property and subscribe the property again.

**Comment by danielpeintner** [comment]
Mhh, Issue-230 is not going to solve it (@egekorkan  linked it but it handles another problem).

May I ask you to try the PR https://github.com/eclipse/thingweb.node-wot/pull/233. I believe this allows to properly unsubscribe in HTTP.

@erkann-sen What I still don't understand is your comment about the difference between observeProperty and events...

**Comment by erkann-sen** [comment]
I tried it 233 too, still no difference.
Sorry for any misunderstanding, let me explain things from beginning with the new findings.

If observeProperty called for a property which has the field `"observable": true` it sends a get request to `XXX/properties/NameOfProperty/observable`, which returns only if value is changed. After data is sent, it will send another Get request to same address to follow other updates.

If observeProperty called for a property which does not have the field `"observable": true` it sends a get request to `XXX/properties/NameOfProperty`, which returns directly the value of the property. After data is sent, it will send another Get request to same address, which will return again and this loop will run forever.

my comment about the difference between observeProperty and events was about the second possibility (observing non observable property), which returns directly the value not wait for a change. 

Possible solution is, return error if property is not observable.

**Comment by danielpeintner** [comment]
I see now. The issue is specific to HTTP since we do long polling (asking GET over and over again).

> After data is sent, it will send another Get request to same address, which will return again and this loop will run forever.

I think the issue is in `getClientFor(...)`. The following line should *not* return a matching client.
https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L332

I believe purely looking at the `observable` flag is not sufficient. According to the [TD](https://w3c.github.io/wot-thing-description/#propertyaffordance) it is only an optional hint. An opinion?

**Comment by erkann-sen** [comment]
I guess your suggestion about `getClientFor(...)` makes more sense.
But if it will be the case, it is better to change the following message to be more precise like:
 `reject(new Error(`ConsumedThing '${this.title}' did not get suitable **"observerProperty"** client for ${form.href}`));` 

At the end we need to check the `href` for `observeProperty`, so the `observable` flag is insufficient and pointless. You are right

**Comment by danielpeintner** [comment]
I believe there are lots of consequences and complexity that comes with it...

The idea is to be able to observe a property only IF `op: "observeproperty"` exits.
On the other hand this also means that if a someone calls readAllProperties it should also just read the properties that have `"readproperty"` in `op`  it et cetera... however at that point neither protocol etc is clear.

Moreover, this means that `getClientFor()` may also return `null` for `form` given that the schema has been found but the op field does not match.

I started a PR https://github.com/eclipse/thingweb.node-wot/pull/234 but I am not sure about the consequences....

**Comment by danielpeintner** [comment]
@erkann-sen May I ask you to take a look at PR https://github.com/eclipse/thingweb.node-wot/pull/234

I believe this PR fixes your issue. Moreover, it actually checks properly for the *right* op value.
e.g., it is possible that a value is observable but not readable et cetera.
