### ISSUE TITLE
[examples/couter.ts] Incorrect uriVariables handling

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#205]
In the counter thing example the actions increment and decrement support uriVariables (i.e. step variable in this case). However, it is being handled incorrectly. This is the piece of code:

```TypeScript
if(options && typeof options === 'object' && 'uriVariables' in options) {
	if('step' in options['uriVariables'] && options['uriVariables'] instanceof Array) {
		step = options['uriVariables']['step'];
	}
}
```

The problem is that options['uriVariables'] is not an array, but an object.

**Comment by egekorkan** [comment]
While you are working on this example, I would suggest to remove this uriVariables or move it to another interaction or example, since I don't think that this should be encouraged, especially for a POST request pattern in the actions where there is already the dedicated input field. They make more sense for property affordances

**Comment by fatadel** [comment]
I would ask for advice @sebastiankb to help on deciding how we should proceed.

**Comment by danielpeintner** [comment]
@fatadel good catch!

https://github.com/eclipse/thingweb.node-wot/commit/191bb6be9bb26fe117d70256e3f7f2aea32499a6 should fix the problem.

**Comment by sebastiankb** [comment]
@egekorkan 
>While you are working on this example, I would suggest to remove this uriVariables or move it to another interaction or example, since I don't think that this should be encouraged, especially for a POST request pattern in the actions where there is already the dedicated input field. They make more sense for property affordances

The idea is to have a tutorial that explains all variations what can be done with properties, actions and events. This is kind of missing in node-wot to see the full features that can be implementd. E.g., the counter examples shows only how to use actions with uriVariables. There are no explanations somewhere how to use with input...

**Comment by fatadel** [comment]
@danielpeintner Works great now, thank you!
Please take a look at issue #206 as well.
