### ISSUE TITLE
WSL Install Issues

### ISSUE THREAD

**Issue by joshco** [eclipse/thingweb.node-wot#207]
Hi,
I'm running Windows 10 with Windows Services for Linux (WSL) v1.
I couldn't make the npm run build step work until I upgraded from node 10 to node 12.
I'm working from current master (commit 191bb6be9bb2)

With node 10 (and 11), I got the error below.
I tried directly installing lerna, bootstrap, and node-gyp (for the dependencies).  I also tried moving to a directory in the native WSL filesystem (rather than my linked windows home directory) since the symlinking of node often confuses windows.   None of these worked.

Is anyone else using WSL?

The error:
````
lerna ERR! npm install exited 1 in '@node-wot/binding-netconf'
lerna ERR! npm install stderr:
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer  supported. Please update to mkdirp 1.x. (Note that the API surface has changed to  use Promises in 1.x.)
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-17T04_02_46_029Z-debug.log

lerna ERR! npm install exited 1 in '@node-wot/binding-netconf'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit  immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ bootstrap: `lerna bootstrap --no-ci`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional  logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-17T04_02_47_131Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prebuild: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional  logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-04-17T04_02_47_358Z-debug.log
ubuntu@wsl:~/unx/thingweb.node-wot$ npm install -g lerna
````

**Comment by egekorkan** [comment]
@lukesmolo Could you have a look?

**Comment by fatadel** [comment]
I am also using WSL 1 on Windows 10. But I initially installed the latest LTS version of Node.js, which is v12.16.1 as of now. Everything worked (and works) like a charm.

**Comment by lukesmolo** [comment]
Unfortunately I do not own Windows. But from what I see, it seems a problem related to the version of node. Maybe @joshco you can try as suggested by @fatadel .

**Comment by joshco** [comment]
Thanks.  I'm actually OK. I'm using node 13 at the moment. I just figured I'd report it since the docs say it should work with node 10.

**Comment by fatadel** [comment]
Apparently, we need to change the docs.

**Comment by relu91** [comment]
Since LTS is now v12.13.0 I guess we could try to upgrade, what do you think @danielpeintner?

**Comment by danielpeintner** [comment]
> Since LTS is now v12.13.0 I guess we could try to upgrade, what do you think @danielpeintner?

I am fine either way. To be on the *safe* side I still use node v10 locally and it works fine on my side (did not try WSL though).

The [Travis](https://travis-ci.org/eclipse/thingweb.node-wot) builds run on node10 and latest also with success. Having said that I think this might be an issue of Windows Services for Linux (WSL).

Personally I would stick a bit longer to v10. 
@sebastiankb @egekorkan any opinion?

**Comment by danielpeintner** [comment]
FYI: 10.x is still "Active LTS" (see https://en.wikipedia.org/wiki/Node.js#Releases)

**Comment by egekorkan** [comment]
I use node 12.x and works without any issues for me on Arch Linux.

**Comment by joshco** [comment]
The updates to the readme have been merged.  Closing this
