### ISSUE TITLE
Updating API.md file

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#209]
The API.md file that is in the root directory is not up to date with the latest API. (https://github.com/eclipse/thingweb.node-wot/blob/master/API.md).

It also does not show some features like adding security, uriVariables.

**Comment by danielpeintner** [comment]
@egekorkan do you plan to take a look and provide a PR or shall I try to look into?

**Comment by egekorkan** [comment]
I might be able to do that. @sebastiankb mentioned that @fatadel might also look into it?

**Comment by fatadel** [comment]
I think we can remove this file now since we have the smart coffee machine tutorial which covers the API usage. What do others think?

**Comment by egekorkan** [comment]
This should definitely not be removed. Coffee machine is an example tutorial, this is (hopefully) proper library documentation that should be similar to Scripting API.

**Comment by fatadel** [comment]
@egekorkan Okay, I understood 👌

**Comment by sebastiankb** [comment]
@egekorkan told me that @ajs124 is taking care of it
