### ISSUE TITLE
[consumed-thing] valueToContent function sheme differences

### ISSUE THREAD

**Issue by erkann-sen** [eclipse/thingweb.node-wot#216]
In writeProperty function the content conversion is created by `content_serdes_1.default.valueToContent(value, tp, form.contentType);` where tp is the property object itself, which is created as `var tp = _this.properties[propertyName];` , 

but in invokeAction function the content conversion is created by 
`content_serdes_1.default.valueToContent(parameter, _this, form.contentType);` where _this is the thing description itself but it should be ta, which is created as `var ta = _this.actions[actionName];`

**Comment by danielpeintner** [comment]
Not exactly sure which code you are referring to. It looks like trancompiled JavaScript code.

w.r.t. the action you are pointing to it uses `ta` in TypeScript.
see https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L278

Do you mean something else?

**Comment by erkann-sen** [comment]
Sorry Daniel,
I was using version 0.7.0 snapshot 3 and you are right it was fixed in between snapshot 3 to 6
