### ISSUE TITLE
Issue of specify DataSchema of ThingAction input 

### ISSUE THREAD

**Issue by hidetak** [eclipse/thingweb.node-wot#217]
Thank you for developing this software.

I'm trying to develop a `binding` based on this software.  
I found a little issue during development.

I think it's need to specify DataSchema of ThingAction input at [consumed-thing.ts](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L278) file, like follows:
```
                if (parameter !== undefined) {
                    input = ContentManager.valueToContent(parameter, <any>ta.input, form.contentType);
                }
```

Thank you,

**Comment by danielpeintner** [comment]
I think you are right. Thank you for pointing us to the issue.

**Comment by danielpeintner** [comment]
resolved by PR https://github.com/eclipse/thingweb.node-wot/pull/221

**Comment by hidetak** [comment]
Thank you for fix this! (^^)

**Comment by danielpeintner** [comment]
proper fix by https://github.com/eclipse/thingweb.node-wot/pull/263 ?
