### ISSUE TITLE
Options are not parsed in consumed thing

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#218]
In `packages/core/src/consumed-thing.ts` neither of consumed Thing methods (e.g. `readProperty`, `writeProperty` etc.) are utilizing passed options. All methods have this parameter in their signature, but none of them uses it. So it's just ignored. And it makes impossible of using uriVariables with properties. Talking about actions and the `invokeAction` method, it utilizes the uriVariables in a wrong way. It parses uriVariables as `parameter` but should parse it as `options`, since `options` are uriVariables, and `parameter` is a payload of a request.

**Comment by danielpeintner** [comment]
@fatadel please take a look at PR https://github.com/eclipse/thingweb.node-wot/pull/222 and let me know whether you think the fix is OK.

**Comment by fatadel** [comment]
Thank you, @danielpeintner. I will check out the branch now and will test it out with my examples.

**Comment by fatadel** [comment]
It seems to work as intended now. The problem is resolved, thank you! @danielpeintner
