### ISSUE TITLE
[cli] wot-servient.conf seems to be ignored

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#223]
The `wot-servient.conf.json` in the examples seems to be ignored. I remove the `http` object but still an HTTP Thing is generated. And MQTT forms are not generated...

This used to work 1 month ago so something has broken it I think?

**Comment by danielpeintner** [comment]
I looked at https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/src/cli.ts#L40-L42 and it still seems to pick up the the default `"wot-servient.conf.json"` if no other file is provided.

Do you have an example that is not working?

**Comment by egekorkan** [comment]
It seems that this was a problem in my system that got fixed after reinstalling :blush:
