### ISSUE TITLE
[binding-mqtt] MQTT message payload could not be accessed in the ActionHandler

### ISSUE THREAD

**Issue by MarcusWolfSchmidt** [eclipse/thingweb.node-wot#224]
### Description

I am exposing a Thing via MQTT and when I try to access the payload of an MQTT message in setActionHandler, I get an error. More details to reproduce it are posted below, but it is likely due to the mqtt package (dependency).
I am using the binding-mqtt-0.7.0-SNAPSHOT.6 and one of its dependancies is the mqtt package version 3.0.0. (As it is in GitHub.) 
Another device in my network publishes a message periodically on the relevant topic (setNumber1) and as long as I don't want to access the payload of the MQTT message everything works as intended in setActionHandler.

### To reproduce

My code:

```js
Servient = require("@node-wot/core").Servient
MqttBrokerServer = require("@node-wot/binding-mqtt").MqttBrokerServer

let servient = new Servient();
servient.addServer(new MqttBrokerServer("mqtt://192.168.178.38")); //change for another broker, like test.mosquitto.org

servient.start().then((WoT) => {

    WoT.produce({
        "@context": "https://www.w3.org/2019/wot/td/v1",
        "id": "de.tum:ei:esi",
        "title": "example_td",
        "securityDefinitions": { "nosec_sc": {"scheme": "nosec"}
        },
        "security": ["nosec_sc"],
        "actions":{
            "setNumber1":{
                "input":{
                    "type": "integer"
                }
            }
        }
    })
    .then((thing) => {
    console.log("Produced " + thing.getThingDescription().title);

    // set action handlers
    thing.setActionHandler("setNumber1", (msg) => {
        
         return new Promise ((resolve, reject) => {
             console.log(msg);
             resolve();
         });
    });

    // expose the thing
    thing.expose().then(() => {
        console.info(thing.getThingDescription().title + " ready");
    }).catch((e) => {
        console.log(e);
    });
});
```

I am unable to access the MQTT message payload over msg and console.log(msg) returns :
```bash
function () { … }

    [[FunctionLocation]]:internal#location
    [[Scopes]]:Scopes[4]
    arguments:TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    caller:TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    length:0
    name:""
    prototype:Object {constructor: }
    __proto__:function () { … }
```
### Hint

A looked at the mqtt-broker-server.ts file and found out that in line 176 a problem occurs with packet.properties.
When looking up mqtt in npm I saw that there were some breaking changes in v2.0.0.

**Comment by danielpeintner** [comment]
Mhh, not sure now. Is this an issue in the mqtt library (version "3.0.0") we are using?
Shall we report this back to the developers there?

@egekorkan may I ask you to look into that issue...

**Comment by ajs124** [comment]
I'm working on this [here](https://github.com/ajs124/thingweb.node-wot/tree/fix/mqtt-binding-payload), but I haven't done enough testing yet to be confident in the correctness of the code I have there, to open a pull request. This is just a heads up, if anyone else is also looking into it.
