### ISSUE TITLE
[proposal] slightly improve logs

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#229]
In #186 I tried to use a simple patter for logging. I think it might be useful if it is adopted for the whole library. it does not require external libraries but it gives slightly better control over what is logged and what is not. 

The pattern is: `console.debug("[package-name]", "log message)`. Following this rather simple pattern can provide two positive outcomes:
1. Quickly identify where the log message is generated 
2. Allows filtering procedures to just shut down package level messages. 

Considering the second point, an example could be this js script:
```javascript
// turn off messages from core package
const debug = console.debug
console.debug = (package,...args) => {
 if(package !== "[core]"){
    debug(package,...args)
 }
}
```

In general, I would prefer to use just `debug`, `warn`, and `error` leaving `info` and `log` reserved to applications that use node-wot. 

Notice that with this suggestion this statement from README remains valid: 

> We used to have a node-wot-logger package to allow fine-grained logging (by means of Winston). It turned out though that depending on the actual use-case other logging libraries might be better suited. Hence we do not want to prescribe which logging library to use. Having said that, we use console statements which can be easily overriden to use the prefered logging library if needed (see here).

**Comment by danielpeintner** [comment]
I like the suggested approach. We would need to

* document that approach in the README (as *best* practice)
* walk over the code and update accordingly (i.e., adding "[package]" and replace any info/log level messages with debug)

**Comment by sebastiankb** [comment]
issue is kind of related to each other #193

**Comment by relu91** [comment]
@sebastiankb @danielpeintner I am working on this.

**Comment by relu91** [comment]
I think we can close this issue after #250
