### ISSUE TITLE
Flag "writeable" for properties seems to be broken

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#23]
How to reproduce:
Run counter example `node packages\cli\dist\cli.js examples\scripts\counter.js` and retrieve the TD which reports a property `count` with `"writeable": true`.

The property is not writable and reports 500 error on PUT.

**Comment by mkovatsc** [comment]
It should be `writable` without e.
Will check why there is writeable in the TD.

**Comment by danielpeintner** [comment]
The only mentioning of `writaeble` is here:  https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js#L36

I fixed this minor issue right away in  https://github.com/eclipse/thingweb.node-wot/commit/8125173022a32afe81390892e5dabd7477062e36
