### ISSUE TITLE
Proposal for a new td-generator.ts implementation in @node-wot/core

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/thingweb.node-wot#24]
To face the issue that was mention in PR https://github.com/eclipse/thingweb.node-wot/pull/9 (getAddress()) we should think about to make the td-generator.ts more generic for any protocol bindings. 

So far, if there is a new protocol binding such as MQTT with remote broker address assignment or specific protocol handling such as http long poll some if statements have to be added within generateTD() method. This should be avoided in the future and TD generator should be more generic for any new bindings.

Proposal is to provide a getForms() method in the protocol-interfaces.ts that have to be implemented by the protocol binding packages. The getForms() returns a array with all communication metadata that are relevant for the underlying protocol binding.

What do you think?

**Comment by danielpeintner** [comment]
I agree.

The core `module` should not contain any information (or knowledge) from a given binding to allow for future extensions (bindings) we don't know about.

**Comment by danielpeintner** [comment]
@sebastiankb  is this issue still valid?

I did not find any references from core module to binding modules?
Did I overlook any dependency?

If not I propose closing.

**Comment by danielpeintner** [comment]
I believe this is obsolete
