### ISSUE TITLE
[suggestion] Introduce a pull request template

### ISSUE THREAD

**Issue by ajs124** [eclipse/thingweb.node-wot#241]
Contributing to this project can be slightly confusing.

You actually have some [really good documentation](https://github.com/eclipse/thingweb.node-wot/blob/master/CONTRIBUTING.md), which explains the whole process and without it, I'm not sure how anyone would figure all of this out, it they're not familiar with Eclipse projects already.
It's even linked under "Helpful resources" next to issues (and pull requests, I assume).

The only problem with it is that it's still relatively easy to miss/forget parts of it. Searching through closed pull-requests, I can find at least a handful where people forgot to agree to the contributor agreement or to sign off their commits and needed to be reminded.

GitHub offers a pretty nice feature, which can really help with reminding people of these things called [pull request template](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository). 
An example implementation of this, in a project which I've been contributing to, can be [found here](https://raw.githubusercontent.com/NixOS/nixpkgs/master/.github/PULL_REQUEST_TEMPLATE.md).

It could for example be a simple checklist with the most common things like:
- [ ] I agreed to the Eclipse Contributor agreement
- [ ] All of this code is mine and I'm allowed to contribute it
- [ ] I signed off my commits
- [ ] the commit author and sign off e-mail adress match with the one I agreed to the Eclipse Contributor agreement with

**Comment by egekorkan** [comment]
Just to add a little point @ajs124 mentioned to me before:
You can add comment fields in the md file of the template which are seen by the developer but are not rendered in GitHub comments :blush: It is seen also in the nixos template above
