### ISSUE TITLE
Remove codestyle scripts in package.json

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#243]
Relates to https://github.com/eclipse/thingweb.node-wot/issues/239#issuecomment-640479670

We should remove `"codestyle": "standard --pretty"` or alike in *all* package.json
e.g., https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-coap/package.json#L37

We should properly handle it with [.editorconfig](https://github.com/eclipse/thingweb.node-wot/blob/master/.editorconfig)

**Comment by danielpeintner** [comment]
@relu91 could you check PR https://github.com/eclipse/thingweb.node-wot/pull/259 ?

In a next step we can try to use VSC auto format feature and see how many diffs we see...

**Comment by relu91** [comment]
>  @relu91 could you check PR #259 ?

I've just done my review.

> In a next step we can try to use VSC auto format feature and see how many diffs we see...

Yes exactly. However, I found that `.editorconfig` is quite limited regarding the expressivity of how the code should be formatted.  I have to admit that I do not use `.editorconfig` usually, so maybe I have to understand it a little bit better. `eslint` seems more advanced.

**Comment by relu91** [comment]
closing we now have a new fancy code-style system
