### ISSUE TITLE
[proposal] introduce run mocha tests vscode task

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#245]
I usually debug tests using the embedded `vscode` debugger. Having a preconfigured `vscode` task would help newcomers to run tests and improve the workflow for debugging (i.e. no need to launch mocha from the command line and then attach the debugger to the node process).

We could provide two tasks. One that execs all the available tests in the repository with `lerna test` (useful before committing to quickly verify that something didn't break). The other to run a single Mocha test file, usually the currently open tab. 

What do you think?

**Comment by egekorkan** [comment]
Good workflow idea, +1 from my side :)

**Comment by relu91** [comment]
As usual, things get harder when you try to implement them. It turns out that the launch mocha test target requires a reference to the actual mocha executable:
```javascript
{
            "args": [
                "-u",
                "tdd",
                "--timeout",
                "999999",
                "--colors",
                "${workspaceFolder}/test"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha", //HERE
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "node"
        }
```
Unfortunately, it is quite tricky to write down a general path for each subpackage. I see three solutions: 
1. Add mocha as a dev dependency of the root project (not ideal in my opinion)
2. Configure a vs code workspace. This would allow the definition of .vscode/launch.json files at the package level. However, the workspace is not opened automatically, you have to specify that you want to open a workspace instead of a folder from the file menu. This means that we need to document this workflow in the readme, which might not ideal. 
3. Manually configure a launch target for every single package at the root level. This has the advantage of not requiring additional documentation about how the project is structured. 

Finally, also for running `lerna test` there are some problems. In particular, vscode cannot run a task without a debugger attached (See [here](https://github.com/microsoft/vscode-cpptools/issues/1201)). This means that it tries to attach to every single learna call (even the build tasks). In the end, the process is longer than usual and it is not even debuggable because it seems that it cannot attach the breaking points to the right files. 

It seems that we are stuck with the current workflow, aside maybe for the little improvement described in the point 3.

**Comment by danielpeintner** [comment]
> It seems that we are stuck with the current workflow, aside maybe for the little improvement described in the point 3.

I think "solution 3" is at least *some* improvement!

**Comment by relu91** [comment]
@danielpeintner @sebastiankb I am working on this.

> I think "solution 3" is at least some improvement!

Ok let see how it goes.
