### ISSUE TITLE
[cli] cli-default-servient assumes that there is always a log level

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#254]
Even though the log level features added by @fatadel  have been tested, we have overlooked something. In the config file, the log level was optional (as far as I remember) but now in https://github.com/eclipse/thingweb.node-wot/blob/6b207b0029654055f170f83dc94443cc8c94f956/packages/cli/src/cli-default-servient.ts#L69 the `log.level` is trying to be read. So if the config file does not have it, an error like the following is thrown:
`WoT-Servient config file error: Cannot read property 'level' of undefined`

As mentioned at https://github.com/eclipse/thingweb.node-wot/issues/177 , I think we really need a JSON Schema (and TS definitions) for the configuration file that validates it before being used in the runtime. This would also serve as a guide for those who are writing a configuration file.

**Comment by danielpeintner** [comment]
@fatadel may I ask you to provide a patch that sets a default logging level if it hasn't been set before.

> As mentioned at #177 , I think we really need a JSON Schema (and TS definitions) for the configuration file that validates it before being used in the runtime. This would also serve as a guide for those who are writing a configuration file.

Agree.

**Comment by relu91** [comment]
+1 for validation. It would be cool if we validate AND fill the default values altogether so that we do not need to check every time if the value is null/undefined.

**Comment by egekorkan** [comment]
> fill the default values altogether so that we do not need to check every time if the value is null/undefined.

Good idea. AJV supports this (https://ajv.js.org/#assigning-defaults)

**Comment by fatadel** [comment]
Thanks for spotting, @egekorkan!
Here is the PR - https://github.com/eclipse/thingweb.node-wot/pull/257.

**Comment by danielpeintner** [comment]
I think a general solution to fill *all* default values is valuable...

**Comment by danielpeintner** [comment]
I noticed that with the latest logging changes it is difficult for users to *spot* some important information like which server is started and on which port.

E.g.,:
* default log level is "info"
* important information like `console.debug("[binding-http]",`HttpServer starting on ${(this.address !== undefined ? this.address + ' ' : '')}port ${this.port}`);` is logging level "debug"

I think by default you should see the address of the servers and the port. Any opinion?
@relu91 @egekorkan @fatadel 

At the moment what you see is the following. Is this enough?

```
[cli] WoT-Servient using defaults as 'wot-servient.conf.json' does not exist
{ servient: { clientOnly: false, scriptAction: false },
  http: { port: 8080, selfSigned: false },
  coap: { port: 5683 },
  log: { level: 'info' } }
```

**Comment by relu91** [comment]
Moving `console.debug("[binding-http]",HttpServer starting on ${(this.address !== undefined ? this.address + ' ' : '')}port ${this.port});` to info seems reasonable to me.

**Comment by danielpeintner** [comment]
> Moving `console.debug("[binding-http]",HttpServer starting on ${(this.address !== undefined ? this.address + ' ' : '')}port ${this.port});` to info seems reasonable to me.

The same might make sense for CoAP and others server parts also.... I guess.

The downside I am seeing is that we initially said that all logs from node-wot should *not* use "info" level... this would break this assumption.

**Comment by relu91** [comment]
> The downside I am seeing is that we initially said that all logs from node-wot should not use "info" level... this would break this assumption.

Yes, I know... but during the PR I understood that we might be a little bit easier on that statement. I like: please use avoid to use `info` level whenever is possible 😄 .

**Comment by danielpeintner** [comment]
@relu91 see https://github.com/eclipse/thingweb.node-wot/pull/264
Please approve IF ok.

Note1: we could also add every expose log to info but I think it is good for now without it since users can load the base url and see the available things anyway

Note2: we could also log on info whether the server was stopped (did not do so)

Note3: I was not sure what to do with MQTT

**Comment by relu91** [comment]
Just approved 👍 

>Note1: we could also add every expose log to info but I think it is good for now without it since users can load the base url and see the available things anyway

One line saying `thingid` exposed should not be so bad, however, I'll wait if we really find that we *really* need this information logged in the default level.

> Note2: we could also log on info whether the server was stopped (did not do so)

To be symmetrical it makes sense. @egekorkan what's your opinion about this?

> Note3: I was not sure what to do with MQTT

I think we could log at `info` level [this line](https://github.com/eclipse/thingweb.node-wot/blob/479bfdf02f4bac9a7068b5784cc842e3e22fb34b/packages/binding-mqtt/src/mqtt-broker-server.ts#L302) and live the others to debug. (also here @egekorkan I'd like to hear your input).

**Comment by egekorkan** [comment]
> One line saying thingid exposed should not be so bad, however, I'll wait if we really find that we really need this information logged in the default level.

I also like this, since if a long TD is logged, it is annoying to get its id, title or link.

>To be symmetrical it makes sense. @egekorkan what's your opinion about this?

I also agree :)

> I think we could log at info level this line and live the others to debug. (also here @egekorkan I'd like to hear your input).

That line is indeed where it should be I think :)

**Comment by fatadel** [comment]
@danielpeintner 
Could you please restate what's left with this issue?

**Comment by danielpeintner** [comment]
> @danielpeintner
> Could you please restate what's left with this issue?

I think it would be good do have a way to set defaults to all possible values like Ege mentioned in https://github.com/eclipse/thingweb.node-wot/issues/254#issuecomment-647468528

So not only the log level but other configs also. Do you know what I mean? Does it make sense?

**Comment by danielpeintner** [comment]
> > To be symmetrical it makes sense. @egekorkan what's your opinion about this?
> 
> I also agree :)
> 
> > I think we could log at info level this line and live the others to debug. (also here @egekorkan I'd like to hear your input).
> 
> That line is indeed where it should be I think :)

I provided PR https://github.com/eclipse/thingweb.node-wot/pull/266.
Anything missing or ok as is?
Please take a look @relu91 and @egekorkan

**Comment by egekorkan** [comment]
I think it is OK as it is :)

**Comment by fatadel** [comment]
@danielpeintner Yeah, I think I got you. Thanks for clarification.
I will provide a PR in the nearest time.

**Comment by fatadel** [comment]
@danielpeintner Please check out my PR - https://github.com/eclipse/thingweb.node-wot/pull/273.
