### ISSUE TITLE
[binding-mqtt] MQTT Topics should not start with `/`

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#255]
As pointed out by @benjaminbraun , the MQTT topics that node-wot subscribes and publishes to always start with a forwards slash, i.e. `/`. However, this is something that should never be done according to best practices. See more [here](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/).

This also shows something we cannot easily describe with a TD produced by node-wot since the base URI that can be used to identify the broker is not produced and all hrefs are absolute. Thus, a Consumer cannot tell if the topics starts with a `/` or not. For example, `"mqtt://test.mosquitto.org/example_td/actions/setNumber1"` can correspond to:
- Broker: `"mqtt://test.mosquitto.org"` and topic `"example_td/actions/setNumber1"` OR
- Broker: `"mqtt://test.mosquitto.org"` and topic `"/example_td/actions/setNumber1"`

Related issue in W3C WoT TD repo: https://github.com/w3c/wot-thing-description/issues/878

**Comment by JKRhb** [comment]
I just ran into the same issue using `node-red-contrib-web-of-things` – there is always a `/` added to topics as a prefix making it, unfortunately, impossible to subscribe or publish to topics that don't start with one. 

Have there been any discussions on this in the meantime? Maybe it could be a workaround to simply remove the leading `/` for now in all cases? (And maybe add a specific vocabulary term to the binding templates if a leading `/ ` should be used?)

**Comment by egekorkan** [comment]
I think that the `/` should be simply removed and for the consumption of MQTT TDs, a `base` with an MQTT should be present since that could be the only way of doing it while having `href` in forms. 

Another possibility would be to say that the `href` only defines the location of the broker and an additional `mqv:topic` clearly states the topic and can have `/` or not. Also, important to note that MQTT does not have a URI scheme that is standardized.

**Comment by JKRhb** [comment]
Sounds good! I guess the simple `/` removal would be an easy fix for `node-wot` while the addition of `mqv:topic` (with the assumption that `href` refers to a broker) could be a good medium-term solution?

It is probably not ideal, however, that the broker address has to be stated then in every `form` if the broker is defined using `href` and not `base` but I suppose the current TD structure does not allow for a different solution.

**Comment by sebastiankb** [comment]
I think, a clear URL guideline with MQTT broker and topic information should be present at the (future) MQTT binding document. Maybe we should also think about a RFC.

**Comment by JKRhb** [comment]
I just opened #398 as a very simple fix for this problem.

**Comment by danielpeintner** [comment]
fixed by https://github.com/eclipse/thingweb.node-wot/pull/398
