### ISSUE TITLE
[core] counter example crashes when observing and reset action invoked

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#256]
There is a behavior that I am not able to understand where it really comes from but here is the sequence of interactions I make to the counter example:
1. I increment the count property using the increment action and URI Variables with step of 100, i.e. `curl --location --request POST 'http://localhost:8080/counter/actions/increment?step=100'`
2. I invoke the reset action, i.e. `curl --location --request POST 'http://localhost:8080/counter/actions/reset'`

This works as expected, the count property is set back to 0. Then I observe the count property in the beginning, i.e. `curl --location --request GET 'http://localhost:8080/counter/properties/count/observable'`. Once I repeat the two previous requests, the reset causes the servient to crash with the following log:
```sh
HttpServer on port 8080 received 'POST /counter/actions/reset' from [::1]:54194
HttpServer on port 8080 received no Content-Type from [::1]:54194
ExposedThing 'counter' calls registered handler for Action 'reset'
Resetting count
ExposedThing 'counter' directly sets Property 'count' to value '0'
ExposedThing 'counter' directly sets Property 'lastChange' to value '2020-06-22T17:51:33.692Z'
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:643:15)
    at ServerResponse.end (_http_outgoing.js:763:7)
    at SafeSubscriber._next (/home/eko/git/thingweb.node-wot/packages/binding-http/dist/http-server.js:441:45)
    at SafeSubscriber.__tryOrUnsub (/home/eko/git/thingweb.node-wot/packages/core/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.next (/home/eko/git/thingweb.node-wot/packages/core/node_modules/rxjs/Subscriber.js:189:22)
    at Subscriber._next (/home/eko/git/thingweb.node-wot/packages/core/node_modules/rxjs/Subscriber.js:129:26)
    at Subscriber.next (/home/eko/git/thingweb.node-wot/packages/core/node_modules/rxjs/Subscriber.js:93:18)
    at Subject.next (/home/eko/git/thingweb.node-wot/packages/core/node_modules/rxjs/Subject.js:55:25)
    at /home/eko/git/thingweb.node-wot/packages/core/dist/exposed-thing.js:207:71
    at new Promise (<anonymous>)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:702:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Some notes:
- I actually use Postman but curl commands are easier to paste here
- Not invoking the increment action does not cause this bug to appear, i.e. starting the servient, start observing, invoke reset.
- It seems that the observing can happen anytime before this sequence, not necessarily just before.

**Comment by danielpeintner** [comment]
@egekorkan Do you think we can come up with a unit test for this unexpected behavior?

**Comment by egekorkan** [comment]
Do you also observe the same behavior?

**Comment by danielpeintner** [comment]
I did try to reproduce the issue with my RESTclient but failed.
Hence I was thinking having a test that shows the issue helps me and other to reproduce the issue..

**Comment by egekorkan** [comment]
I am able to reproduce the issue with the following script that is basically a modified counter-client.js:
```js
WoTHelpers.fetch("http://localhost:8080/counter").then(async (td) => {
    try {
        let thing = await WoT.consume(td);
        console.info("=== TD ===");
        console.info(td);
        console.info("==========");
        // read property #1
        let read1 = await thing.readProperty("count");
        console.info("count value is", read1);
        //comment out the next 3 lines to not observe the bug (no pun intended)
        thing.observeProperty('count', (data) => {
            console.log(data)
        });
        await thing.invokeAction("increment", undefined, {
            uriVariables: {
                'step': 100
            }
        });
        let inc1 = await thing.readProperty("count");
        console.info("after inc1 count value is", inc1);
        await thing.invokeAction("reset"); //comment out this line to not observe the bug
        let res = await thing.readProperty("count");
        console.info("count value is", res);
    }
    catch (err) {
        console.error("Script error:", err);
    }
}).catch((err) => { console.error("Fetch error:", err); });
```
@danielpeintner if you cannot reproduce the bug with this script, there has to be something wrong with my setup somehow but I am using the latest master with Node.js v14.4.0. My wot-servient.conf.json is :
```json
{
    "servient": {
        "_staticAddress": "plugfest.thingweb.io",
        "scriptDir": ".",
        "scriptAction": true
    },
    "http": {
        "port": 8080,
        "allowSelfSigned": true
    },
    "log": {
        "level": "info"
    }
}
```
I use the same conf for both server and client but run the client with the -c option

**Comment by danielpeintner** [comment]
No crash on my side.

I tried both, RESTclient and running the scripts a la `node packages\cli\dist\cli.js examples\scripts\counter.js`.

My node version is v10.17.0 and I am using the *latest* master

**Comment by egekorkan** [comment]
Cannot reproduce in another computer with node 12.16.2. Trying newer versions

**Comment by egekorkan** [comment]
Really interesting, I cannot reproduce it in my other computer that also runs Arch linux and node.js 14.4.0. I will try again tomorrow on the computer that exhibits the issue.

**Comment by danielpeintner** [comment]
I suggest to close this issue. Please reopen @egekorkan if you feel strongly about 🙃
