### ISSUE TITLE
getThingDescription calls serializeTD just to parse it again

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#271]
As mentioned in https://github.com/eclipse/thingweb.node-wot/issues/244#issuecomment-649629819 the `getThingDescription` method is calling `serializeTD` every time. For reference see the implementation body of this method:

```ts
public getThingDescription(): WoT.ThingDescription {
    return JSON.parse(TD.serializeTD(this));
}
```
Why do not just return this? if serialize is doing some transformation why do not cache the result of `serializeTD`? I feel that this method might be called a lot of times and should be as lean as possible.

**Comment by danielpeintner** [comment]
Close in favor of https://github.com/eclipse/thingweb.node-wot/issues/244
