### ISSUE TITLE
[core][consumed-thing] No error handling on getting the interaction name

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#285]
If I write a consumer but misspell an interaction name on `readProperty`, `invokeAction` etc., the error shown by node-wot is not helping to find my mistake. I get an error like `Cannot get form of undefined`. This is happening due to the lines just after `readProperty`, `invokeAction` etc. of consumed-thing.ts of the core package, i.e. for invokeaction: https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L317

I think that a try/catch should surround `let ta: TD.ThingAction = this.actions[actionName];` and the appropriate error message should be communicated to the developer.

**Comment by danielpeintner** [comment]
> I think that a try/catch should surround `let ta: TD.ThingAction = this.actions[actionName];` and the appropriate error message should be communicated to the developer.

I think the error message comes from later code...

Please have a look at PR https://github.com/eclipse/thingweb.node-wot/pull/287

**Comment by danielpeintner** [comment]
resolved by https://github.com/eclipse/thingweb.node-wot/pull/287
