### ISSUE TITLE
Status Modbus in README.md

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#286]
what is the *correct* status of Modbus binding [here](https://github.com/eclipse/thingweb.node-wot#protocol-support)

@relu91 @wiresio

**Comment by wiresio** [comment]
Although @relu91 provided a test Modbus server, I'd put client only.

**Comment by relu91** [comment]
> Although @relu91 provided a test Modbus server, I'd put client only.

Agree, PR incoming
