### ISSUE TITLE
[documentation] Dependency management in package.json

### ISSUE THREAD

**Issue by TimKam** [eclipse/thingweb.node-wot#289]
I am trying to use ``@node-wot/core`` to run an "ordinary" Node.js module, in which the dependencies are managed in a package.json file.
However, it seems that when running ``wot-servient`` the script does not pick up locally installed dependencies, but requires me to install all dependencies of my project globally.
Presumably, the solution can be to install ``@node-wot/core`` locally and invoke ``wot-servient`` locally as well.
How can this be achieved?
IMHO, it is important to document this as the standard way of working (instead of having to clone this GitHub repo as a starting point, which is a rather "hacky" workflow).

**Comment by relu91** [comment]
Just to be sure. @TimKam are you trying to use the wot-servient command on js file? (i.e. `wot-servient index.js`). And the `index.js` contains something like this:
```js
const loadsh = require('loadsh')
const other = require('package_json_dependency')
....
```

It would be awesome if you provide little your local project setup. :) Anyway, I agree with @egekorkan we need to update the readme to have a straightforward preferred way to use `node-wot`.

**Comment by TimKam** [comment]
Considering that it can be expected that most developers want to have access to local dependencies, I _think_ it makes sense to adjust the documentation as follows:

* Add the CLI as an ordinary dependency, i.e.:

```
npm install @node-wot/core @node-wot/binding-coap @node-wot/cli --save
```

* Adjust the `scripts` of your project's ``package.json`` as follows:

```
  "scripts": {
    "start": "node ./node_modules/@node-wot/cli/dist/cli.js"
    ...
  }
```

Now it works :-)

The current README gives the impression that the CLI is merely a dev tool. But if so, how do I get my dependencies managed in production?
Don't I use the CLI as well in production? If so, how do I manage my dependencies in production?

**Comment by danielpeintner** [comment]
Note: be aware that once you add a dependency to `@node-wot/cli` you pull in other packages (see [here](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/package.json#L26-L33)).
This may (or may not) be what you want.

**Comment by relu91** [comment]
Other note. I made a [tool](https://github.com/UniBO-PRISMLab/wam) that can simplify the initial project setup. @TimKam if you have time to evaluate it, it would be awesome. 

>```
>
>"scripts": {
>
>"start": "node ./node_modules/@node-wot/cli/dist/cli.js"
>
>...
>
>}
>
>```

I'd say that also `"start": "wot-servient"` should work. if it is not I think we should create another issue to track this problem.

**Comment by TimKam** [comment]
Good point. This works if the CLI is locally installed, which again supports the idea of making the CLI an "ordinary" dependency. If the CLI is globally installed, it won't find the local dependencies. I can add a PR that updates the documentation accordingly. I'll try to have a look at the setup tool in some days.
