### ISSUE TITLE
Testing CBOR implementation

### ISSUE THREAD

**Issue by Giammkk** [eclipse/thingweb.node-wot#296]
Hi, I implemented the support for CBOR. I  added this script in `core/src/codecs` and I import the `CBORCodec` class in `content-serdes.ts`, but I'm facing difficulties in checking if it works properly. The read/write functions work but I'm worried whether thingweb actually uses CBOR  or some default mediatype. I've noticed `ContentSerdesTest.ts` in `core/test`, but when I run `npm run build`, it doesn't transcompile what it is inside the test folder. So, how can I verify my implementation?

```
import { ContentSerdes, ContentCodec } from "../content-serdes";
import * as TD from "@node-wot/td-tools";
const cbor = require("cbor");

/** default implementation offering CBOR de-/serialisation */
export default class CBORCodec implements ContentCodec {

  getMediaType(): string {
    return 'application/cbor';
  }

  bytesToValue(bytes: Buffer, schema: TD.DataSchema, parameters: { [key: string]: string }): any {
    //console.log("testb2v");
    let parsed: any;
    try {
      parsed = cbor.decodeAll(bytes)[0];
    } catch (err) {
      if (err instanceof SyntaxError) {
        if (bytes.byteLength == 0) {
          parsed = undefined;
        } else {
          parsed = bytes.toString();
        }
      } else {
        throw err;
      }
    }

    if (parsed && parsed.value !== undefined) {
      console.warn("[core/cbor-codec]",`CBORCodec removing { value: ... } wrapper`);
      parsed = parsed.value;
    }
    return parsed;
  }

  valueToBytes(value: any, schema: TD.DataSchema, parameters?: { [key: string]: string }): Buffer {
    //console.debug("CBORCodec serializing", value);
    let body = "";
    if (value !== undefined) {
      return cbor.encode(value);
    }
    return Buffer.from(body);
  }
}
```

**Comment by relu91** [comment]
You should register your codec to the [static method](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts#L45) of `ContentSenders` class. Then the servient will use it if the mediaType equals to `'application/cbor'`.

About unit tests, they are not transcopiled by default (i.e. they should not be distributed). To run them you can use `npm run test` on the core package. If you are still confused you can provide a PR and we can guide you to the right path.

**Comment by danielpeintner** [comment]
BTW, we plan to support *pluggable* content-serdes in the same fashion as we do for bindings.

We are still exploring possible solutions. Input with that regard is welcome ...

**Comment by danielpeintner** [comment]
relates to https://github.com/eclipse/thingweb.node-wot/pull/304

**Comment by danielpeintner** [comment]
There is a way to plug-in *new* codecs to content serdes as illustrated in https://github.com/eclipse/thingweb.node-wot#mediatype-support

Hence, I am going to close this issue.
