### ISSUE TITLE
[Modbus] Sync terms with binding template vocabulary

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#297]
should be in sync with https://github.com/w3c/wot-binding-templates/pull/98

**Comment by relu91** [comment]
Please assign this to me.

**Comment by relu91** [comment]
Between the other changes we need to update FunctionNames.

The ontology currently uses `readHoldingRegisters` but the implementation uses `readMultipleHoldingRegisters`

**Comment by danielpeintner** [comment]
are there still pending items or can the issue be closed?
@relu91

**Comment by relu91** [comment]
Yes, to the best of my knowledge the implementation is now aligned to what is described in the binding templates. I suggest opening specific issues about not-aligned terms if it is not the case. Closing.
