### ISSUE TITLE
readallproperties & readmultipleproperties op's are accesible?

### ISSUE THREAD

**Issue by erceguder** [eclipse/thingweb.node-wot#299]
I'm not sure if this needs to be fixed but when an `exposedThing` instance is created, the TD generated by the method `WoT.produce()` has an element in it's `forms` array with `op`s `readallproperties` and `readmultipleproperties`, independent of either `Thing` possesses `'properties'` or not.

**Comment by danielpeintner** [comment]
It does not harm (like it it is now) but I agree it should not happen. I will try to take a look and report back.

Thanks @erceguder
