### ISSUE TITLE
Allow to add static addresses via wot-servient.conf.json

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#3]
Add a field to wot-servient.conf.json, which is passed to the Helper to statically add them to the getAddresses function.

**Comment by mkovatsc** [comment]
For now added field `staticAddress` for a single manual address used for all servers.

Please comment with use cases for multiple manual addresses.

**Comment by danielpeintner** [comment]
No more use-cases -> closing
