### ISSUE TITLE
"events" > ... > "op" > "unsubscribeevent" missing on generated TD

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#306]
see https://github.com/w3c/wot-scripting-api/issues/233 reported by @weigandjakob

**Comment by danielpeintner** [comment]
PR https://github.com/eclipse/thingweb.node-wot/pull/307 should resolve the issue.

The *new* resulting TD with your example code looks as follows.

```
{
	"title": "MyCoffeeMachine",
	"description": "A very special coffee machine",
	"securityDefinitions": {
		"no_sc": {
			"scheme": "nosec",
			"in": "header"
		}
	},
	"security": ["no_sc"],
	"events": {
		"not_enough": {
			"data": {
				"type": "string",
				"enum": ["Water", "CoffeeBeans"]
			},
			"forms": [{
				"href": "http://localhost:9200/MyCoffeeMachine/events/not_enough",
				"contentType": "application/json",
				"subprotocol": "longpoll",
				"op": ["subscribeevent", "unsubscribeevent"]
			}, {
				"href": "coap://localhost:9201/MyCoffeeMachine/events/not_enough",
				"contentType": "application/json",
				"op": ["subscribeevent", "unsubscribeevent"]
			}]
		}
	},
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"@type": "Thing",
	"id": "urn:uuid:8b41cb7a-fd9a-4f8d-99f5-60c8028c35dd"
}
```

@weigandjakob can you confirm it is ok

**Comment by weigandjakob** [comment]
@danielpeintner Yes, looks good as far as I can tell.

Only one small question for a better understanding: Why did the generation of "readallproperties", "readmultipleproperties" also change? Are there some generation parameters or was this a change in the default behavior?

**Comment by danielpeintner** [comment]
> Only one small question for a better understanding: Why did the generation of "readallproperties", "readmultipleproperties" also change? Are there some generation parameters or was this a change in the default behavior?

There was a recent change that adds "readallproperties" and "readmultipleproperties" only if there are any properties. In your example there aren't.

**Comment by danielpeintner** [comment]
resolved by https://github.com/eclipse/thingweb.node-wot/pull/307
