### ISSUE TITLE
binding-file: replace deprecated new Buffer

### ISSUE THREAD

**Issue by 6d77** [eclipse/thingweb.node-wot#31]
When using the file binding I get the following warning on the console:

```
(node:9222) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

The reason is the following line:

https://github.com/eclipse/thingweb.node-wot/blob/b4bcbd5a22bbab74c88a3df7a39e6ef970909348/packages/binding-file/src/file-client.ts#L55

I propose to follow the recommendation given in the warning and replace the constructor by one of the factory methods.

**Comment by mkovatsc** [comment]
Done in c6d966dda3f5d3c6b04625f1bf43de9f9ea08d39
