### ISSUE TITLE
Slugify title in URLs

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#313]
From Telegram discussion:
If we use slagify then the thing titles containing spaces will be automatically converted to the ones using dashes not `%20`.
So that, `Smart Coffee Machine` becomes `smart-coffee-machine` (note lowercase as well) and we are not obliged to use dashes in titles for readability in URLs.

**Comment by danielpeintner** [comment]
I like the proposal to use more *readable* URLs.

The only downside that comes to my mind is that at the moment there is a 1-to-1 mapping from title to URL. This is going to fail with the proposed change:
`"title": "Smart Coffee Machine"`
and
`"title": "Smart-Coffee-Machine"`
and many more variante lead to the same url
`smart-coffee-machine`

**Comment by fatadel** [comment]
I agree with you, @danielpeintner.
But to overcome the downside you've mentioned we can simply log the generated URL.
If we do it on `console.log` level we can be sure that this message never gets suppressed and the user knows where to look for the exposed Thing.

**Comment by egekorkan** [comment]
Yes but log messages get lost easily among other messages. Not objecting this need but only 90% convinced on the solution.

**Comment by danielpeintner** [comment]
An alternative is to make sure that by means of slagify we never get duplicates.

Having said that, a second *thing* getting the same URL would need to 
a) get another URL (and we need to store that URL internally) or
b) being refused to be exposed due do conflicts

**Comment by fatadel** [comment]
I think keeping the list of URLs and appending some suffix to conflicting ones is better than refusing to expose and making the user change the Thing title.

**Comment by relu91** [comment]
> I think keeping the list of URLs and appending some suffix to conflicting ones is better than refusing to expose and making the user change the Thing title.

IMHO this behavior can be easily implemented by the developer. I think failing should be the best option. It is better than falling silently and change the title.

 > But to overcome the downside you've mentioned we can simply log the generated URL.
If we do it on console.log level we can be sure that this message never gets suppressed and the user knows where to look for the exposed Thing.

A link to the generated TD might be still nice. However, no `console.log` this message is clearly a debug message to help developers test their generated Web Things. I see it hardly useful in production.

**Comment by danielpeintner** [comment]
> > I think keeping the list of URLs and appending some suffix to conflicting ones is better than refusing to expose and making the user change the Thing title.
> 
> IMHO this behavior can be easily implemented by the developer. I think failing should be the best option. It is better than falling silently and change the title.

We can also keep the title as is and still add some suffix to the URL. The user just won't find it where it expects it to be. Moreover, we would need to update several parts of the code that use the uniqueness of the title to generate URLs ...

I am like @egekorkan I guess. I am not yet 100% sure whether it is worth the effort and the possible downsides/problems...

**Comment by danielpeintner** [comment]
@fatadel do you want to work on a PR if you feel like it is worth it?

**Comment by fatadel** [comment]
@danielpeintner Yeah, I can propose a solution and then we can decide if it's worth it or not.
Should I use something like https://www.npmjs.com/package/slugify, or just write it as a custom method without external dependencies?

**Comment by danielpeintner** [comment]
I know the code would not be terribly complicated but I would rather pick something *proven*  ;-)

**Comment by fatadel** [comment]
> I know the code would not be terribly complicated but I would rather pick something *proven*  ;-) 
> 
> 
> 
> 

Okay :)

**Comment by fatadel** [comment]
Please check out my PR for this issue - #317.
I've tried making the least breaking changes to the code, please let me know if it suffices.
Or in case I've missed out somewhere the usage of a title in URLs.
