### ISSUE TITLE
[core][cli] Upgrade to vm2

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#314]
Currently, we are using the node `vm` module to load and execute WoT applications. However, `vm` has different problems:
1. it is not completely "safe". [Here](https://github.com/patriksimek/vm2#vm2-----) is explained how a malevolent script can access the main context and kill the servient. 
2. it is difficult to make `require` works. As discussed in different issues/PRs is not possible to require local modules or scripts without heavy modification to the current code. Modifications that will end up very similar to what is already implemented in vm2.

So my suggestion is to upgrade to [vm2](https://github.com/patriksimek/vm2) which has interesting features  (from the readme):
* Runs untrusted code securely in a single process with your code side by side
* Full control over sandbox's console output
* Sandbox has limited access to process's methods
* Sandbox can require modules (builtin and external)
* You can limit access to certain (or all) built-in modules (*currently is not working in our servient CLI*)
* You can securely call methods and exchange data and callbacks between sandboxes
* Is immune to all known methods of attacks
* Transpilers support (*so we may support TS from the cli without the building step*)

What do you think? I can volunteer to make this happen.

**Comment by egekorkan** [comment]
Sounds very good!

**Comment by danielpeintner** [comment]
>     * Transpilers support (_so we may support TS from the cli without the building step_)

This would be very cool.

> What do you think? I can volunteer to make this happen.

Great, thanks!
