### ISSUE TITLE
[http/core] ERR_STREAM_WRITE_AFTER_END error after the first event

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#323]
The servient crashes with the error in the title when it sends the second event on an HTTP long polling subscription.

### how to reproduce
consumer.js
```js
WoT.consume({
    title: "test",
    events: {
        test: {
            forms: [
                {
                    href: "http://localhost:8080/test/events/test",
                    contentType: "application/json",
                    subprotocol: "longpoll",
                    op: [
                        "subscribeevent",
                        "unsubscribeevent"
                    ]
                }]
        }
    }
    }).then( thing => {
        thing.subscribeEvent("test",()=> console.log("event"))
    } );
```  
producer.js
```js

WoT.produce({
  "title":"test",
  "events":{
    test:{}
  }
}).then(exposing => {
  exposing.expose();
  setInterval(() => {
    exposing.emitEvent("test")
  }, 1000);
});
```
run:
```js
wot-servient producer.js
```
```js
wot-servient -c consumer.js
```

I can volunteer to work on PR so please assign me.

**Comment by danielpeintner** [comment]
Thanks Cristiano!

**Comment by relu91** [comment]
I dug into the problem. Putting simply, the issue is that we do not unsubscribe event callbacks. The `http-server` subscribes to the `thing` event using `thing.subscribeEvent` every time it receives an HTTP LP request. After one event is sent it unsubscribes using `thing.unsubscribe`, but as you can see we do not actually unsubscribe the callback:
```typescript
public unsubscribeEvent(name: string): Promise<void> {
        return new Promise<void>((resolve, reject) => {
            if (this.events[name]) {
                let sub: Subject<any> = this.events[name].getState().subject;
                // sub.unsubscribe(); // XXX causes loop issue (see browser counter example)
                console.debug("[core/exposed-thing]",`ExposedThing '${this.title}' unsubscribes from event '${name}'`);
            } else {
                reject(new Error(`ExposedThing '${this.title}', no event found for '${name}'`));
            }
        });
    }
```
Consequently, the next time that the thing emits an event, we call also the previous callback which contains a dead HTTP connection ---> ERR_STREAM_WRITE_AFTER_END. 

However, it is more complex than it seems. I can solve the loop problem (it is caused by misuse of `rxjs` API) but, now I wonder what happens when two or more consumers crate an HTTP long polling request? see this simplified code:
```js
// HTTP-server

// new HTTP LP request arrived
thing.subscribeEvent("event",(data)=>{ res.end(data); thing.unsubscribe(event); })
// another HTTP LP request from a different client
thing.subscribeEvent("event",(data)=>{ res.end(data); thing.unsubscribe(event);})

// event happens here
// one of the two callbacks runs
// thing.unsubscrbe is called 

// what happens to the second callback? 
```

As I see it this is not an easy fix, and it will require some refactoring. I propose two solutions:
1. Since the new APIs might be able to unsubscribe specific callbacks we can move this issue fix to 0.8.x branch. 
2. It seems that this implementation of `emitEvent` differs from what we are describing [here](https://w3c.github.io/wot-scripting-api/#the-emitevent-method). In the algorithm is said that the emitEvent method calls directly the underling runtime and the runtime uses the ProtocolBinding layer to deliver this message. In `node-wot` implementation it is the opposite. The Binding subscribes to the upper layers for events and then it delivers them. So my point is to refactor the `emitEvent` method to align with the specs, consequently solving also this issue. 

What do you think? do you see any other options?

**Comment by danielpeintner** [comment]
>     1. Since the new APIs might be able to unsubscribe specific callbacks we can move this issue fix to 0.8.x branch.

Now I recall that issue and I think you are right branch 0.8.x and the revised subscribe/unsubscribe might help. Let's postpone it till we actively work on 0.8 and the new API.

**Comment by SteinerPascal** [comment]
At the moment I'm testing an experimental WoT demo in which my client-Servient subscribes to a motion triggered sensor on my server-Servient. I'm running in the same issue described here. Did I understand it correctly, that at the moment it is not possible to subscribe to an event which gets triggered multiple times? Is there a workaround?

**Comment by relu91** [comment]
Yes, at least as I recall it. A workaround could be to use another protocol instead of HTTP, perhaps MQTT.

**Comment by SteinerPascal** [comment]
Okay thank you for the quick answer!

**Comment by AdamF42** [comment]
Hi, I'm working on project where several components use the http-binding. 
One of the things generates an event at fixed interval. In my case no error is reported (node v15.4.0, node-wot/core 0.7.4, node-wot/binding-http  0.7.4) but the client application log shows "[core/content-senders] ContentSerdes serializing to application/json" for every event generated previously. 
I think it is related to the same problem. 
Since I can't change the protocol, is there any other workaround at least to solve the loop problem?

**Comment by danielpeintner** [comment]
We might need to look into the issue for v.7.x OR we postpone the problem till the *new* scripting API v.8.x is in place. 

> Since I can't change the protocol, is there any other workaround at least to solve the loop problem?

You can always "poll" values (instead of using eventing) after certain time-outs even though this should not be the case :-(

**Comment by relu91** [comment]
> We might need to look into the issue for v.7.x OR we postpone the problem till the new scripting API v.8.x is in place.

I'll wait for the v0.8.x to happen and I agree polling might be a dirty workaround but it should work in the meantime.

**Comment by relu91** [comment]
Since we are working on `ExposedThing` interface, I think we should also solve this issue @fillobotto
