### ISSUE TITLE
writeOnly properties can be read?

### ISSUE THREAD

**Issue by erceguder** [eclipse/thingweb.node-wot#326]
As far as I've observed, node-wot does not allow readOnly properties to be written, replying with a `Property readOnly` body. However, writeOnly properties can be read (though `op` only has the element `writeproperty`), isn't this a problem ?

**Comment by danielpeintner** [comment]
Thanks for reporting. The PR https://github.com/eclipse/thingweb.node-wot/pull/328 has been started to fix the issue.
