### ISSUE TITLE
Breaking rename within 0.5.0-SNAPSHOT versions: get/set -> read/write

### ISSUE THREAD

**Issue by mkovatsc** [eclipse/thingweb.node-wot#33]
In the Scripting API call we decided to align the get/set vs read/write terms used also in the TD and Binding Templates to a uniform read/write.

See https://github.com/w3c/wot-scripting-api/issues/127

**Comment by danielpeintner** [comment]
Note: The same issue exists for actions: "run" in node-wot vs. "invoke" in Scripting API (see https://rawgit.com/zolkis/wot-scripting-api/master/index.html#the-thingaction-interface)

**Comment by mkovatsc** [comment]
Was done in 19db385514a9947d3cee1398bd5798962a6f0274

Examples are updated.
Scripts at other locations based on v0.5.0* need to be updated.
