### ISSUE TITLE
Validate input data based on DataSchema

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#332]
At the moment node-wot core simply passes any value that it gets for a given property et cetera.

Hence even IF we have `"type": "number"` a string would work unless the binding/handler refuses the data.

I think the core should be validating input data. This means we should plugin a library like [avj](https://ajv.js.org/) to validate JSON.

However it causes some problems IF the data that comes in is **not** JSON. We do not have (and probably won't have) libraries for XML, EXI, ... and other formats. I think this is out-of-scope.

It gets more interesting what we want to do with formats like CBOR or EXI4JSON that are JSON-based and could be validated.

Comments/suggestions are welcome.

**Comment by danielpeintner** [comment]
see https://github.com/eclipse/thingweb.node-wot/blob/master/examples/templates/exposed-thing/src/base.ts#L126

**Comment by egekorkan** [comment]
I would firstly wait for the .value() feature to come to node-wot. Then, I would see some different solutions:
- provide a `validate()` function on the scripting level that can be used in interaction handlers. The developer chooses to uses it based on the data.
- provide a validate option that defaults to "yes validate" in interaction handlers that can be replaced with no validation or a custom validator by the developer. Even though ajv is very good, maybe some people have better solutions etc. OR the data is not JSON
- Let the codecs do validation (as precision to the one above)
- Don't let the codecs do the validation but try to transform everything to JSON and if it cannot be transformed, return a corresponding value to programmer. If it is transformed, do validation before/after the codecs

As a different question, what about validation on the ConsumedThing interface ?

**Comment by danielpeintner** [comment]
Okay, let's wait till the updated API is in place!

**Comment by relu91** [comment]
> Okay, let's wait till the updated API is in place!

I agree.

> provide a validate option that defaults to "yes validate" in interaction handlers that can be replaced with no validation or a custom validator by the developer. Even though ajv is very good, maybe some people have better solutions etc. OR the data is not JSON

I like this idea, probably it would be good to have also a *global* option in the servient. So one can personalize it more easily (i.e. he don't need to set the validation function for each interaction). However, this is implementation-specific and should not be introduced in the API spec. 

 > Don't let the codecs do the validation but try to transform everything to JSON and if it cannot be transformed, return a corresponding value to programmer. If it is transformed, do validation before/after the codecs

It would be easier and more portable to go down this path. The value function is in charge to create valid Javascript objects so in my mind it is more natural to validate JSON.

**Comment by danielpeintner** [comment]
Basic data validation is in place.
