### ISSUE TITLE
core/content-serdes.ts: provide more information to ContentCodecs

### ISSUE THREAD

**Issue by 6d77** [eclipse/thingweb.node-wot#34]
Currently the converter methods of `ContentCodec` just have the following simple signatures:

```javascript
  bytesToValue(bytes: Buffer): any
  valueToBytes(value: any): Buffer
```

It would be helpful to provide more information to these methods to help them doing the correct encoding and decoding.

For `bytesToValue` it would be helpful to have the following additional information:

* "type" of the expected result, as e.g. specified for a property in the TD
* additional parameters of the media type, e.g. `charset` or other specific parameters for specific media types

For `valueToBytes` the "type" of the property is probably not needed, as this is the type of the parameter itself. It would however be helpful to properly understand the `value` parameter. The additional parameters to the media type however would also be required in some cases to do a proper encoding.

**Comment by mkovatsc** [comment]
Done in 955f67d463c6bd52a71ebc49468c09600fb06192

`bytesToValue()` now also gets the DataSchema and the parameters part of the content type.

**Comment by danielpeintner** [comment]
@6d77 is this issue still relevant or resolved by now?

**Comment by 6d77** [comment]
is already solved
