### ISSUE TITLE
Setting log level without the cli tool?

### ISSUE THREAD

**Issue by erceguder** [eclipse/thingweb.node-wot#344]
[Here](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/cli/README.md), setting log level for `Servient` is shown for the CLI tool. How can I set log level when node-wot is installed as a npm dependency?

**Comment by egekorkan** [comment]
Can be closed? :)

**Comment by danielpeintner** [comment]
Agree.

Moreover, it is also linked by the [question](https://github.com/eclipse/thingweb.node-wot/issues?q=label%3Aquestion+) label from main readme.
