### ISSUE TITLE
[Question] Assistance Implementing a Property

### ISSUE THREAD

**Issue by oHotel** [eclipse/thingweb.node-wot#345]
I am struggling to create a thing including a property representing an image (JPEG). Three questions arise here:

1. How to create the corresponding property in WoT.produce?
   My attempts:
      `“picture” : {description: “JPEG image”, type:”image/jpeg”, observable:true}`; and
      `"picture” : {description: “JPEG image”, forms:[{contentType: "image/jpg" }], observable:true}`
 
2. What is the type of the second argument of writeProperty (“picture”, arg2)?
   Arg2 = path to the JPEG file ?
   Arg2 = frame Buffer?

3. Can the picture be displayed in the provided browser example?

Any suggestions would be appreciated.

**Comment by danielpeintner** [comment]
There is a running  counter example, see http://plugfest.thingweb.io/examples/counter.html.
The code for it is here: https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js

It contains a "red dot" PNG see [here](http://plugfest.thingweb.io:8083/counter/properties/redDotImage)

Hope this helps to provide the right pointers....

**Comment by othello25** [comment]
I have a similar issue:

Line 149 https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js

What is 
`"iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="` ?
a raw binary dump of the redDotImage?

I am still investigating, I will keep you informed.

**Comment by miguelrk** [comment]
Hey @othello25  jumping-into the discussion...

`iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==` is a Base64 encoded string of the PNG image (image/png) .

You can test it yourself using the decoder over at [https://base64.guru/converter/decode/image](https://base64.guru/converter/decode/image).

Hope this helps. I was also looking to implement this, just wondering if making the property observable would work? I will propably try it and let you know

**Comment by relu91** [comment]
Since the question is already been answered and there is no follow up I'd close the issue.
