### ISSUE TITLE
[test] OPCUA tests fail on Windows

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#349]
The OPCUA tests fail on Windows (depending on setup?)
_**it used to work on my Windows box but does not any longer**_

Hence we should try to fix the problems by
1. Fix the actual issues (linux and windows treat differently unreachable hosts)
2. Don't run OPCUA tests on Windows (e.g., by using https://github.com/charlesguse/run-script-os or so )

"1." is preferred

**Comment by danielpeintner** [comment]
Since some days the OPCUA tests fail. Initially I thought it was related to my local Windows machine setup since the code itself didn't change for a while.

Having said that, it now fails on Travis also (see https://travis-ci.org/github/eclipse/thingweb.node-wot/jobs/739568120)
@lukesmolo do you have more insights what might be happening?

**Comment by lukesmolo** [comment]
From logs it seems it does not instantiate the local server that is needed for testing the client. I can have a look at it in the next days for sure.

**Comment by danielpeintner** [comment]
Great! Thank you for your support and your quick answer!

**Comment by danielpeintner** [comment]
FYI: for the time being we [ignore](https://github.com/eclipse/thingweb.node-wot/pull/354) all OPCUA tests.  Please re-activate them once they are working again. Thanks!

**Comment by lukesmolo** [comment]
Something changed in the _node-opcua_ library while instantiating a server needed for the tests. The server hence was not running and each test failed. Together with @relu91 we solved it and he made a new PR.

**Comment by danielpeintner** [comment]
Thanks @lukesmolo and @relu91 

What I still don't understand is the fact that the node-opcua library changed without actually increasing the version.
My *naive* understanding is that this should not happen...

**Comment by relu91** [comment]
It might be the fact that opcua dependency is recorded as "^2.4.3". This implies that every minor version is valid (see the [specs](https://docs.npmjs.com/about-semantic-versioning)). However, I tried to downgrade to exactly 2.4.3 I had still encountered the same error 🤔.

**Comment by danielpeintner** [comment]
Mhh, strange. Thanks for looking into it!
