### ISSUE TITLE
Proper validation of config files

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#353]
Discussion in https://github.com/eclipse/thingweb.node-wot/pull/352#issuecomment-721386867 highlighted the fact that [mergeConfigs](https://github.com/eclipse/thingweb.node-wot/blob/d420cfb259dc01d23177fe40ff5c4dea4799cdbc/packages/cli/src/cli-default-servient.ts#L60) has some undesired effects:
e.g.,  any default binding kicks in (even if not desired!)

The idea raised was to use JSON schema default values (see https://ajv.js.org/#assigning-defaults). This way, the `mergeConfigs` function would not be needed anymore.

Moreover, a proper check for configs is done that way also.

The only "downside" I see is that we add a new [ajv](https://www.npmjs.com/package/ajv) dependency.
Having said that, we might need this in the future anyway IF we want to provide proper input validation, see https://github.com/eclipse/thingweb.node-wot/issues/332

Any comment? @relu91 @egekorkan 
Shall we go for it?

**Comment by relu91** [comment]
I support this change, avj is just110 Kb and it has a pretty big community. We'll totally improve node-wot having it has a dependency. 

> Having said that, we might need this in the future anyway IF we want to provide proper input validation, see #332

This is a strong reason to have it, in my opinion.

**Comment by egekorkan** [comment]
I also support it. Also it would be a dependency only in the cli for now :)

**Comment by egekorkan** [comment]
Yes! Can be closed :)
