### ISSUE TITLE
WoT-Servient cannot start: read ECONNRESET

### ISSUE THREAD

**Issue by chriskarapapas** [eclipse/thingweb.node-wot#360]
Hello, 
after install i tried to run the examples but i get the following output:
binding-mqtt] MqttBrokerServer could not connect to broker at mqtt://test.mosquitto.org on Ubuntu 20.04
Any ideas?

**Comment by egekorkan** [comment]
I think that the official mosquitto test server is down? If I try `mosquitto_pub -h test.mosquitto.org -t "hello" -m "yiyi"` it says `Error: The connection was lost.`. However, trying the same command with localhost for the mosquito broker running in my own computer works.

Could you try starting a broker locally and test again?

**Comment by chriskarapapas** [comment]
@egekorkan Everything runs perfect locally! Thanks

**Comment by egekorkan** [comment]
No problem :) @danielpeintner could you close this issue?
