### ISSUE TITLE
http-client-factory.js null check missing

### ISSUE THREAD

**Issue by jplaui** [eclipse/thingweb.node-wot#37]
Line [35](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-client-factory.ts#L35) of the thingweb.node-wot/packages/binding-http/src/http-client-factory.ts file does not check if `this.config` is `null` . The this.config.proxy access results in an error if no configuration is set during HttpClientFactory initialization.

Line which caused the error: `servient.addClientFactory(new HttpClientFactory());`

Adding the null check (this.config != null) solved the problem for me.
```javascript
HttpClientFactory.prototype.getClient = function () {
        if (this.config != null) {
            if (this.config.proxy && this.config.proxy.href && this.config.proxy.href.startsWith("https:")) {
                console.warn("HttpClientFactory creating client for 'https' due to secure proxy configuration");
                return new http_client_1.default(this.config, true);
            }
        }
        else {
            console.log("HttpClientFactory creating client for '" + this.scheme + "'");
            return new http_client_1.default(this.config);
        }
    };
```

**Comment by danielpeintner** [comment]
I opened a PR for this. Thanks for reporting this issue!
