### ISSUE TITLE
Forms value and data validation for properties

### ISSUE THREAD

**Issue by Martinocom** [eclipse/thingweb.node-wot#375]
# Background

I created a simple TD that has some attributes. I will simplify it, to get to the point:

```
{
    ....
    "title":"TV",
    "description": "A simple (not-so) Smart TV that can be controlled remotely.",
    "properties": {
        ....
        "channel" : {
            "type": "number",
            "title": "Channel",
            "description": "The number of the channel",
            "minimum" : 1,
            "maximum" : 255,
            "readOnly" : false,
            "writeOnly" : false,
            "forms": [{"href": "/channel"}]
        },
        ....
}
....
```

Considering this TD, this command should work:
```
PUT localhost:8080/things/tv/properties/channel
Body: 5
Headers: Content-Type: application/json
```

But **this should not**, since I specified the minimum and maximum values:
```
PUT localhost:8080/things/tv/properties/channel
Body: -1
Headers: Content-Type: application/json
```

**Neither this command should work**, since I specified that I want a `number`:
```
PUT localhost:8080/things/tv/properties/channel
Body: "hello"
Headers: Content-Type: application/json
```

**But all of them works**. They are rejected because I manually check for the `typeof`, but the type of the data should be a thing for the Thing Description itself.

# Is the "form validation" automatic? How I can achieve it? 
Documentation about [DataSchema](https://www.w3.org/TR/wot-thing-description/#sec-data-schema-vocabulary-definition) says about proper `type` and his specific schema, like for `number` there is a [`NumberSchema`](https://www.w3.org/TR/wot-thing-description/#numberschema) with minimum and maximum. There there is a link for [Binding Templates](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/) where it speaks about [Payloads and DataSchema](https://www.w3.org/TR/2020/NOTE-wot-binding-templates-20200130/#payload-structure): should I use all that payload to send data? In the body, should I use a JSON object like `{ 2 }` or `{ data: { channel: 2 }}` or a "plain value" like `2` to `PUT` data?

Even in the [testthing.js](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/testthing/testthing.js) there is no explicit validation to the form, but a generic `typeof` check.

So what I'm asking is if **_it is possible to do something like:_**

```
thing.setPropertyWriteHandler(propertyName, async(value) => {
    let form = thing.getFormFor(propertyName)
    let isValid = form.validate(value)
    if (isValid) {
        // OK - valid :)
    } else {
        // Oh no - not valid :(
    }
})
```

# Why form attribute is overwritten? 
I wanted to add "for fun" an extra form for the "channel" property, that will be something like this:
```
"forms": [{
        "href": "/channel"
        ...
    }, {
        "href": "/channel/extra"
        ...
    }
]
```
but eventually the final exposed thing **will NOT** have that extra form. It will generate only forms following the DataSchema specification, indicating `readOnly` and `writeOnly` attributes (example, indicating `readOnly: true` it will generate only the form with `readproperty`, not the `writeproperty` one). 

Adding the _'extra'_ form on properties or in the `forms` of the Thing Descpription itself does not change the situation.

Am I wrong wanting to put extra forms? Am I doing wrong to achieve what I want?

**Comment by egekorkan** [comment]
- The input validation is an upcoming feature so it is "normal" that you can write a string for a number property. 
> So what I'm asking is if it is possible to do something like:

That is indeed possible. You can check out the use of AJV library [here](https://github.com/eclipse/thingweb.node-wot/blob/62106f4978d88a7cf70f3333ba801f00cdf4d929/examples/templates/exposed-thing/src/base.ts#L124)

- `forms` are not editable to the full extent. You can only specify contentType and that would be used if you have given json, svg or png.

**Comment by danielpeintner** [comment]
Note: w.r.t. validation there is an open issue, see https://github.com/eclipse/thingweb.node-wot/issues/332

**Comment by relu91** [comment]
I quote what is said above. About form configuration, we had some discussion about how to improve it but is still an open issue in my mind. Now we are focused more on bringing the new APIs, we could review the form configuration after that.

**Comment by danielpeintner** [comment]
1. data validation is in place now.
2. https://github.com/eclipse/thingweb.node-wot/pull/810 should let you add additional href endpoints

Can we close this issue?

**Comment by relu91** [comment]
I think we can move the discussion to https://github.com/eclipse/thingweb.node-wot/issues/842. The issue has already been marked as a question and it was addressed. Feel free to reopen it if you like.
