### ISSUE TITLE
observeProperty() has different value from readProperty()

### ISSUE THREAD

**Issue by Martinocom** [eclipse/thingweb.node-wot#376]
For this issue I need some background. I have a TV, that has 4 properties:
- status [true/false] - true = on, false = off
- channel [0-255]
- volume [0-100]
- brightness [0-100]

I have also a "local" object to maintain all the propeties, their names and default values, like this:
```
let localRef = {
    status: {
        name: "status",
        value: false,
    },
    channel: {
        name: "channel",
        value: null,
        default: 1,
        off: null
    },
    volume: {
        name: "volume",
        value: 0,
        default: 30,
        off: 0
    },
    brightness: {
        name: "brightness",
        value: 0,
        default: 50,
        off: 0
    },
    thing: null
}
```

Now, if `status` is false (TV is off) I want to avoid changing all the properties but the status itself. So a call like `PUT /volume {20}` will be denied until `status` is `true` (TV = on). This theoretically should be possible using a combination of:

- `setWritePropertyHandler()` for changes that I need to make **BEFORE** setting the `status`
  ```
  // Handling write of status property (BEFORE write)
  localRef.thing.setPropertyWriteHandler(localRef.status.name, async(data) => {
      if (!data) {
          // Only if TV pass from ON to OFF I need to bring all properties to "off" state
          await Promise.all([
              localRef.thing.writeProperty(localRef.channel.name, localRef.channel.off),
              localRef.thing.writeProperty(localRef.volume.name, localRef.volume.off),
              localRef.thing.writeProperty(localRef.brightness.name, localRef.brightness.off)
          ])
      }
      // After writing, data will be the official status of the TV 
      return data
  })
  ```

- `observeProperty()` for changes that I need to make **AFTER** setting the `status`
  ```
  // Observing status of status property (AFTER write)
  thing.observeProperty(localRef.status.name, async(data) => {
          if (data) {
              // Only if TV pass fron OFF to ON I need to bring all properties to "on" state
              await Promise.all([
                  localRef.thing.writeProperty(localRef.channel.name, localRef.channel.default),
                  localRef.thing.writeProperty(localRef.volume.name, localRef.volume.default),
                  localRef.thing.writeProperty(localRef.brightness.name, localRef.brightness.default)
              ])
          }
  
          // Change of status is already made, so no need to return anything
      })
  ```

Why I need this order of operations? Because in every single writeHandler of the following properties I have a simple check: _you can write new data ONLY if TV is on_:

```
    // Override behavior on writing status property
    localRef.thing.setPropertyWriteHandler(localRef.channel.name, async(data) => {
        return getPropertyToWrite(localRef.channel.name, data)
    })
    localRef.thing.setPropertyWriteHandler(localRef.volume.name, async(data) => {
        return getPropertyToWrite(localRef.volume.name, data)
    })
    localRef.thing.setPropertyWriteHandler(localRef.brightness.name, async(data) => {
        return getPropertyToWrite(localRef.brightness.name, data)
    })
```

...where  the `getPropertyToWrite()` is a simple method that does:

```
async function getPropertyToWrite(propertyName, data) {
    let isTvOn = await localRef.thing.readProperty(localRef.status.name)
    let currentValue = await localRef.thing.readProperty(propertyName)

    if (isTvOn) {
        return data
    } else {
        return currentValue
    }
}
```

## The problem is that in `getPropertyToWrite()`, `isTvOn` result `false`. Why?
Is there something that causes triggering of the `observer` BEFORE it effectively writes its value to the Thing?

Let's check the code flow:

1.  TV is off
2.  I call `PUT /status {true}` to turn it on
3.  `writePropertyHandler()` of status is triggered, but does nothing and **write the value** `(true)`
4.  `observeProperty()` of status is triggered and it does something
5.  it calls all three async methods for writing data
6.  each method will trigger the `writePropertyHandler()` of its own property
7.  each `getPropertyToWrite()` should ask the thing for the status (that is set to `true`)
8.  **but isTvOn result is false**, even if `writePropertyHandler()` should set it as `true` in the 2. point

![wrong](https://user-images.githubusercontent.com/17514549/104737308-5b888b80-5744-11eb-9a43-fbb4307bb7e8.png)

To contextualize I attach the source: [attachments.zip](https://github.com/eclipse/thingweb.node-wot/files/5820971/attachments.zip)

And the most curious thing is that **if re-ask** for `await localRef.thing.readProperty(localRef.status.name)`, **the status WILL BE effectively `true`,** so I suppose that `observe` and `write` are two actions that are done simultanously and not one after each-other.

Any help or details?

**Comment by Martinocom** [comment]
Maybe I was trying to achieve something that is impossible to to with only properties. Still, I cannot explain why after `observing` that value changes to `true` it results as `false` afterwards, so I'm still leaving this issue as "open". 

Anyway, **I found a workaround for this problem**, reading also about issues for updating `readOnly` values in this repo.

**I don't use properties to set values anymore**: every property now is `readOnly` and I'm observing the `status`. I'm saving changes locally, where I have full control over the code and every request of writing a property is a simple "refresh" of the data I have locally. I still have the `localRef` object: same as previously, but now I'm using it actually to store data.

```
    // Set write/read properties
    localRef.thing.writeProperty(localRef.status.name, localRef.status.value)
    localRef.thing.writeProperty(localRef.channel.name, localRef.channel.value)
    localRef.thing.writeProperty(localRef.volume.name, localRef.volume.value)
    localRef.thing.writeProperty(localRef.brightness.name, localRef.brightness.value)

    // Overwrite behaviour on writing properties: just update them with local data
    localRef.thing.setPropertyWriteHandler(localRef.status.name, async(data) => {
        return localRef.status.value
    })
    localRef.thing.setPropertyWriteHandler(localRef.channel.name, async(data) => {
        return localRef.channel.value
    })
    localRef.thing.setPropertyWriteHandler(localRef.volume.name, async(data) => {
        return localRef.volume.value
    })
    localRef.thing.setPropertyWriteHandler(localRef.brightness.name, async(data) => {
        return localRef.brightness.value
    })
    
    // Observe status changes
    localRef.thing.observeProperty(localRef.status.name, async(data) => {
        if (data) {
            // TV changes its state to ON -> set default values
            writeProperty(localRef.brightness.name, localRef.brightness.default)
            writeProperty(localRef.volume.name, localRef.volume.default)
            writeProperty(localRef.channel.name, localRef.channel.default)
        } else {
            // TV changes its state to OFF -> set OFF values
            writeProperty(localRef.brightness.name, localRef.brightness.off)
            writeProperty(localRef.volume.name, localRef.volume.off)
            writeProperty(localRef.channel.name, localRef.channel.off)
        }
    })
```

Now every change is made inside **an action** that I defined in the Thing Description. With actions I have more control about what is happening inside and who is calling. I don't know if this is a "best practice", but in my case it works. I know that thinking about REST I should be able to set a thing like `channel` directly on a `PUT` but... Aren't actions ok?

```
    // Toggle it
    localRef.thing.setActionHandler("toggle", async(params) => {
        let status = await localRef.thing.readProperty(localRef.status.name)
        return writeProperty(localRef.status.name, !status)
    })

    // Change Channel
    localRef.thing.setActionHandler("set-channel", async(params) => {
        return checkIfCanWrite(localRef.channel.name, params.channel)
    })

    // Change Brightness
    localRef.thing.setActionHandler("set-brightness", async(params) => {
        return checkIfCanWrite(localRef.brightness.name, params.brightness)
    })

    // Change Volume
    localRef.thing.setActionHandler("set-volume", async(params) => {
        return checkIfCanWrite(localRef.volume.name, params.volume)
    })
    
    async function checkIfCanWrite(propertyName, valueToWrite) {
        let status = await localRef.thing.readProperty(localRef.status.name)
        if (status) {
            return writeProperty(propertyName, valueToWrite)
        } else {
            return "Tv is turned OFF. Impossible to perform [" + propertyName + "] update."
        }
    }

    function writeProperty(name, value) {
        // Write object locally
        for (const key of Object.keys(localRef)) {
            if (key == name) {
                localRef[key].value = value
            }
      }
  
      // Wirte object remotely
      return localRef.thing.writeProperty(name, value)
    }
```

I'm still using `await localRef.thing.readProperty(localRef.status.name)` for compatibility, since THIS is the official way the thing has to communicate his state. Local changes are mine changes, but the thing could change his state regardless of my decision.

Allso this time I'll attach the [source.zip](https://github.com/eclipse/thingweb.node-wot/files/5822222/source.zip)

**Comment by relu91** [comment]
As daniel said having the status locally will be the preferred way for the next API version. 

One unrelated suggestion that I can give you is that it is better to think more about WoTinteractions rather than REST verbs. From a WoT point of view, REST is just another protocol binding you shouldn't enforce designing choices from the protocol up to the interaction interface. The only exceptions of this "rule" are:
1. When you are integrating a pre-existent system 
2. When you have other non-wot services that interact with your device and expect a REST interface.

just my 2 cents.

**Comment by danielpeintner** [comment]
@Martinocom please let me know whether the issue should be kept open/re-opened (was closed automatically by merging PR)

**Comment by Martinocom** [comment]
-------------------------------
> One unrelated suggestion that I can give you is that it is better to think more about WoTinteractions rather than REST verbs. From a WoT point of view, REST is just another protocol binding you shouldn't enforce designing choices from the protocol up to the interaction interface.

Thanks for the Tip! 
In my specific case, I wanted to have a way to semantically describe Web Things. The only way I found was with this library, since others doesn't provide support for multiple @context values. Then the Web Things were there only to simulate a real world application, where **interoperability** is the key. Since I wanted Things that can be reachable by everyone (not restricted to platform-specific solutions), I preferred use REST that everyone can understand and I based all my project on it.

My work is unfortunately made entirely in Italian, but if someone wants to take a look it's [here](https://github.com/Martinocom/pervasive-semantic-exam). At this moment it's all a draft.


-------------------------------
> @Martinocom please let me know whether the issue should be kept open/re-opened (was closed automatically by merging PR)

@danielpeintner  Glad to contribute in this development: I think that we can close it, since issue is solved. Thanks!

**Comment by relu91** [comment]
> My work is unfortunately made entirely in Italian, but if someone wants to take a look it's here. At this moment it's all a draft.

Thanks for sharing your work! I'll look at it in my spare time. 

A presto! 👍
