### ISSUE TITLE
Removing VM from core package

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#377]
Even though I had discussed it with @danielpeintner and @relu91 I have realized that I did not open an issue about it.

In the core module and still in the 0.8.x branch at the servient (https://github.com/eclipse/thingweb.node-wot/blob/4c9152cb7bb8f10957b1ac9efa24c6d323dbe5c0/packages/core/src/servient.ts#L16) the VM module is included and the run script is also there. I think that this functionality should be moved to the CLI since it is not about the core servient functionality. It also causes issues in webpack where we have to manually remove the includes in where node-wot is installed at node_modules at https://github.com/tum-esi/wade

**Comment by danielpeintner** [comment]
@egekorkan did you explore the consequences moving the vm part from core to cli ?
Do plan to provide a PR for e.g., master branch? (we can merge proposed changes into 0.8x branch)

**Comment by egekorkan** [comment]
So I do not use the runScript functionality of the servient in any of my projects. Thus, I cannot say what it really changes. I have been simply removing it from the servient (removing the require and the functions to run scripts).
@relu91 you are using these functions I think?

**Comment by relu91** [comment]
> @relu91 you are using these functions I think?

yes, I'm using them and when I do it, I'll do it from CLI. I've never needed to use node-wot as a library and at the same time run scripts in the VM. In my mind, the use-cases where people we'll use both functionalities (i.e., embed node-wot in an application and run scripts in its VM) are few...

**Comment by egekorkan** [comment]
Alright then. Should we simply move them to the default servient of the CLI?

**Comment by danielpeintner** [comment]
Sounds good!
