### ISSUE TITLE
Specify dependencies more precisely to avoid issues

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#379]
see https://github.com/eclipse/thingweb.node-wot/pull/378#pullrequestreview-570381544

**Comment by egekorkan** [comment]
I like the comment https://github.com/eclipse/thingweb.node-wot/pull/378#pullrequestreview-570381544

Another possibility would be to also push the lock files so that the environment that tests it has the exact version we need. It also enables dependabot or similar things to work

**Comment by relu91** [comment]
>Another possibility would be to also push the lock files so that the environment that tests it has the exact version we need. It also enables dependabot or similar things to work.

Right, I've just seen that the package-lock is ignored. Usually, it should be committed (see [here](https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md#description)). With this fix we don't need to specify the exact version.
