### ISSUE TITLE
Can you issue a release?

### ISSUE THREAD

**Issue by Citrullin** [eclipse/thingweb.node-wot#388]
Next week starts the plugfest and we want to provide some IPv6 WoT TDs.
I fixed the IPv6 issue already in #363 
But the fix isn't included in the current node package. It would be great, if you can release a new package with this fix in it.
So that people can just update their projects and use it with IPv6.

**Comment by relu91** [comment]
I think we can release a v0.7.5. @danielpeintner?

**Comment by danielpeintner** [comment]
Yes, will do...

**Comment by danielpeintner** [comment]
release v0.7.5 ready

e.g., https://www.npmjs.com/package/@node-wot/td-tools
