### ISSUE TITLE
Dependency on wot-typescript definitions

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#392]
I have just realized that all the packages are using the 0.7.3 version of wot-typescript-definitions (https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/package.json#L27). Is this intended?

**Comment by danielpeintner** [comment]
The `"wot-typescript-definitions"` versioning an the `"@node-wot/package-name"` versioning is *NOT* aligned.

The only assumption in the past that holds is that `0.X.Y1` is working with  `0.X.Y2`.

Does this clarify the confusion?

**Comment by egekorkan** [comment]
ah I see. Then can we update all packages to 0.7.4 Snapshot 1? I use that in my own projects

**Comment by danielpeintner** [comment]
Mhh the change from `"0.7.3"` to `"0.7.4-SNAPSHOT.1"` was a snapshot only version and more intended for 0.8.x.

see https://github.com/w3c/wot-scripting-api/commit/b1ef74446342069d7789814e3ff2419fc6165514#diff-2d042e5f33a7b3f604ddfc171a9cd4066c19952ee99f53f93bf54c411ecfa880

Having said that, I would stick with `0.7.3`

**Comment by egekorkan** [comment]
Ah ok! closing :)
