### ISSUE TITLE
WebThingsIO implementation not compatible with node-wot

### ISSUE THREAD

**Issue by JohannesMerkt** [eclipse/thingweb.node-wot#393]
I tried to create a web thing with an arduino running an example code from [webthing-arduino](https://github.com/WebThingsIO/webthing-arduino) and connect with the node-wot client. When fetching the Thing Description node-wot complains: 

`Cannot consume TD because Property 'on' has no forms field`

The TD as json looks like this:
```
{
"id":"led",
"title":"Built-in LED",
"@context":"https://iot.mozilla.org/schemas",
"base":"http://192.168.178.143/",
"securityDefinitions":{"nosec_sc":{"scheme":"nosec"}},
"security":"nosec_sc",
"@type":["OnOffSwitch","Light"],
"links":[{"rel":"properties","href":"/things/led/properties"},{"rel":"actions","href":"/things/led/actions"},{"rel":"events","href":"/things/led/events"},{"rel":"alternate","href":"ws://192.168.178.143/things/led"}],
"properties":{"on":{"type":"boolean","@type":"OnOffProperty","links":[{"href":"/things/led/properties/on"}]}}
}
```

it has a links field rather than forms.

Here is the schema WebThingsIO is using: https://github.com/WebThingsIO/schemas

Since both libraries implement the [WOT Things Description](https://www.w3.org/TR/wot-thing-description/) they should work together.

It would be awesome if they could work together. 
 
Here the issue i openend on webthing-arduino: https://github.com/WebThingsIO/webthing-arduino/issues/134

**Comment by wiresio** [comment]
> Since both libraries implement the WOT Things Description they should work together.

Unfortunately Mozilla does not follow the W3C rec., see e.g. here: https://github.com/WebThingsIO/api/issues/149

**Comment by egekorkan** [comment]
Also look here: https://github.com/WebThingsIO/wiki/wiki/Mozilla-W3C-Differences

**Comment by JohannesMerkt** [comment]
Thank you for your quick reply. So i guess comatibility in the near future is unlikely. Thats sad. It puts me into the dilema that i want to be able to use a wide range of languages and hardware (arduino) to create web things, which is possible with WebThingsIO but I cannot simply interface with them with a library as they only have the gateway.

**Comment by relu91** [comment]
Hi Johannes, thanks for reporting the issue. As the others said we are well aware of the issue and I am glad to inform you that we have recently started working on a possible unification of the two models. I'm personally looking into the issue with the support of @sebastiankb and @benfrancis. So bear your Arduinos and ESP32s there's hope 😄

**Comment by benfrancis** [comment]
See also: https://github.com/WebThingsIO/gateway/issues/2802

**Comment by danielpeintner** [comment]
@benfrancis @relu91 I assume the efforts of aligning are still ongoing right?

**Comment by benfrancis** [comment]
@danielpeintner Actually the implementation work has unfortunately been paused for the last few months due to a shortfall in funding. I'm waiting on news on potential future funding to resume the work.

**Comment by relu91** [comment]
> @danielpeintner Actually the implementation work has unfortunately been paused for the last few months due to a shortfall in funding. I'm waiting on news on potential future funding to resume the work.

Yes, I confirm. However, when I stopped working on the integration I verified that the basic functionalities worked (read/write properties). I'll allocate some of my free time to report how much you can do with node-wot as a client of a web thing hosted in the WebThings gateway.
