### ISSUE TITLE
OPCUA Issues

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#395]
We seem to run into issues of OPCUA versioning.
see for example https://github.com/eclipse/thingweb.node-wot/pull/394/checks?check_run_id=2038479109

`Error: node_modules/node-opcua-basic-types/dist/attributeIds.d.ts(34,33): error TS2694: Namespace '"fs"' has no exported member 'OpenMode'.`

I assume this has to do with recent opcua updates and us having no "fixed" version in [`package.json`](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-opcua/package.json).

Does anyone mind if I update to "fixed" versions e.g., 
* "node-opcua": "^2.4.3" --> "node-opcua": "2.4.3"
* "node-opcua-client": "^2.1.8" --> "node-opcua-client": "2.1.8"

@relu91 @egekorkan or do you think it is caused by other aspects?

**Comment by danielpeintner** [comment]
related to https://github.com/eclipse/thingweb.node-wot/issues/379

**Comment by danielpeintner** [comment]
OR like @relu91 pointed out include package-lock.

Question. What do you prefer?
* fix version OR
* add package-lock

**Comment by egekorkan** [comment]
I see it happening in other projects and that's why I like pushing lock files :)

**Comment by relu91** [comment]
I'll add package-lock too. As another compelling evidence towards this decision, there's also the fact that neither [.gitignore.io](https://www.toptal.com/developers/gitignore/api/node) suggests ignoring package-lock.json files.

**Comment by mjkoster** [comment]
I just ran into the same issue trying to build. I can wait until the issue is resolved, or if it will be a while I could work around, since I don't use OPC UA at the moment
