### ISSUE TITLE
Align DataSchema with Scripting API changes

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#40]
* `type`  in `DataSchema` must not be required (see https://github.com/w3c/wot-scripting-api/issues/133)
* `DataSchema` has now `IntegerSchema` and `NumberSchema`

**Comment by mkovatsc** [comment]
Both Schemas have always been available.

type was made optional in e551d25 for wot-typescript-definitions.

**Comment by danielpeintner** [comment]
> type in DataSchema must not be required (see w3c/wot-scripting-api#133)
> DataSchema has now IntegerSchema and NumberSchema

implemented -> resolved
