### ISSUE TITLE
Wrong interface in binding-http/src/http.ts htv:fieldName htv:fieldValue 

### ISSUE THREAD

**Issue by maxim-s-barabash** [eclipse/thingweb.node-wot#404]
Hello everyone. noticed a minor discrepancy.

**what we have now**

https://github.com/eclipse/thingweb.node-wot/blob/0285771212558af8c973d8e0e74157b175416a32/packages/binding-http/src/http.ts#L62-L65
If guided by https://www.w3.org/TR/wot-binding-templates/#http-vocabulary-terms

**must be something like**

```typescript
 export class HttpMessageHeader { 
     public "htv:fieldName": string; 
     public "htv:fieldValue": string; 
 } 
 ```

**Comment by danielpeintner** [comment]
You are right. This looks strange... let me investigate!
