### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by MartinMeyer1** [eclipse/thingweb.node-wot#407]
Hi, I'm trying to use a thing with a basic http security. I don't understand why but my consumer seems to not find the credentials. I've looked for some examples and my code seems to be correct:

// Required module
const {HttpsClientFactory} = require("@node-wot/binding-http");
Servient = require("@node-wot/core").Servient

// create Servient and add HTTP binding
let servient = new Servient();

servient.addClientFactory(new HttpsClientFactory(null));

servient.addCredentials(
    {
        "urn:dev:tests": {
            username: "USERNAME",
            password: "PASSWORD"
        }
    });

td = JSON.parse("here is my td I didn't paste it")

try{

    servient.start().then((WoT) => {

        WoT.consume(td).then((thing) => {
            //get the power, energy average, relay state and temperature
            thing.readProperty("temperature").then((s) => {
                console.log("Temperature is ", s);
            });
        });
    });
}
catch (err){
    console.log(err)
}

Here is the errors:
[core/servient] Servient storing credentials for 'urn:dev:tests'
[td-tools/td-parser] parseTD() parsing
```
{"id":"https://domos.oiken.ch/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1","@context":["https://www.w3.org/2019/wot/td/v1",{"dCO_PoC":"http://www.domos-project.eu/dCO_PoC/0.0.1#"},{"@language":"en"}],"@type":"d
CO_PoC:AmbientSensor","located-in":[{"house":"dCO_PoC:House169","demo_site":"dCO_PoC:Sion","label":"The SolarPanelsMeter is located in the House169 of the Sion Demo site"}],"title":"Ambient Sensor","description":"The ambient temper
ature sensor TD for the house 169","base":"https://domos.oiken.ch","securityDefinitions":{"basic":{"scheme":"basic","in":"header"}},"security":["basic"],"properties":{"humidity":{"@type":"dCO_PoC:Humidity","type":"object","properti
es":{"constraint":{"description":"The cloudio constraint","type":"string"},"type":{"description":"The cloudio Type","type":"string"},"timestamp":{"description":"The time of the measure","type":"number"},"value":{"description":"The
humidity","type":"number","unit":"dCO_PoC:Percentage"}},"forms":[{"href":"/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1/relHumidity/datapoint","op":"readproperty","contentType":"application/json"}]},"temperature
":{"@type":"dCO_PoC:Temperature","type":"object","properties":{"constraint":{"description":"The cloudio constraint","type":"string"},"type":{"description":"The cloudio Type","type":"string"},"timestamp":{"description":"The time of
the measure","type":"number"},"value":{"description":"The temperature","type":"number","unit":"dCO_PoC:Celcius"}},"forms":[{"href":"/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1/temperature/datapoint","op":"read
property","contentType":"application/json"}]},"batteryLevel":{"@type":"dCO_PoC:BatteryLevel","type":"object","properties":{"constraint":{"description":"The cloudio constraint","type":"string"},"type":{"description":"The cloudio Typ
e","type":"string"},"timestamp":{"description":"The time of the measure","type":"number"},"value":{"description":"The batteryLevel","type":"number","unit":"dCO_PoC:Percentage"}},"forms":[{"href":"/api/v1/data/7fea01af-ed1d-452e-8a5
e-e9c92eb26b19/ambientSensor-1/batteryLevel/datapoint","op":"readproperty","contentType":"application/json"}]}},"actions":{},"events":{}}
```
[td-tools/td-parser] parseTD() normalizing 'base' into 'forms'
[td-tools/td-parser] parseTDString() applying base 'https://domos.oiken.ch' to '/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1/relHumidity/datapoint'
[td-tools/td-parser] parseTDString() applying base 'https://domos.oiken.ch' to '/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1/temperature/datapoint'
[td-tools/td-parser] parseTDString() applying base 'https://domos.oiken.ch' to '/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1/batteryLevel/datapoint'
[core/wot-impl] WoTImpl consuming TD 'https://domos.oiken.ch/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1' to instantiate ConsumedThing 'Ambient Sensor'
[core/helpers] Helpers found scheme 'https'
[core/consumed-thing] ConsumedThing 'Ambient Sensor' has no client in cache (-1)
[core/servient] Servient checking for 'https' scheme in 1 ClientFactories
[core/servient] Servient creating client for scheme 'https'
[binding-http] HttpsClientFactory creating client for 'https'
[core/consumed-thing] ConsumedThing 'Ambient Sensor' got new client for 'https'
[core/consumed-thing] ConsumedThing 'Ambient Sensor' setting credentials for [HttpClient]
[core/servient] Servient looking up credentials for 'https://domos.oiken.ch/api/v1/data/7fea01af-ed1d-452e-8a5e-e9c92eb26b19/ambientSensor-1' (@deprecated)
(node:6692) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
    at new BasicCredential (C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\binding-http\dist\credential.js:62:27)
    at HttpClient.setSecurity (C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\binding-http\dist\http-client.js:209:35)
    at Object.ConsumedThing.ensureClientSecurity (C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\core\dist\consumed-thing.js:111:20)
    at Object.ConsumedThing.getClientFor (C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\core\dist\consumed-thing.js:157:22)
    at C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\core\dist\consumed-thing.js:172:32
    at new Promise (<anonymous>)
    at Object.ConsumedThing.readProperty (C:\Users\martin.meyer\Documents\domos_wot\node_modules\@node-wot\core\dist\consumed-thing.js:166:16)
    at C:\Users\martin.meyer\Documents\domos_wot\consumer.js:154:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). T
o terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Can you help me please?

**Comment by danielpeintner** [comment]
I am not sure about your "server" side. Is it implemented in node-wot also?

Anyhow, please find a [gist](https://gist.github.com/danielpeintner/09ac53fe43a694302cfb176e7de16f3e) with 2 very simple scripts for server and client with basic authentication.
Note: it is based on the samples in https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-http

Please have a look and let me know whether it resolves the issue.
If you think the [README.md](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/README.md) is not complete or can be improved please let us know also!

**Comment by egekorkan** [comment]
From what I can see, the `id` of the TD and the object in the `addCredentials` method do not match. They must be the same

**Comment by MartinMeyer1** [comment]
@egekorkan Thank you that is the error. All works now
@danielpeintner No the "server" side is a "real" thing
