### ISSUE TITLE
OPC UA Issues

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/thingweb.node-wot#410]
I just used the OPC UA binding and faced some issues:

- if I use a property address like `opc.tcp://localhost:4840/ns=3;s="Case_Lamp_Variable"` the UA binding transforms the address to `opc.tcp://localhost:4840/ns=3;s=%22Case_Lamp_Variable%22`. The node-opcua package is not able to process such kind of string pattern and needs more the '"' character again. A quick fix can be done in extract_params function in opcua-client.ts  
- when I initiated a write property I received an error 'The server does not support writing the combination of value, status and timestamps provided.' . In `writeResource` I had to delate the `sourceTimestamp` and `statusCode` of the `value` variable.
- It seems that in `writeResource` the  UA data type and its corresponding ID is not provided properly (e.g., see [here](https://node-opcua.github.io/api_doc/2.0.0/enums/datatype.html)). 
- Within the `nodeToWrite` in `writeResource` the full `payload` is assigned. However, it should be more `payload.payload`

For my application I found a quick fix, but it should be solved generically.

**Comment by danielpeintner** [comment]
> - if I use a property address like `opc.tcp://localhost:4840/ns=3;s="Case_Lamp_Variable"` the UA binding transforms the address to `opc.tcp://localhost:4840/ns=3;s=%22Case_Lamp_Variable%22`. The node-opcua package is not able to process such kind of string pattern and needs more the '"' character again. A quick fix can be done in extract_params function in opcua-client.ts  

Mhh, the url is encoded, see https://www.urldecoder.org

I still think this is the right process. Hence I wonder whether it is
-  an issue of the node-opcua package and we should report it or
- we should simply url-decode before passing it to the library.

Any thoughts?

With regards to the other aspects. Who is able to work on the OPCUA aspects?

**Comment by lukesmolo** [comment]
Hi guys, thank you for reporting the problems you encountered. I made some fixes and I am going to make a PR.
Regarding the four points:

- I added a _decode_ operation inside the extract_params function, so we are sure that the string is passed as decoded to the library. I added some tests for this
- for the moment I removed the **timestamp** and **statusCode** values from the payload. I guess they should become optional as soon as the form will accept it
- I made a fix and added some further tests on purpose
- I made a fix

Please let me know if something else should be fixed/improved.

**Comment by sebastiankb** [comment]
>for the moment I removed the timestamp and statusCode values from the payload. I guess this depends on the specific opcua server. These fields should become optional as soon as the form will accept it

This is an interesting statement where maybe the TD can help here to define what the server expect. 

That are details which we should discuss together with the OPCF.

**Comment by danielpeintner** [comment]
The actual issue has been solved by PR https://github.com/eclipse/thingweb.node-wot/pull/433.

@sebastiankb do you want to keep the issue open due keep track of `timestamp` and `statusCode` discussion?

**Comment by relu91** [comment]
I would close this one and add a dedicated issue for `timestamp`and `statusCode`. It will help us when trying to find it in the future.

**Comment by danielpeintner** [comment]
created https://github.com/eclipse/thingweb.node-wot/issues/444
