### ISSUE TITLE
Actions with `const` inputs

### ISSUE THREAD

**Issue by JKRhb** [eclipse/thingweb.node-wot#412]
I recently tried to model the possible actions of a legacy device that use the same `href` but differ in their payload which indicates the intended action. I tried to use a `const` value for this like so:

```json
"actions": {
    "toggle": {
        "input": {
            "const": "toggle"
        },
        "forms": {
            "href": "tigger/actions"
        }
    },
    "blink": {
        "input": {
            "const": "blink"
        },
        "forms": {
            "href": "tigger/actions"
        }
    }
}
```

Consuming these actions as part of a TD with `node-wot`, however, does not have an effect on the behavior of the `ConsumedThing`, i.&nbsp;e. the `const` value is neither assumed as the (unchangeable) default nor used for an assertion of the actual input.

Do you think one of these two options should be added to `ConsumedThing`? Or should the user be free to use any input they like while the assertion is only performed by the actual thing?

**Comment by danielpeintner** [comment]
At the moment node-wot does not really check any JSON schema constraints (there is not even a JSON schema library used).

I agree, a proper validation (that would also kick-in `const`s) is desirable. 
There is a related issues for that, see https://github.com/eclipse/thingweb.node-wot/issues/332.

**Comment by relu91** [comment]
Btw in `0.8.x` we have started working on proper validation. In any case, I would use the schema just as validation not as a way to infer the default values of input. (FYI: JsonSchema has also the `default` keyword but as I understood it is not consistently implemented in the processors)

**Comment by egekorkan** [comment]
Regarding default, it is not implemented by validators since it is not used for validation, similar to readOnly, writeOnly, description and title. It can be used by data and UI generators though. A VS-Code plug-in for node-wot can do this for example :)

**Comment by danielpeintner** [comment]
I don't think there is any plan to add `const` values in data (payload), right?
Shall we close the issue?

**Comment by relu91** [comment]
+1 for closing as "won't implement".
