### ISSUE TITLE
wot-typescript-definitions update hell

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#420]
I wanted to update `wot-typescript-definitions` from version `0.8.0-SNAPSHOT.11`  to `0.8.0-SNAPSHOT.12` (see https://github.com/eclipse/thingweb.node-wot/pull/419).

Unfortunately that is no longer easy with `package-lock.json` files.

There is no automatic update even in case of issues like in this specific case.

```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with npm install before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's wot-typescript-definitions@0.8.0-SNAPSHOT.11 does not satisfy wot-typescript-definitions@0.8.0-SNAPSHOT.12
```

The way I solved it was to walk into each directory with `wot-typescript-definitions` and call
`npm install wot-typescript-definitions`

This updates the `package-lock.json` files in most of the cases.
There is no call in root that can do that I think. Am I wrong?

Moreover, for binding-http this approach does *NOT* work.. and one has to copy around stuff like the following snippets to several places and fix the version also..

```
		"wot-typescript-definitions": {
			"version": "0.8.0-SNAPSHOT.12",
			"resolved": "https://registry.npmjs.org/wot-typescript-definitions/-/wot-typescript-definitions-0.8.0-SNAPSHOT.12.tgz",
			"integrity": "sha512-W+meBiG7G3tKbxEi+S/mkdaGt2EVn4hrdWNKTbxmPkyxj+dAF7jd38QV/YOQ9mUmRso4YGNquE0zESdDmIuo3g=="
		},
```

I had to fix the lock files for mqtt and opcua also manually.

Moreover, .. the order of dependencies after `npm install wot-typescript-definitions` is different.. which I usually do not want... so I have to fix that again manually...

I don't know but someone needs to tell me how to do this better. . this is not practical at all. Without `package-lock.json` it was easy... updating the version in each `package.json` file and done.

I am more and more leading towards removing `package-lock.json` files again :-(

**Comment by egekorkan** [comment]
So regarding removing lock files or not and using them or not, those are two things to decide on in my opinion. Submitting lock files allow GitHub bots to find issues and also to make sure that a certain version was working with given dependencies. Ideally, in local environments during development, we would work with `package.json` and then submit the changes. If no one changes the lock files, they lose their purpose as well.

**Comment by relu91** [comment]
One note, in #430 I wrote down this comment about install dependencies with lockfiles:
> By the way, we should encourage committers to install new packages using lerna add <package> --scope @node-wot/<subpackage> it should cause fewer troubles.

Maybe this solves the issues described above using just `npm install`, if that so we should definitely add this info to the README (also as a reminder for ourselves)

**Comment by danielpeintner** [comment]
> > By the way, we should encourage committers to install new packages using lerna add  --scope @node-wot/ it should cause fewer troubles.
> 
> Maybe this solves the issues described above using just `npm install`, if that so we should definitely add this info to the README (also as a reminder for ourselves)

I will try next time and let you know! Let's hope so...

**Comment by relu91** [comment]
> One note, in #430 I wrote down this comment about install dependencies with lockfiles:
> 
> > By the way, we should encourage committers to install new packages using lerna add  --scope @node-wot/ it should cause fewer troubles.
> 
> Maybe this solves the issues described above using just `npm install`, if that so we should definitely add this info to the README (also as a reminder for ourselves)

I've tried this approach in different new PRs it seems to work. @danielpeintner did you try it?

**Comment by danielpeintner** [comment]
In https://github.com/eclipse/thingweb.node-wot/pull/454 I simply updated the local version.
Will try next time... I hope I don't forget again 🙈

**Comment by danielpeintner** [comment]
Note: I think `npm install` works for published repositories only. Next time we update `wot-typescript-definitions` I will give it a try

**Comment by JKRhb** [comment]
I don't know if it works for a nested package structure but maybe setting up [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) could be a solution for updating the dependencies automatically. I could try it out and provide a PR if you're interested :)

**Comment by danielpeintner** [comment]
A more automatic approach is desirable 👍 

Having said that, I think [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates) works with pointing to the *latest* version.

Here the issue is that we are trying to update all *local* versions. The packages are not published yet and only available locally.

I might be wrong though.

**Comment by danielpeintner** [comment]
solved by now using `npm workspaces` and a *new* way to handle (and check) dependencies
