### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by JKRhb** [eclipse/thingweb.node-wot#430]
Is there are roadmap for releasing a new version of node-wot (e. g. 0.7.6)?

**Comment by relu91** [comment]
I've looked into the commit history we have collected some minor fixes. So I don't mind publishing a 0.7.6. @danielpeintner has the final word here so let's wait for his input.

**Comment by danielpeintner** [comment]
The [changes](https://github.com/eclipse/thingweb.node-wot/compare/v0.7.5...master) are not big but still useful. 

I will try to publish `v0.7.6` soon...

The next efforts should go into `v0.8.x` though

**Comment by danielpeintner** [comment]
[v0.7.6](https://github.com/eclipse/thingweb.node-wot/releases/tag/v0.7.6) has been published and should appear _soon_ on NPM.
