### ISSUE TITLE
How can i stop a servient? - Error on shutdown with MQTT binding

### ISSUE THREAD

**Issue by alvarogar23** [eclipse/thingweb.node-wot#431]
I am trying to stop my servient with the following function:

`servient.shutdown()`

but it throws the following error:

`(node:10160) UnhandledPromiseRejectionWarning: TypeError: _this.broker.stop is not a function
    at C:\Users\alvar\Desktop\Servient\node_modules\@node-wot\binding-mqtt\dist\mqtt-broker-server.js:244:26
    at new Promise (<anonymous>)
    at MqttBrokerServer.stop (C:\Users\alvar\Desktop\Servient\node_modules\@node-wot\binding-mqtt\dist\mqtt-broker-server.js:241:16)
    at C:\Users\alvar\Desktop\Servient\node_modules\@node-wot\core\dist\servient.js:212:64
    at Array.forEach (<anonymous>)
    at Servient.shutdown (C:\Users\alvar\Desktop\Servient\node_modules\@node-wot\core\dist\servient.js:212:22)
    at C:\Users\alvar\Desktop\Servient\air.js:174:22
    at Layer.handle [as handle_request] (C:\Users\alvar\Desktop\Servient\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\alvar\Desktop\Servient\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\alvar\Desktop\Servient\node_modules\express\lib\router\route.js:112:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

So my question is, what is the right way to stop the servient from running?
Thanks in advance.

**Comment by egekorkan** [comment]
Normally it should be via the destroy method (https://w3c.github.io/wot-scripting-api/#the-destroy-method). However, it is not implemented yet

**Comment by alvarogar23** [comment]
@egekorkan thank you very much, i was so confused when trying to execute that method.

**Comment by relu91** [comment]
> Normally it should be via the destroy method (https://w3c.github.io/wot-scripting-api/#the-destroy-method). However, it is not implemented yet

Just to be precise the destroy method does not stop the servient but as single WebThing. So suppose you expose N WebThings in your application, you can call the destroy method on one of them. The end result will be that you'll have N-1 active exposed WebThings. 

The correct method to completely stop the servient is the one you're using. So taking the previous example if you call `servient.shutdown()` the servient will stop all the active web things and exit. The end result here is that you'll have 0 WebThings and application exit. 

I think that the error you posted above is a bug and we should fix it

**Comment by relu91** [comment]
I've just renamed the issue for bookeeping 👍🏻

**Comment by danielpeintner** [comment]
I looked into that issue a bit and I think the `ProtocolServer` interface needs an extension.

https://github.com/eclipse/thingweb.node-wot/blob/de006242c79a35f1fecc0e756d31d369b5928bf9/packages/core/src/protocol-interfaces.ts#L55-L61

Besides an `expose(...)` call we need to have a way to report to the protocol to shut-down a certain thing a la `destroy(thingId: string)`.
Any opinion?

Of course, in the case of a exposedThing.destroy() we need to fill the destroy method with functionality i.e., to walk over all bindings and remove the thing....
https://github.com/eclipse/thingweb.node-wot/blob/de006242c79a35f1fecc0e756d31d369b5928bf9/packages/core/src/exposed-thing.ts#L109-L113

**Question**: Is it okay for everybody to create `destroy(thingId: string)` in `ProtocolServer` ?
Other proposals/comments?

**Comment by relu91** [comment]
> Question: Is it okay for everybody to create destroy(thingId: string) in ProtocolServer ?

Yes, I support the addition. And regarding our offline discussion, I would say that this change could be implemented in 0.7.x it is a sort of a _fix_ plus it does not mess with the new features implemented in 0.8.x (i.e., it is just a new method not a refactoring of the protocol interface).

**Comment by danielpeintner** [comment]
I started https://github.com/eclipse/thingweb.node-wot/pull/438 to work on ...
