### ISSUE TITLE
Browser HTTPS invokeAction body is missing

### ISSUE THREAD

**Issue by LennyHEVS** [eclipse/thingweb.node-wot#437]
So I'm trying to write a simple Javascript web application using the browser bundle and when I try to `POST` something with a body, the thing doesn't receive any body. The request has done by the consumed thing has a `content-lengh` of zero.
```Javascript
// create Servient, add needed credentials and setup HTTPS configuration
let servient = new Wot.Core.Servient();
servient.addCredentials(
	{
		"urn:dev:org:wot-thing": {
			clientId: "theID",
			clientSecret: "theSecret"
		}
	}
);
let httpsConfig = {
    allowSelfSigned: true, // client configuration
};
servient.addClientFactory(new Wot.Http.HttpsClientFactory(httpsConfig));
let wotHelper = new Wot.Core.Helpers(servient);


$(document).ready(function() {
	wotHelper.fetch("https://localhost:443").then(async (td) => {
		servient.start().then((factory) => {
			factory.consume(td).then((thing) => {
				
				let stringBody= '{"string": "someString"}';
				
				thing.invokeAction("postString",JSON.parse(stringBody)).then((res) => {
					console.log("Result:",res);
				});
			});
		});
	});
});
```
The Thing that I'm using uses HTTPS with the flow `client-crendentials` of the `oauth2` security scheme
If I re-write this code in a Node application it works fine. But with the web app the `stringBody` is not there.

This is what I'm receiving
```
Request!
        Method:  POST
        URL:  /postString
        Variables:  URLSearchParams {}
Data:  undefined
Params:  { uriVariables: {} }
```
I tried to follow the request in the browser-bundle library and in the Typescript library but I don't find the source of the problem.
The `request` returned by `generateFetchRequest` in the `http-client` file seems to have a key "bodyUsed" set to false at some point.

Thanks for the help already !

**Comment by relu91** [comment]
If it works in a Nodejs environment it might be a translation problem of `browserify`. Can I ask you to verify if the issue occurs even without HTTPS and the security scheme? Knowing this would help to pinpoint the issue 👍🏻

**Comment by LennyHEVS** [comment]
I tried removing the security scheme (using `nosec`) still using HTTPS and the data is transferred correctly. The issue doesn't occur in this case
