### ISSUE TITLE
[question] Is there any servient for browser ? (pure client in fact, build according a Thing Description)

### ISSUE THREAD

**Issue by franckOL** [eclipse/thingweb.node-wot#44]

**Comment by mkovatsc** [comment]
We know that other participants in the W3C WoT WG have such an implementation, but did not make it public.

If someone has time, we would definitely add such an implementation to Eclipse Thingweb.

**Comment by wiresio** [comment]
Since version 0.6.1 there is a browser bundle of node-wot implementing core functionality, TD parsing, and http client binding. This provides the functionality of using the WoT Scripting API within a web page.
