### ISSUE TITLE
[OPC UA] Removed timestamp and statusCode values from payload

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#444]
see https://github.com/eclipse/thingweb.node-wot/issues/410#issuecomment-881283506

**Comment by danielpeintner** [comment]
Is this issue still relevant?
@lukesmolo @erossignon

**Comment by erossignon** [comment]
This isssue is not relevant anymore with the revamped binding-opcua 
By default opcua things are exposed as raw value without statuscode nor timestamp to represent the lowest level of data that is commonly used with things property. Some codec mechanisms exist to expose either Variant or DataValue for advanced use only (see unit test for example of use)
