### ISSUE TITLE
Problem with OAuth2.0

### ISSUE THREAD

**Issue by alvarogar23** [eclipse/thingweb.node-wot#445]
Hello guys. I am trying to implement OAuth2.0 security in my Servients and I have started by testing the example that is uploaded, I have changed some things of the TD but I think that nothing important, the problem is that the consumer doesn.t get the token to execute the action because I think that the clientID is missing, I attach the files with my changes. The file "memory-model" haven't been touched.

PD: Can I implement the OAuth2.0 with this same configuration of the uploaded example in my MQTT project? And if not, how could I secure the communication of Servients if I use MQTT protocol to interact between them?

Thanks in advance!

Exposer.js

```

let td = {
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "OAuth",
    "id": "urn:dev:wot:oauth:test",
    "securityDefinitions": {
        "oauth2_sc": {
            "scheme": "oauth2",
            "flow": "client_credentials",
            "authorization": "https://example.com/authorization",
            "token": "https://localhost:3000/token",
            "scopes": [
                "limited",
                "special"
            ]
        }
    },
    "security": [
        "oauth2_sc"
    ],
    "actions": {
        "sayOk": {
            "description": "A simple action protected with oauth",
            "idempotent": true
        }
    }
};

const Servient = require('@node-wot/core').Servient;
const HttpServer = require('@node-wot/binding-http').HttpServer;

const servient = new Servient();
servient.addServer(new HttpServer());

servient.start().then((WoT) => {
    try {
        WoT.produce(td).then((thing) => {
            thing.setActionHandler("sayOk", async () => "Ok!");
            thing.expose();
        });
    }
    catch (err) {
        console.error("Script error: " + err);
    }
});


```

Consumer.js

```

const { Servient, Helpers } = require("@node-wot/core");
const { HttpClientFactory } = require('@node-wot/binding-http');

const servient = new Servient();
servient.addClientFactory(new HttpClientFactory(null));
const WoTHelpers = new Helpers(servient);

let td = {
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "title": "OAuth",
    "id": "urn:dev:wot:oauth:test",
    "securityDefinitions": {
        "oauth2_sc": {
            "scheme": "oauth2",
            "flow": "client_credentials",
            "authorization": "https://example.com/authorization",
            "token": "https://localhost:3000/token",
            "scopes": [
                "limited",
                "special"
            ]
        }
    },
    "security": [
        "oauth2_sc"
    ],
    "actions": {
        "sayOk": {
            "description": "A simple action protected with oauth",
            "idempotent": true,
            "forms": [{"href": "http://localhost:8080/oauth/actions/sayOk"}]
        }
    }
};

WoTHelpers.fetch("http://localhost:8080/oauth").then(td => {
    try {
        servient.start().then(async (WoT) => {
            WoT.consume(td).then(async (thing) => {
    
                try {
                    const result = await thing.invokeAction("sayOk");
                    console.log("oAuth token was", result);
                }
                catch (error) {
                    console.log("It seems that I couldn't access the resource");
                }
            });
        });
    }
    catch (err) {
        console.error("Script error:", err);
    }
}).catch((err) => { console.error("Fetch error:", err); });

```

This is the output when executing the consumer

```
[core/wot-impl] WoTImpl consuming TD 'urn:dev:wot:oauth:test' to instantiate ConsumedThing 'OAuth'
[core/helpers] Helpers found scheme 'http'
[core/consumed-thing] ConsumedThing 'OAuth' has no client in cache (-1)
[core/servient] Servient checking for 'http' scheme in 1 ClientFactories
[core/servient] Servient creating client for scheme 'http'
[binding-http] HttpClientFactory creating client for 'http'
[core/consumed-thing] ConsumedThing 'OAuth' got new client for 'http'
[core/consumed-thing] ConsumedThing 'OAuth' setting credentials for [HttpClient]
[core/servient] Servient looking up credentials for 'urn:dev:wot:oauth:test' (@deprecated)
It seems that I couldn't access the resource
```

The consumer gets to communicate with the exposer

```
[binding-http] HttpServer on port 8080 received 'GET /oauth' from [::ffff:127.0.0.1]:55380
[binding-http] HttpServer on port 8080 replied with '200' to [::ffff:127.0.0.1]:55380
[binding-http] HttpServer on port 8080 received 'GET /oauth' from [::ffff:127.0.0.1]:58503
[binding-http] HttpServer on port 8080 replied with '200' to [::ffff:127.0.0.1]:58503
[binding-http] HttpServer on port 8080 received 'GET /oauth' from [::ffff:127.0.0.1]:58571
[binding-http] HttpServer on port 8080 replied with '200' to [::ffff:127.0.0.1]:58571
```

**Comment by LennyHEVS** [comment]
>  because I think that the clientID is missing

Yes exactly to add your clientID and your clientSecret needed for the client_credentials flow of OAuth2 you need to add these lines after `servient.addClientFactory(new HttpClientFactory(null));`
```Javascript
servient.addCredentials({
	"urn:dev:wot:oauth:test": {
		clientId: "admin",
		clientSecret: "admin"
	}
});
```

As for the MQTT question, I think there is no usable security schemes yet. But I'll let another person more knowledgeable on the state of the MQTT binding answer that question.

**Comment by relu91** [comment]
> Hello guys. I am trying to implement OAuth2.0 security in my Servients and I have started by testing the example that is uploaded, I have changed some things of the TD but I think that nothing important, the problem is that the consumer doesn.t get the token to execute the action because I think that the clientID is missing, I attach the files with my changes. The file "memory-model" haven't been touched.

Just to be sure have you started the sample OAuth 2.0 server: ` npm run server` ? 

> PD: Can I implement the OAuth2.0 with this same configuration of the uploaded example in my MQTT project? And if not, how could I secure the communication of Servients if I use MQTT protocol to interact between them?

About this MQTT uses different schemes, usually username and password (check [the readme](https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-mqtt#more-examples) )

**Comment by alvarogar23** [comment]
@relu91 yes, I started the server with that command

**Comment by relu91** [comment]
No problem! 

> And about the part of the MQTT security I assume that the following code must be in the TD.

Actually, it should be in the servient.conf.json of the client. As noted in the readme that I linked.

**Comment by alvarogar23** [comment]
Yes but in the readme I think it is explained if you have it installed as a Standalone application, I have installed it as node dependency and I think I have to change the mqtt-broker.server.js values of the following function:

```
function MqttBrokerServer(uri, user, psw, clientId, protocolVersion) {
        this.scheme = "mqtt";
        this.port = -1;
        this.address = undefined;
        this.user = undefined;
        this.psw = undefined;
        this.clientId = undefined;
        this.protocolVersion = undefined;
        this.brokerURI = undefined;
        this.things = new Map();
        if (uri !== undefined) {
            if (uri.indexOf("://") == -1) {
                uri = this.scheme + "://" + uri;
            }
            this.brokerURI = uri;
        }
        if (user !== undefined) {
            this.user = user;
        }
        if (psw !== undefined) {
            this.psw = psw;
        }
        if (clientId !== undefined) {
            this.clientId = clientId;
        }
        if (protocolVersion !== undefined) {
            this.protocolVersion = protocolVersion;
        }
    }
```

**Comment by alvarogar23** [comment]
I have tested what I have put in the previous message and it seems like it doesn´t work when changing this.client variable in mqtt-client.js. And if that varaible is not touched the Servients do communicate between them but I thnk it still not secured because I can change values using Postman application without indicating any username or password.

**Comment by relu91** [comment]
Ah, I see, maybe @egekorkan can help you here. In theory, you should be able to configure the bindings from code to (i.e., without the servient.conf.json) but I don't know the situation of the mqtt binding. 

>  And if that varaible is not touched the Servients do communicate between them but I thnk it still not secured because I can change values using Postman application without indicating any username or password.

Does Postman support MQTT now? 🤔

**Comment by egekorkan** [comment]
So first of all, you shouldn't specify security configuration in the thing but in the servient configuration. For the case of MQTT, it is done the way shown at https://github.com/eclipse/thingweb.node-wot/tree/master/packages/binding-mqtt#more-examples . That config can be also inserted when you create an MQTT binding, i.e. when you do `servient.addServer(new MqttBrokerServer("mqtt://test.mosquitto.org"));`

**Comment by relu91** [comment]
@alvarogar23 is this issue solved? the title is about OAuth2.0 but the conversation went to MQTT security configuration. Should we close this one and open a dedicated issue?

**Comment by alvarogar23** [comment]
@relu91 Yes this is solved, you can close this if you want
