### ISSUE TITLE
Sort NPM dependencies alphabetically

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#450]
It seems NPM likes to sort NPM dependencies alphabetically.

Hence, every time a *new* dependency is added it sort all the other dependencies  also which causes unnecessary diffs. 

see https://github.com/eclipse/thingweb.node-wot/pull/449/files#r678638895

**Comment by maxim-s-barabash** [comment]
npm will sort the dependencies once. Next Do not edit package.json dependencies manually and everything will be fine.

**Comment by relu91** [comment]
> Next Do not edit package.json dependencies manually and everything will be fine.

That's what I usually do, but I don't know how it was done before... since in 0.8.x I re-inited every package with `npm init -w _package_name`, it should be solved there...

**Comment by danielpeintner** [comment]
Solved by now.
