### ISSUE TITLE
Keeping Copyright Years up-to-date

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#464]
This is a a _very_ minor issue but I thought I bring it up.

We have many (if not all) source files with a copyright header that are very much outdated.

e.g., https://github.com/eclipse/thingweb.node-wot/blob/575f30c639a5d4f790b3e65953c94d9c8b319f6b/packages/binding-coap/src/coap-client-factory.ts#L2

The file was last changed in 2020!

The original idea is to have at least one date (the year the file was created) and maybe a second year that indicates the last change. We have not being updating this regularly...

Moreover, I do not really see any real benefit of having it in the first place. Some projects are very picky about that.

I am inclined to say "removing all dates would be the best" 🙉
IF we can have some kind of script/tool that does it for use I am ok to keeping it as long as we just need to run the tool once in a while... (any experience with https://github.com/marketplace/actions/update-license-copyright-year-s or others)

Any opinion in general?

**Comment by relu91** [comment]
I am ok keeping _only if_ we can automate the process. Since is something that needs to be done sporadically it also means that people will forget about it. I would support setting up the Github action above.

**Comment by egekorkan** [comment]
Is this not a rule set by Eclipse that the information should be provided in a specific format? I have checked another eclipse project and they also have old dates (https://github.com/eclipse/ditto/blob/master/base/model/src/main/java/org/eclipse/ditto/base/model/common/AbstractIdValidator.java).

I would say that we should use the actions to automate it :)

**Comment by danielpeintner** [comment]
I am not familiar with the GitHub action project I linked and I believe we might need more fixes.

Hence I wrote a very simple script (or rather Java class) that walks over all files and takes a look at the "git log" history.
see https://github.com/eclipse/thingweb.node-wot/pull/465 for the result.

What I also found are files that do not even have a copyright header.
My take is that any .ts file in `/src` should have one.. I don't think `/test` files need it.

The mini utility tool can help to spot those cases also and fix them.
We can run the script at any time (most likely once a year or so)...

**Comment by danielpeintner** [comment]
Note: I noticed a minor issue... we need to run the script in late December... otherwise we add a git log history for the upcoming year ;-)

**Comment by danielpeintner** [comment]
This is the list of files that does *not* have any license..

\examples\servients\modbus-cli\src\test-modbus-server.ts
\examples\templates\exposed-thing\src\base.ts
\packages\binding-modbus\src\modbus-client-factory.ts
\packages\binding-modbus\src\modbus-client.ts
\packages\binding-modbus\src\modbus-connection.ts
\packages\binding-modbus\src\modbus.ts
\packages\binding-modbus\src\utils.ts
\packages\binding-netconf\src\async-node-netconf.ts
\packages\binding-netconf\src\xpath2json.ts
\packages\examples\src\proxy-scripts\festo-fake.ts
\packages\examples\src\proxy-scripts\festo-live.ts
