### ISSUE TITLE
consumed thing. not support Security definitions activated at the form

### ISSUE THREAD

**Issue by maxim-s-barabash** [eclipse/thingweb.node-wot#466]
**expected behavior**
Security definitions MAY also be activated at the form level by including a security member in form objects, which overrides (i.e., completely replace) all definitions activated at the Thing level.

```json
"forms": [
    {
         "href": "https://example.com/",
        "security": ["apikey_x", "apikey_y"]
    }
]
```

**what at the moment**
only the field is used  at the Thing level. form level ignored.

Link on related code https://github.com/eclipse/thingweb.node-wot/blob/ed18712144b5ac1d78a2cb717946fe261d8020b7/packages/core/src/consumed-thing.ts#L124

**doc**
https://www.w3.org/TR/wot-thing-description/#security-serialization-json
> Security configuration in the TD is mandatory. At least one security definition MUST be activated through the security array at the Thing level (i.e., in the TD root object). This configuration can be seen as the default security mechanism required to interact with the Thing. Security definitions MAY also be activated at the form level by including a security member in form objects, which overrides (i.e., completely replace) all definitions activated at the Thing level.

**Comment by danielpeintner** [comment]
You are correct, security at form level is not supported yet.

We will try to work on that. IF you are willing to work on a PR please let us know.

**Comment by danielpeintner** [comment]
@maxim-s-barabash I think the fix is rather simple, see https://github.com/eclipse/thingweb.node-wot/pull/467

Unfortunately I do not have have time to actually test it properly the next days.
If you can do so in the meantime and report back it would be great.

**Comment by maxim-s-barabash** [comment]
@danielpeintner, thanks. I think this will work.
