### ISSUE TITLE
Proposal to use TD.SecurityType instead of TD.SecurityScheme

### ISSUE THREAD

**Issue by maxim-s-barabash** [eclipse/thingweb.node-wot#469]
That would be a more accurate description

https://github.com/eclipse/thingweb.node-wot/blob/56bbc544e964b369c1bdb57be540e96662c13114/packages/core/src/exposed-thing.ts#L30

```diff
-    securityDefinitions: { [key: string]: TD.SecurityScheme };
+    securityDefinitions: { [key: string]: TD.SecurityType };
```    

```
export interface SecurityScheme {
    scheme: string;
    description?: string;
    proxy?: string;
}
```
does not allow manipulation with
```
export interface BearerSecurityScheme extends SecurityScheme {
    scheme: "bearer";
    in?: string;
    alg?: string;
    format?: string;
    name?: string;
    authorization?: string;
}
```

And further on the code:

https://github.com/eclipse/thingweb.node-wot/blob/74fe2a09d0252c57e66eeb731f35bb77f6a4cfb6/packages/td-tools/src/thing-description.ts#L41

https://github.com/eclipse/thingweb.node-wot/blob/56bbc544e964b369c1bdb57be540e96662c13114/packages/binding-http/src/http.ts#L36

https://github.com/eclipse/thingweb.node-wot/search?p=1&q=SecurityScheme

What do you think about this?

**Comment by danielpeintner** [comment]
The `master` branch is a little bit _behind_ and we plan to move to [`v0.8.x`](https://github.com/eclipse/thingweb.node-wot/tree/v0.8.x) soon.

The following should be a better match. 
https://github.com/eclipse/thingweb.node-wot/blob/97ea2b06a29db95e7d8201ae4d788780a8b4abec/packages/core/src/exposed-thing.ts#L32

Do you agree? Further improvements might be still needed...

**Comment by maxim-s-barabash** [comment]
Thanks. now I will be looking into a new branch.
