### ISSUE TITLE
Сlarify write error message on exposed-thing.writeMultipleProperties

### ISSUE THREAD

**Issue by maxim-s-barabash** [eclipse/thingweb.node-wot#470]
v0.8.x

Now we have error text similar to
```
 Error: ExposedThing 'ThingTitle', failed to read properties [object Object]
```
There is a semantic error in the current code. **read -> write**

https://github.com/eclipse/thingweb.node-wot/blob/v0.8.x/packages/core/src/exposed-thing.ts#L391
```diff
    writeMultipleProperties(valueMap: WoT.PropertyWriteMap, options?: WoT.InteractionOptions): Promise<void> 
...
      .catch(err => {
-          reject(new Error(`ExposedThing '${this.title}', failed to read properties ` + valueMap));
+          reject(new Error(`ExposedThing '${this.title}', failed write multiple properties. ${err.message}`));
      });
```

PS: Am I posting these minor issues. Is this acceptable?

**Comment by relu91** [comment]
> PS: Am I posting these minor issues. Is this acceptable?

Yes, IMHO these are the trickiest things to notice. So thank you for reporting this here. If you are willing to contribute further, PRs are always welcomed.

**Comment by danielpeintner** [comment]
@maxim-s-barabash do you want to provide a PR resolving the issue?

**Comment by maxim-s-barabash** [comment]
At the moment I want to limit myself to posting issues.

**Comment by danielpeintner** [comment]
> At the moment I want to limit myself to posting issues.

No problem. Please take a look at https://github.com/eclipse/thingweb.node-wot/pull/472
