### ISSUE TITLE
[binding-http] missing typescript types for node-fetch dependency

### ISSUE THREAD

**Issue by miguelrk** [eclipse/thingweb.node-wot#471]
Hello everybody!

**Problem:** I am trying to deploy an application with **@node-wot/binding-http** as dependency to Heroku, the build is however failing due to node-fetch missing types:

```log
node_modules/@node-wot/binding-http/dist/credential.d.ts(3,25): error TS7016: Could not find a declaration file for module 'node-fetch'. '/tmp/build_375c4a13/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
         Try `npm i --save-dev @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`
       npm ERR! code 2
       npm ERR! path /tmp/build_375c4a13
       npm ERR! command failed
       npm ERR! command sh -c npm run compile
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.rmIFW/_logs/2021-08-22T08_05_54_603Z-debug.log
-----> Build failed
```

This is coming from `node_modules/@node-wot/binding-http/dist/credential.d.ts(3,25)` with the line 
```javascript
import { Request } from 'node-fetch';
```

The easy workaround of manually editing this file (e.g. add an explicit any type) does not work, as edits won't be available in production when Heroku does a clean `npm install` from package.json.

**NOTE:** Since node-fetch 3.x [types are bundled with node-fetch](https://github.com/node-fetch/node-fetch#typescript), so you don't need to install any additional packages.

---

**Proposed Solutions:** 
1) upgrade node-fetch dependency to latest (v3.0.0-beta.10). Since v3.x is an ESM only package, it might require other changes in the codebase.
2) install official types: `npm install --save-dev @types/node-fetch` 

I would go with 2 for now. Is this possible? Thanks a lot!

**Comment by relu91** [comment]
it's odd cause if you check http-binding package json `node-fetch` types are already there. Are you sure that you did the usual bootstrapping procedure?🤔

**Comment by miguelrk** [comment]
Thanks for the quick response @relu91! You're right, `@types/node-fetch` is already in `package.json`, I somehow missed this. 
I tried purging heroku cache to no success, it 

I am installing the packages as usual via `npm install` only, is [this](https://github.com/eclipse/thingweb.node-wot#as-a-standalone-application) the necessary botstrapping procedure you are reffering to? I don't see how I would need additional build steps when using `npm install`, the `/dist` folder under `node_modules/@node-wot/<package>` is already present for all packages. It might be something Heroku related, as this works in my local development setup (the types are also missing, but the build does not fail).

**Comment by miguelrk** [comment]
Update: I could not find the root of the issue. After stumbling for a while I settled on simply installing `@types/node-fetch` on the root of my project, which got it working.

Thanks again for the help! Feel free to close this issue 👍🏼

**Comment by relu91** [comment]
> I am installing the packages as usual via npm install only, is this the necessary botstrapping procedure you are reffering to? I don't see how I would need additional build steps when using npm install, the /dist folder under node_modules/@node-wot/<package> is already present for all packages.

That's right you don't need anything more. Sorry, I thought you were trying to build node-wot from source :). 

> Update: I could not find the root of the issue. After trying multiple things for a while I settled on simply installing @types/node-fetch on the root of my project, which got it working.

I'm glad that you make it works! I'd keep the issue open cause I want to be sure that's not some misconfiguration from our side. Let's see if some else faces the same problem in different environments.

**Comment by danielpeintner** [comment]
It seems we can close the issue by now, right @relu91 ?

**Comment by relu91** [comment]
It should but we'll know for sure only once we publish 0.8.0. I would close it, but feel free to open it again if 0.8.0 still doesn't work.
