### ISSUE TITLE
MBus tests failing

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#475]
see  https://github.com/eclipse/thingweb.node-wot/pull/473/checks?check_run_id=3433642871

2 failing tests

```

  1) MBus connection
       should throw for unknown host:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/thingweb.node-wot/thingweb.node-wot/packages/binding-mbus/test/mbus-connection-test.ts)
  

  2) MBus connection
       Operation
         should fail for unknown host:
     Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/thingweb.node-wot/thingweb.node-wot/packages/binding-mbus/test/mbus-connection-test.ts)
```

My first attempt was to increase timeout to 10 secs since I saw locally 2 seconds.
Note: Locally the tests run stable and fine on my machine.

Anyhow, not sure what is causing these issues, i skipped the failings tests, see https://github.com/eclipse/thingweb.node-wot/pull/474

@LennyHEVS can you take a look?

**Comment by LennyHEVS** [comment]
I modified the connection test file in the PR #504 . I'm not sure if this is going to work or not.
I'd like to see the result of the tests to be sure of the fix.
