### ISSUE TITLE
No matching format found error when sending CoAP GET

### ISSUE THREAD

**Issue by cdh4u** [eclipse/thingweb.node-wot#48]
When I am sending a CoAP GET message, I get the following error:

```
CoapClient sending GET to coap://193.234.219.199:5683/3303/0/5700
/usr/src/app/thingweb.node-wot/packages/binding-coap/node_modules/coap/lib/option_converter.js:143
    throw new Error('No matching format found')
    ^
```

When I am sending the same request with the coap-shell app, everything works.

Below is the response I get with coap-shell:

```
Options: {"Content-Format":"text/plain"}
Status : 205-Reset Content, Payload: 3B
................................... Payload ....................................
8.3
```

I am using the Leshan LWM2M Client (prebuilt) as CoAP server.

(Note that, due to firewalls, the IP address of the CoAP server above is not reachable from the Internet, so you will unfortunately not be able to test it)

**Comment by cdh4u** [comment]
Ok, I found the reason. When looking in Wireshark, the CoAP response indicates a Content-Format value that node-wot does not understand. 

To solve this, the CoAP request sent from node-wot would have to indicate that it accepts text/plain.

**Comment by cdh4u** [comment]
I have the following in my TD:

"forms":[{"href":"coap://193.234.219.199:5683/3303/0/5700","mediaType":"text/plain"}]

But, it does not have any impact on the request.

**Comment by 6d77** [comment]
Just talked to him. There was another CoAP server implementation which could not cope with `Accept` headers, so he removed it to make this working. Until a final solution is found to fit both requirements you might just uncomment the line again locally.

**Comment by cdh4u** [comment]
I think the master branch should be based on endpoints behaving correctly - in this case being able to process the Accept header :)

Anyway, I will see Matthias this weekend, so I can discuss it with him then. Short term I will uncomment the line.

**Comment by danielpeintner** [comment]
The code
`req.setOption("Accept", form.mediaType);`
is activated again.

@cdh4u  Can we close the issue?

**Comment by danielpeintner** [comment]
as mentioned the option is in by default now, see https://github.com/eclipse/thingweb.node-wot/blob/6dad9786152e40f939caa7f63ef1abf1769ef316/packages/binding-coap/src/coap-client.ts#L212
