### ISSUE TITLE
NPM install shows oudated dependencies warnings

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#481]
running `npm install` for `v.0.8.x` shows

```
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
```

We should try to resolve these warnings...

**Comment by egekorkan** [comment]
I don't know where request is used now but we already have node-fetch and request is deprecated as the warning is shown

**Comment by danielpeintner** [comment]
> I don't know where request is used now but we already have node-fetch and request is deprecated as the warning is shown

We use it in:
* HTTP: https://github.com/eclipse/thingweb.node-wot/blob/b3e8535394f04e59edca1c7b506d5056f8a940be/packages/binding-http/package.json#L33
* MQTT: https://github.com/eclipse/thingweb.node-wot/blob/b3e8535394f04e59edca1c7b506d5056f8a940be/packages/binding-mqtt/package.json#L23
* Examples: https://github.com/eclipse/thingweb.node-wot/blob/b3e8535394f04e59edca1c7b506d5056f8a940be/examples/templates/exposed-thing/package.json#L21

and it seems other dependencies seem to refer to it as well

I like the following image very much ;-) 

![grafik](https://user-images.githubusercontent.com/11281461/131514269-9b9dd90e-05b5-463a-8f4e-b250b616e205.png)

**Comment by egekorkan** [comment]
Regarding where it is _used_:
- The example uses it for a normal HTTP request, to register a TD. This is a legit usage.
- HTTP and MQTT have it in their package.json but not in their actual code via import/require statements.

**Comment by relu91** [comment]
I am working on the warnings, some of them are from `wot-firestore`. Our repo is getting havier and havier. We should start thinking about a better contribution procedure... something like webpack or rollup plugins.

**Comment by danielpeintner** [comment]
This is an *old* issue and we need to continuously check for outdated dependencies.
Hence, closing...
