### ISSUE TITLE
Show statistics in README.md

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#484]
Does it make sense to add some statistics in our README like
https://npmstats.org/@node-wot:td-tools

Q: Is there a good way how this can be nicely rendered on GitHub?

**Comment by egekorkan** [comment]
Maybe like this? 

<img alt="npm" src="https://img.shields.io/npm/dw/@node-wot/td-tools">

**Comment by egekorkan** [comment]
I made it with this: https://shields.io/category/downloads

**Comment by relu91** [comment]
I like badges 👍🏻 we can use them and link back to https://npmstats.org/@node-wot:td-tools
