### ISSUE TITLE
Supported NodeJS Version

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#486]
At the moment we do support (and test) node-wot with NodeJS 10+.

I think it is time to lift the minimum requirement, at least for v0.8.x.
Note: LTS versions get updates for 30 months.

I recently setup GitHub actions to test against 14 and 16 only.
I think having less variations is better. Version 17 is coming soon and even 16 will become LTS soon.

Question: Do we still need to support 12 or can we be more restrictive? Any option?

**Comment by maxim-s-barabash** [comment]
for me 14 and up

**Comment by relu91** [comment]
Thank you for creating this issue. In principle, I think we could support 12 until its [end of life](https://endoflife.date/nodejs). If it is not causing issues I think it's ok!

**Comment by danielpeintner** [comment]
Thanks for your comments 👍 
Mhh, both comments seem to make me think we should still support v12, .. unless we run into actual issues...

Note: End of life for NodeJS v12 is May 2021, https://endoflife.date/nodejs

**Comment by danielpeintner** [comment]
At the moment we run tests for
* 12.x
* 14.x
* 16.x

I [updated the readme accordingly](https://github.com/eclipse/thingweb.node-wot/commit/9a0f90c987e2c20d64666bb2baf78c4a1c15ba37).

Hence, I think we can close this issue.
