### ISSUE TITLE
WoT Firestore binding naming

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#489]
Currently we have all bindings named like this
* binding-coap
* binding-file
* binding-http
* ...

Recently we added two new bindings
* binding-wotfirestore
* binding-wotfirestore-browser-bundle

which seem to use a different naming convention by adding "wot".

Not sure if it is just me but I would rather choose the following:
* binding-firestore
* binding-firestore-browser-bundle

We can still change that since it was *not* published yet on NPM.
Any thoughts? 
@hidetak

**Comment by hidetak** [comment]
@danielpeintner 
I have no particular objection to changing the name to the following.
* binding-firestore
* binding-firestore-browser-bundle

I will change the names.

**Comment by danielpeintner** [comment]
I provided a PR, see https://github.com/eclipse/thingweb.node-wot/pull/494
@hidetak may I ask you take a look?
