### ISSUE TITLE
Make v0.8.x the *new* master

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#495]
TODOs for making [`v0.8.x`](https://github.com/eclipse/thingweb.node-wot/tree/v0.8.x) the *new* master

### Before merge
* [x] merge PR firestore, https://github.com/eclipse/thingweb.node-wot/pull/494
* [x] publish version 0.7.8 on NPM
* [x] create branch v0.7.x for possible fixes in the future, see https://github.com/eclipse/thingweb.node-wot/tree/v0.7.x
*  [x] fix wotfirestore naming issue in v0.8.x also (see https://github.com/eclipse/thingweb.node-wot/pull/502), https://github.com/eclipse/thingweb.node-wot/issues/489

### After merge
*  [ ] check all examples (on-going work)
*  [ ] remove for the time being branch v0.8.x
*  [ ] fix remaining issues, e.g., `ExposedThing` implementing `setPropertyObserveHandler()`,  `setPropertyUnobserveHandler()`, ...
*  [ ] bring back HTTP server test, see https://github.com/eclipse/thingweb.node-wot/blob/59fe3264bb4cfa19a3c8cddb0f1c68b4685a4a47/packages/binding-http/test/http-server-test.ts#L73-L74

Did I miss anything?

**Comment by relu91** [comment]
> create branch v0.7.x for possible fixes in the future

I think is a good idea to keep track of it 👍🏻 , but I also suggest that we defined and date when we drop the support for 0.7.x. We don't have so many resources... I am afraid it would be a mess handling issues for two versions. 🤔

**Comment by danielpeintner** [comment]
> I think is a good idea to keep track of it 👍🏻 , but I also suggest that we defined and date when we drop the support for 0.7.x. We don't have so many resources... I am afraid it would be a mess handling issues for two versions. 🤔

I agree. I do not plan to propose to update the branch. In the past we created a branch for [v0.6.x](https://github.com/eclipse/thingweb.node-wot/tree/v0.6.x) also. However, we did not proceed to work on it. I expect to happen the same this time. 
IF someone wants to take over the work we have a clean branch one can take a look at.

**Comment by egekorkan** [comment]
This can be closed no?

**Comment by danielpeintner** [comment]
Yes, let's close it even though the part of *updating* all examples is not done yet.
I will try to work on https://github.com/eclipse/thingweb.node-wot/pull/618

Please take a look at https://github.com/eclipse/thingweb.node-wot/pull/618#issuecomment-964329859 and provide feedback.
I have the feeling we should remove MANY examples and bring them only back is there is need for it.
