### ISSUE TITLE
Question: why is /all/properties used instead of /properties?

### ISSUE THREAD

**Issue by miguelrk** [eclipse/thingweb.node-wot#505]
Note: this is not an issue, only something I've been wondering...

**Question:** 

Why does node-wot use `/all/properties` and not `/properties` directly?

**Reasoning:**

Currently, `binding-http` [handles](https://github.com/eclipse/thingweb.node-wot/blob/56bbc544e964b369c1bdb57be540e96662c13114/packages/binding-http/src/http-server.ts#L271) `readallproperties` and `writeallproperties` under this path:

```
/all/properties
```

Following REST principles, and maybe even MQTT topic syntax, I think 

```
/properties
```

makes more sense for these `op` values.

This also applies to   `readmultipleproperties`, and `writemultipleproperties` (not fully implemented yet, see [here](https://github.com/eclipse/thingweb.node-wot/issues/246)) and maybe even the incoming `subscribeallevents`, etc

There must be a valid reason for prefixing with `/all`, maybe to make it not necessarily RESTfull, but rather more protocol agnostic. Or maybe because of code complexity, but digging into the code I couldn't come-up with why using `/properties` directly would make handling the distinct `op` types harder. 

To my knowledge, the Thing Description Spec does not give an official recommendation for this (left to implementation). I was just curious why this is handled so, maybe others as well.

Thanks!

**Comment by danielpeintner** [comment]
I think we have support for "all" in HTTP and CoAP.

I recall that I implemented the support at that time and _maybe_ I didn't think too much about the URL.
Having said that, I do not have a strong opinion and thinking about it more closely it makes sense to use purely `/properties`.

@relu91 @egekorkan do you see any reason for keeping the current way?

**Comment by egekorkan** [comment]
I would also support the proposal above

**Comment by danielpeintner** [comment]
Okay, let's do the change then... I will provide a PR

**Comment by relu91** [comment]
+1 for `/properties`
