### ISSUE TITLE
[question] How to send images (contenttype:image/jpeg)

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#51]
How can I create a property with a contenttype equal to image/jpeg? In general, is there a way to change the contenttype of the created forms?

**Comment by mkovatsc** [comment]
This is more a topic for https://github.com/w3c/wot-scripting-api/issues

**Comment by egekorkan** [comment]
I have commented on the issue [#112](https://github.com/w3c/wot-scripting-api/issues/112) of the scripting api specification.

**Comment by egekorkan** [comment]
[](url)

**Comment by danielpeintner** [comment]
@egekorkan can we close this issue given that https://github.com/w3c/wot-scripting-api/issues/112 is closed too?

**Comment by egekorkan** [comment]
Actually I have written another issue in the scripting API ( [156](https://github.com/w3c/wot-scripting-api/issues/156) ). The ambiguity is the fact that the scripting API says to accept a TD for the expose method but actually the algorithm should decide how to init the exposed thing. In this case it is not clear whether not having this feature is the "fault" of node-wot or scriptiing API

**Comment by egekorkan** [comment]
From the discussion in Scripting API on issue [156](https://github.com/w3c/wot-scripting-api/issues/156), at the moment it is up to the implementation to figure out how to interpret the form field of a given TD for the produce() method. This means that we can (and I think we should) use the information provided in the form field. At the moment it is completely ignored.

**Comment by danielpeintner** [comment]
@egekorkan any update?

**Comment by egekorkan** [comment]
Nothing from my side...

**Comment by egekorkan** [comment]
There is also a need/usecase for this by @jenlincode

**Comment by sebastiankb** [comment]
I think the produce() should provide a way to override the default assumptions in node-wot (also in forms). E.g.,

```JavaScript
WoT.produce({
		"@context": "https://www.w3.org/2019/wot/td/v1",
		title: "camera",
		properties: {
			myPhote: {
				description: "Latest cached photo",
				readOnly: true
				forms: [{contentType:"image/jpeg"}]
			}
```

The contentType should override the application/json.

**Comment by relu91** [comment]
If no one is on this issue, I could give a hand and propose an implementation for merging form configurations with the defaults. I am wondering what will happen if the codec for the contentType specified in the form is not defined? Should we raise an error immediately?

**Comment by egekorkan** [comment]
There is #187 so I would wait the progress there :)

**Comment by danielpeintner** [comment]
Thanks @relu91,

as @egekorkan mentioned I did started exploring a bit how it could be done.

It seems a bit *hacky* so please comment or make suggestions in the PR https://github.com/eclipse/thingweb.node-wot/pull/187

**Comment by danielpeintner** [comment]
PR #187 merged
