### ISSUE TITLE
Commented out test in coap-client-test.ts

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#523]
https://github.com/eclipse/thingweb.node-wot/blob/fc359193faea478e6682946fbde79d35c73205c5/packages/binding-coap/test/coap-client-test.ts#L51

We need to decide either to remove the test completely or reimplement it without massive commented out blocks of code.
This issue was initiated by @relu91 while reviewing my PR - https://github.com/eclipse/thingweb.node-wot/pull/520.

**Comment by relu91** [comment]
After #538 and #602 we should probably re-evaluate this issue. @danielpeintner can you give it a look?
