### ISSUE TITLE
.eslintrc.json in some packages only

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#530]
I noticed that we do have the file `.eslintrc.json` in some packages only.

e.g., it is missing for
* binding-mbus
* binding-fujitsu
* binding-mqtt
* ...

Wouldn't it be possible to have it in the root directory only?
@JKRhb

**Comment by danielpeintner** [comment]
I see.. I was just surprised that some packages *do* have  `.eslintrc.json`  while others *do not* have it..

**Comment by relu91** [comment]
Originally I planned to add all the packages under eslint validation, but due time constraints we merge the first PR before finishing it. With the current setup when we'll add new packages under eslint validation we must add also the relative `.eslintrc.json`
