### ISSUE TITLE
Http tests fails: timeouts

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#553]
It seems that sometimes CI tests fail for addresses already in use in the http-protocol binding. Probably, we are missing to clean up or close some resources. Refer to this https://github.com/eclipse/thingweb.node-wot/runs/3805137969

Additional resources:
https://github.com/eclipse/thingweb.node-wot/commit/eb1c4a2187bedcb457e13248873de85b39efa341

**Comment by relu91** [comment]
PR #519 might resolve the issue.

**Comment by relu91** [comment]
Btw the original issue remains https://github.com/eclipse/thingweb.node-wot/runs/3882878266?check_suite_focus=true#step:7:938

**Comment by danielpeintner** [comment]
I might be wrong but this always seemed to be a Mac issue.

**Comment by danielpeintner** [comment]
Sorry, missed that. Merged it just now.

**Comment by relu91** [comment]
It seems we finally tackled this issue, re-open if it happens again!
