### ISSUE TITLE
TD alignments for F2F Princeton

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#56]
TD alignments for F2F Princeton

This is meant to b a sticky placeholder to keep track of missing alignments (with https://w3c.github.io/wot-thing-description/).

- [ ] TODOs (Look into)
  - [ ] Eventing in general: `cancellation`, `subscription`, ...
  - [ ] `ExpectedResponse` (@wiresio)
- [x] `uriVariables` (https://github.com/eclipse/thingweb.node-wot/commit/df9ecdd7aa972e7be7a9b9386b7270f8177b7327)
- [x] `forms` on top-level (i.e. read-all) (https://github.com/eclipse/thingweb.node-wot/commit/cd99e8f33f77f067afd644e62b8c57e8c68ee2af)
- [x] `Versioning` (DP: field added. More needed? --> @sebastiankb I tested this feature. Works!)
- [x] `MultiLanguage` (DP: field added. More needed? --> @sebastiankb I tested this feature. Works!)
- [x] `scopes`, `security`, and `uriVariables` on InteractionFragment level (fixed in https://github.com/eclipse/thingweb.node-wot/commit/2b830e3f0dc3ed71b09e2d657bae14ff80494f1d)
- [x] `op` in `forms` (@sebastiankb, please check also outcome of https://github.com/w3c/wot-thing-description/issues/236#issuecomment-449293523)
- [x] observable properties with http longpoll (@sebastiankb)
- [x] Add `safe` and `idempotent` to `Action` (https://github.com/eclipse/thingweb.node-wot/commit/d80eea9242b81f965fcd15c0fe825dbcdd4cf1d6)
- [x] Remove `writable` and replace it with `readOnly` and `writeOnly` (fixed in https://github.com/eclipse/thingweb.node-wot/commit/96c37f614f83142c6f7b412a544e186bcb45ff38 and https://github.com/eclipse/thingweb.node-wot/commit/85e9cd7ce400c7928bc86fa92ae2c8501d18fc30)
- [x] Security (fixed in https://github.com/eclipse/thingweb.node-wot/commit/1c8df2e52f5d6890a93d101fc401cee253b44109)
  - [x] `SecurityScheme`: rename `proxyURI` to `proxy`
  - [x] Rename `APIKeySecurityScheme` to  `ApikeySecurityScheme`
  - [x] `BearerSecurityScheme`: add attribute `authorization`
  - [x] `CertSecurityScheme`: missing
  - [x] Rename `PskScheme ` to `PSKSecurityScheme` and add attribute `identity`
  - [x] `PublicSecurityScheme`: missing
  - [x] Rename `PopSecurityScheme` to  `PoPSecurityScheme`
  - [x] `OAuth2SecurityScheme`: add attributes `token` and `refresh`
- [x] `mediaType`/`contenttype` renamed to `contentType` (fixed in https://github.com/eclipse/thingweb.node-wot/commit/2c889b595afbcb3b3137fde68de6c3a2c55ac6e1)

Please comment below if you encounter anything else missing...

**Comment by sebastiankb** [comment]
I can take care of it

**Comment by danielpeintner** [comment]
> I can take care of it

Great. Please check also outcome of https://github.com/w3c/wot-thing-description/issues/236#issuecomment-449293523

**Comment by sebastiankb** [comment]
I can take over 'uriVariables'. 
@danielpeintner  Is there already a decision about the way how should be this implemented in the TD API?

**Comment by danielpeintner** [comment]
> I can take over 'uriVariables'.
> @danielpeintner Is there already a decision about the way how should be this implemented in the TD API?

No decision yet (see https://github.com/w3c/wot-scripting-api/issues/149#issuecomment-452640908)

**Comment by sebastiankb** [comment]
@danielpeintner do you have a web meeting on Monday? Would be cool to have a decision there. Please let me know.

**Comment by danielpeintner** [comment]
> @danielpeintner do you have a web meeting on Monday? Would be cool to have a decision there.
> Please let me know.

Yes, we do have a scripting meeting on Monday but I don't expect a definite answer given that there was no feedback yet...

**Comment by danielpeintner** [comment]
w.r.t. uriVariables I like the latest Proposal 3 by @zolkis (see https://github.com/w3c/wot-scripting-api/issues/149#issuecomment-456122569).

I think for now it is best to implement this approach given that it seems the way JS libraries are *generally* build...

**Comment by danielpeintner** [comment]
open issues were taken over to https://github.com/eclipse/thingweb.node-wot/issues/88
