### ISSUE TITLE
Support for Thing Models

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#563]
I think it is time to support [ThingModels](https://w3c.github.io/wot-thing-description/#thing-model) in node-wot.

What do I mean by that. An utility class that is able to create out of a TM a proper TD.

* [Placeholder](https://w3c.github.io/wot-thing-description/#thing-model-td-placeholder)
  - use of https://www.npmjs.com/package/json-placeholder-replacer ?
* [Extension and Import](https://w3c.github.io/wot-thing-description/#thing-model-extension-import) ?
* [Required](https://w3c.github.io/wot-thing-description/#thing-model-td-required) ?
* [Composition](https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1207.html#thing-model-composition) ?

I think we have 2 options, implement it
* as part of the `td-tools` package
* in a dedicated package

Any opinions, comments?

**Comment by danielpeintner** [comment]
> The new [composition](https://pr-preview.s3.amazonaws.com/w3c/wot-thing-description/pull/1207.html#thing-model-composition) feature should also be covered.

Yes, added it to the list above

> We should also be in close exchange with the ediTDor project, which would benefit from such a lib for the design of (complex) Thing Models and their visualization. @fexpal

👍 


> I would be ok to have the TM feature in the td-tools package since TMs are related to TDs. Maybe we start with that. When the TM part getting more overweight then we can think about a separate tm-tool package.

Agree.

**Comment by relu91** [comment]
PTAL #674

**Comment by danielpeintner** [comment]
I think we can close this issue.
https://github.com/eclipse/thingweb.node-wot/issues/680 takes care of the next steps.
