### ISSUE TITLE
td-transformer has some misleading method names

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#564]
I think that it is time to clean up the td-transformer file (https://github.com/eclipse/thingweb.node-wot/blob/master/packages/td-tools/src/td-transformer.ts) since it has some really old TD conversions that even have misleading names like V2. It is not the same v2 I would have thought of, i.e. TD version after the 1.1.

**Comment by danielpeintner** [comment]
The same issue goes for 
https://github.com/eclipse/thingweb.node-wot/blob/master/packages/td-tools/src/td-repository.ts

I think both files are out-dated and should be removed from `td-tools`.

Note: What should come *new* is helpers for
* canonicalize TDs and
* TM support
