### ISSUE TITLE
Parsing error: Cannot read file '.../tsconfig.json'.eslint

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#572]
Locally I do run into issues running
`npm run lint`

Similar to what is reported here
https://stackoverflow.com/questions/64933543/parsing-error-cannot-read-file-tsconfig-json-eslint

@JKRhb did you ever experience the same ?

![grafik](https://user-images.githubusercontent.com/11281461/137161446-9d031460-9fc9-452e-a874-5e6939d5131b.png)

I checked the CI run and there it seems to be the same
https://github.com/eclipse/thingweb.node-wot/runs/3883290275

Do you know what might have broken the toolchain?

**Comment by relu91** [comment]
> https://github.com/eclipse/thingweb.node-wot/runs/3883290275

why is the lint step green if everything is failing? 🙈 it is probably related to #554, because it used the root configuration and it looking for a missing file. I didn't notice this during the review sorry...

**Comment by danielpeintner** [comment]
> In this case it is actually a real problem. Because of the many errors that are currently reported I added `continue-on-error: true` to the linting CI step. Maybe we should really turn all errors into warnings, letting the CI only fail in this cases like this one. As the warnings are displayed on the `File changed` tab we would still have the benefits of the linter without the drawbacks.

The issue has been fixed by https://github.com/eclipse/thingweb.node-wot/pull/574 👍 

However, I wonder whether we should turn all errors into warnings as JKRhb has been proposing.
I think this gives us some hint what is going on. Opinions?

**Comment by relu91** [comment]
>In this case it is actually a real problem. Because of the many errors that are currently reported I added continue-on-error: true to the linting CI step. Maybe we should really turn all errors into warnings, letting the CI only fail in this cases like this one. As the warnings are displayed on the File changed tab we would still have the benefits of the linter without the drawbacks.

Oh, now I remember that allows success even of failure and we keep track of it here: https://github.com/eclipse/thingweb.node-wot/issues/516. I think that once we'll set `continue-on-error: false` everything will work properly. 

> However, I wonder whether we should turn all errors into warnings as JKRhb has been proposing.

My opinion is to leave them as errors, once we'll close #516 everything will be in place. I'd close this issue.
