### ISSUE TITLE
Resolve remaining eslint errors/warnings

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#586]
`npm run lint` still shows errors/warnings which we should fix:
Note: `npm run lint` can be run in a dedicated package only to the see the according infos.

* [x] `td-tools`, resolved by https://github.com/eclipse/thingweb.node-wot/pull/581/
* [x] `core`, initially resolved by https://github.com/eclipse/thingweb.node-wot/pull/582/ but I noticed recent updates broke it again, see https://github.com/eclipse/thingweb.node-wot/pull/585#issuecomment-946428271
* [x] `binding-coap`, @JKRhb, https://github.com/eclipse/thingweb.node-wot/pull/588
* [x] `binding-file`, @danielpeintner, see https://github.com/eclipse/thingweb.node-wot/pull/587
* [x] `binding-firestore-browser-bundle` and `binding-firestore`, see https://github.com/eclipse/thingweb.node-wot/pull/808
* [x] `binding-http`, @relu91 ?
* [x] `binding-mbus`, @LennyHEVS @Chxresubles @danielpeintner https://github.com/eclipse/thingweb.node-wot/pull/594
* [x] `binding-modbus`, @relu91 ?
* [x] `binding-mqtt`, @danielpeintner, https://github.com/eclipse/thingweb.node-wot/pull/592
* [x] `binding-netconf`, disabled warnings by https://github.com/eclipse/thingweb.node-wot/pull/818
* [x] `binding-opcua`, @erossignon, https://github.com/eclipse/thingweb.node-wot/pull/591
* [x] `binding-websockets`, @miguelrk, https://github.com/eclipse/thingweb.node-wot/pull/590
* [x] `browser-bundle`, @danielpeintner, https://github.com/eclipse/thingweb.node-wot/pull/597
* [x] `cli`, https://github.com/eclipse/thingweb.node-wot/pull/589
* [x] `examples`, ?, Note: `npm run lint` causes Oops! Something went wrong! :( , see https://github.com/eclipse/thingweb.node-wot/issues/595

**Comment by relu91** [comment]
I've checked the boxes to reflect the latest changes. There are still some warnings in `netconf` and `firestore` is still excluded from eslint checking.

**Comment by danielpeintner** [comment]
> * [x] `binding-firestore-browser-bundle` and `binding-firestore`

I reflected the latest updates. Having said that, `netconf` should have been the only package which needs some care.
Anyone willing to take the task? 

EDIT: Unfortunately, It is not entirely true.. running `npm run lint` shows one *?new?* issue in `mqtt` packages as well.

```
C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-mqtt\src\mqtt-broker-server.ts
  280:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 1 problem (0 errors, 1 warning)


C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-netconf\src\codecs\netconf-codec.ts
  117:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  118:18  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-netconf\src\xpath2json.ts
  20:28  warning  Argument 'json' should be typed with a non-any type  @typescript-eslint/explicit-module-boundary-types
  20:34  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  58:14  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
  59:17  warning  Unexpected any. Specify a different type             @typescript-eslint/no-explicit-any
```

I suggest to resolve the remaining issues and then implement the commit/push check so that in future we are not getting back *new* warnings..

**_OR_**

we add ignore statements (as we did for other parts, see https://github.com/eclipse/thingweb.node-wot/issues/534) and install the check for any future PR/commit NOW.

Any thoughts?

**Comment by danielpeintner** [comment]
Note: MQTT warning is fixed by https://github.com/eclipse/thingweb.node-wot/pull/816.

I am inclined to add ignore statements to the other warnings for now and install the eslint check in the CI.

**Comment by danielpeintner** [comment]
eslint does no longer show errors/warnings 👍 

I will close this issue but we should try to look into https://github.com/eclipse/thingweb.node-wot/issues/534 ...
