### ISSUE TITLE
Document version of Node.js used

### ISSUE THREAD

**Issue by mmccool** [eclipse/thingweb.node-wot#6]
It was unclear to me whether 8.x or 10.x was necessary.  I assume you are using a recent version but it's not clear how recent it has to be.  I installed 10.5.0 and got the following error when trying to run the examples/scripts:
```
~/thingweb.node-wot/examples/scripts$ wot-servient
WoT-Servient using defaults as 'wot-servient.conf.json' does not exist
DefaultServient configured with { servient: { scriptDir: '.', scriptAction: false },
  http: { port: 8080, selfSigned: false } }
HttpServer starting on port 8080
DefaultServient started
Trace: error building CLI Management Thing: TypeError: console.debug is not a function
    at /home/mmccool/Devel/thingweb.node-wot/packages/cli/dist/default-servient.js:82:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
WoT-Servient cannot start: console.debug is not a function
```
Alternatively, fix the above so node-wot works with 10.x (of course, something *else* could be wrong here...)

**Comment by mmccool** [comment]
Since the exact problem noted seems to be related to logging the hint you gave about that (https://gist.github.com/spmason/1670196) may be relevant.

**Comment by mkovatsc** [comment]
You need at least 8.0.0 for the console functions. Can you recheck installed node version?

**Comment by mkovatsc** [comment]
Now documented fully in README.md
