### ISSUE TITLE
binding-opcua does not handle arrays properly

### ISSUE THREAD

**Issue by lukesmolo** [eclipse/thingweb.node-wot#611]
As shown in node-opcua/node-opcua#1074 the _node-opcua_ is not properly handling arrays while converting a _datavalue_ to a javascript object. This translates into the fact that the binding-opcua cannot handle property properties that have an array as value. According to the author of the _node-opcua_ library, this should be fixed in another version of the opcua binding. Nevertheless, since at the moment the current binding is not properly working, a possible solution could be to use a workaround -as suggested by @erossignon- while waiting for the new _node-opcua-json_  module for converting _datavalue_ to JSON.

**Comment by danielpeintner** [comment]
Is this issue still relevant? Or is it solved in new opcua binding?
@relu91 @erossignon @lukesmolo

**Comment by erossignon** [comment]
@danielpeintner, this issue is not relevant anymore, we now formally use OPCUA JSON encoding with normalized support of Array.
