### ISSUE TITLE
[binding-http] ReferenceError: alparser is not defined

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#614]
running `node packages\cli\dist\cli.js examples\scripts\counter.js` and trying to load http://localhost:8080/counter fails with

```
counter ready
[core/servient] Servient caught Asynchronous script error 'C:\Projects\WoT\thingweb\thingweb.node-wot\examples\scripts\counter.js' and halted with ReferenceError: alparser is not defined
    at HttpServer.<anonymous> (C:\Projects\WoT\thingweb\thingweb.node-wot\packages\binding-http\dist\http-server.js:511:54)
```

**Comment by fillobotto** [comment]
Were you on a specific branch? because I cannot reproduce the problem on master branch. Loading the TD on the browser looks fine to me and no internal error is fired.

**Comment by danielpeintner** [comment]
It has been fixed in the meanwhile. Let's close the issue.
