### ISSUE TITLE
Husky - Pre-Build / Pre-Test

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#624]
Hi,

while working with the *new* husky functionality to push partly ready stuff (even in my private repo) it is a bit annoying if something does not fully work yet. It is not possible to push without tweaking around... same if I want to continue the work on another machine etc.

Is it just me thinking that this is somehow a undesired overkill?

Comments welcome!

**Comment by relu91** [comment]
I think in those special cases we can recommend people to use `--no-verify` option of git command. Check [this](https://github.com/typicode/husky/issues/124#issuecomment-299847973) interesting thread about it.

**Comment by relu91** [comment]
@danielpeintner can we close this issue? does the `--no-verify` option cover your needs?
