### ISSUE TITLE
bug: securityDefinitions is missing

### ISSUE THREAD

**Issue by sebastiankb** [eclipse/thingweb.node-wot#63]
`securityDefinitions` is mandatory (https://w3c.github.io/wot-thing-description/#thing), however, a Thing Producer does not generate a TD with this term at top level.

**Comment by danielpeintner** [comment]
https://github.com/eclipse/thingweb.node-wot/commit/5f198e95d77f6b07e5d668c6e96f20b964e382f8 should resolve the issue with the default security definitions
