### ISSUE TITLE
BasicCredential does not let define name for header

### ISSUE THREAD

**Issue by samubura** [eclipse/thingweb.node-wot#631]
In the method sign of class BasicCredential the "name" parameter of the thing description security schema definition specifying the name of the header to be set is ignored and the default _authorization_ is used instead.

``` 
async sign(request: Request): Promise<Request> {
        const result = request.clone();
        result.headers.set(
            "authorization",
            "Basic " + Buffer.from(this.username + ":" + this.password).toString("base64")
        );
        return result;
    }
```

**Comment by danielpeintner** [comment]
Question: How do you "set" the name?

With the TD that you pass when exposing?
OR
do you set it via `setSecurity(..)` ?

https://github.com/eclipse/thingweb.node-wot/blob/e5b0b20618008e3e26f42f975c54644190f18a06/packages/binding-http/src/http-client.ts#L225-L236

**Comment by relu91** [comment]
> In the method sign of class BasicCredential the "name" parameter of the thing description security schema definition specifying the name of the header to be set is ignored and the default _authorization_ is used instead.
> 
> ```
> async sign(request: Request): Promise<Request> {
>         const result = request.clone();
>         result.headers.set(
>             "authorization",
>             "Basic " + Buffer.from(this.username + ":" + this.password).toString("base64")
>         );
>         return result;
>     }
> ```

Right, this is not implemented in node-wot right now. I don't think it changes whether this was coming from the TD or from `setSecurity` method. @danielpeintner what are you trying to say?

**Comment by samubura** [comment]
I was doing that with the TD but then went looking for it in the code.
