### ISSUE TITLE
[binding-coap] Handle uriVariables

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#636]
Follow-up issue from https://github.com/eclipse/thingweb.node-wot/pull/623#issuecomment-984792457

>... the new `coap-server` was sending an invalid value as `uriVariables`, therefore I've just changed it to return an empty object. ... looking at the file history it seems that it didn't handle `uriVariables` before (but it was correctly returning `undefined`).

see also https://github.com/eclipse/thingweb.node-wot/pull/623/commits/966467e4db4ce77dc0ed7a03736dba74b8e85cf5

**Comment by fillobotto** [comment]
This can be closed, I guess
