### ISSUE TITLE
Shall copyright year ranges be aligned with  the Eclipse proposal

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#643]
In https://github.com/eclipse/thingweb.node-wot/pull/641 @JKRhb found out that Eclipse requires a different format for copyright year ranges than the one we are currently using (see https://www.eclipse.org/projects/handbook/#ip-copyright-headers)

`2018 - 2021`
vs
`2018, 2021`

Question: Shall we update the script to apply all these changes.. it would be one PR with a bit of noise but not a big deal.
Any opinion?

// Note to myself. The copyright script could also check the LICENSE file  //

**Comment by JKRhb** [comment]
Thanks for opening the issue! The other option mentioned in the FAQ would be omitting the year range completely and only stating the year of the initial contribution in  the headers and the license file. This would still cause some noise but would make the annual update of the headers obsolete.

**Comment by relu91** [comment]
> Thanks for opening the issue! The other option mentioned in the FAQ would be omitting the year range completely and only stating the year of the initial contribution in the headers and the license file. This would still cause some noise but would make the annual update of the headers obsolete.

I would support this direction since we should change the copyright in any case it is better to choose the solution that will give us fewer headaches in the future. Was there any reason to use the range?

**Comment by danielpeintner** [comment]
> Was there any reason to use the range?

None I am aware of.
My personal feeling if I see a {year} in source code is the year the file was last modified. Essentially the opposite of the Eclipse proposal but I am fine either way.

Lets go the easy way 👍 

I created an according PR and added a note about our procedure in NOTICE.md and fixed the copyright script.
Please have a look at  https://github.com/eclipse/thingweb.node-wot/pull/644
