### ISSUE TITLE
Follow-up: Clean up examples

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#654]
see [Clean up examples](https://github.com/eclipse/thingweb.node-wot/pull/618)

TODOs/check
* [x] testthing (see https://github.com/eclipse/thingweb.node-wot/pull/669/commits/bc6427fb0f18a4d1504df4eda3d1d80978fea469)
* [x] security
* [x] SmartCoffeeMachine (see https://github.com/eclipse/thingweb.node-wot/pull/669/commits/2de8937f6a656bcde3c18794f15757e294f170c2)
* [x] Browser (see https://github.com/eclipse/thingweb.node-wot/pull/686, TODO more to come)
* [x] Update various Readme.md files of binding packages (some examples might not exist anymore)

**Comment by erossignon** [comment]
we also need to clean the various Readme.md file of the bingmding modules that refers to examples that do not exist anymore

**Comment by danielpeintner** [comment]
I believe once https://github.com/eclipse/thingweb.node-wot/pull/721 has landed we are done.

**Comment by relu91** [comment]
PR merged, closing.
