### ISSUE TITLE
Replacement method for deprecated writeProperty

### ISSUE THREAD

**Issue by ferllings** [eclipse/thingweb.node-wot#661]
Hello,

Since writeProperty is now marked as deprecated https://github.com/eclipse/thingweb.node-wot/blob/0d0f8a40a03ee1eaaf61276238f889d782aca1c6/packages/core/src/exposed-thing.ts#L548

I'm confused about how to initialise the property value, and/or how to update the property from a sensor async event.

The Scripting API isn't clear about to do that. What is the recommended method?

Thanks,

**Comment by danielpeintner** [comment]
`writeProperty()` has never been actually required in the past and caused misunderstanding.

Examples how to use/init properties can be found in  [counter](https://github.com/eclipse/thingweb.node-wot/blob/master/examples/scripts/counter.js) example in node-wot.

Use variables and register handlers accordingly..
https://github.com/eclipse/thingweb.node-wot/blob/e1f9c9c50e33922de8117a41345620b57dd89728/examples/scripts/counter.js#L134-L139

Hope this helps.

**Comment by ferllings** [comment]
Thanks,

So in the case of a sensor (sending data in the background), the recommended way is to simply update the variable used by the read handler, and call the emitPropertyChange() method ourself.

Is that correct?

**Comment by relu91** [comment]
>Thanks,
> So in the case of a sensor (sending data in the background), the recommended way is to simply update the variable used by the read handler, and call the emitPropertyChange() method ourself.
> Is that correct?

Yes, it is 👍🏻 .

**Comment by ferllings** [comment]
Perfect. That make sense.

Thanks
