### ISSUE TITLE
Top level URI Variables

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#670]
assuming https://github.com/w3c/wot-thing-description/pull/1383 gets approved we need to be able to handle *global* `uriVariables` also.

**Comment by egekorkan** [comment]
But are the current uriVariables "handled"? The function at https://github.com/eclipse/thingweb.node-wot/blob/86cf8a191e390c5fd2dc85765a77fee64558b7fa/packages/core/src/consumed-thing.ts#L528 can now simply take another uriVariables object that happens to come from Thing-level?
