### ISSUE TITLE
Improve README.md by using dropdowns

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#671]
By accident I stumbled over the fact that GitHub markdown renderings supports drop-downs.
see [examples](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61).

Our main [README](https://github.com/eclipse/thingweb.node-wot#readme) is rather larger with lots of text and a BIG table-of-contents in the beginning.

Since I am not a _fan_  of such readmes I was wondering whether having drop-down for most of the subsections would be a good alternative. Opinions?

**Comment by relu91** [comment]
I think putting dropdowns would improve the readability of the main readme. On the other hand, I prefer short READMEs with just basic getting started Infos and something else dedicated to documentation (wikis, Github pages, etc.)

**Comment by danielpeintner** [comment]
> On the other hand, I prefer short READMEs with just basic getting started Infos and something else dedicated to documentation (wikis, Github pages, etc.)

I see you point. On the other hand splitting the information across several documents makes it even harder to keep them up-to-date.


I experimented a bit with the drop-downs and a first shot can be seen at https://github.com/eclipse/thingweb.node-wot/blob/266ce0b7e2c4e929e4210dee4fc0adf2934c71ba/README.md

I think we could even get rid of the "Table of contents".

**Comment by JKRhb** [comment]
> I think we could even get rid of the "Table of contents".

I think the table of contents might be a bit redundant anyway as you have one at the top left corner in the Readme UI:

![grafik](https://user-images.githubusercontent.com/12641361/153591038-7c0bbb15-d8fd-4fc5-a6d7-f80cdbb0d019.png)

In general, I would agree with @relu91 that concise information in the Readme and more detailed explanations in other documents might be even better than the current approach (which is certainly an improvement but requires more clicking/navigating around).

Maybe some parts of the top-level README could be moved to an FAQ or troubleshooting document/wiki page, like the section about logging or the different versions of Node.js on Linux? Also, the sections regarding the use of the browser bundle as well as the examples may be turned into links to the respective packages/directories.

**Comment by danielpeintner** [comment]
> > I think we could even get rid of the "Table of contents".
> 
> I think the table of contents might be a bit redundant anyway as you have one at the top left corner in the Readme UI:

I hope people do know that. I didn't 🤷‍♂️

> Maybe some parts of the top-level README could be moved to an FAQ or troubleshooting document/wiki page, like the section about logging or the different versions of Node.js on Linux? Also, the sections regarding the use of the browser bundle as well as the examples may be turned into links to the respective packages/directories.

@relu91 @JKRhb do you want to make a proposal?

**Comment by danielpeintner** [comment]
I have been using the README the last days and I think using the drop-downs is not as useful as I thought. There is no good way to search the whole document et cetera.

Hence, I suggest to undo the changes in https://github.com/eclipse/thingweb.node-wot/commit/266ce0b7e2c4e929e4210dee4fc0adf2934c71ba

I know that I was the one who wanted this adjustment but I changed my mind. 🙃

Any thoughts, opinions ?

**Comment by relu91** [comment]
Ok for changing it back,
