### ISSUE TITLE
Eclipse progress review - Code of Conduct

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#688]
see https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_572859

> Consider adding a Security and Code of Conduct files to your project main repository (see an example [here](https://github.com/eclipse-ee4j/.github))

**Comment by danielpeintner** [comment]
w.r.t. 
* Code of Conduct, the [example ](https://github.com/eclipse-ee4j/.github/blob/main/CODE_OF_CONDUCT.md) is fine by me
* Security, the [example ](https://github.com/eclipse-ee4j/.github/blob/main/SECURITY.md) needs to be updated. Before I work on it I would like to get some feedback.
  - Do we need/want it?
  - IF we want to have it, I suggest to use GitHub issues only (no emails et cetera)

any opinions?

**Comment by relu91** [comment]
Ok for the Code of Conduct, just one note: the attribution section has a broken link(?):
> This Code of Conduct is adapted from the **[Contributor Covenant][homepage]**, version 1.4, available at https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

Not sure about security... I'm ok with having the file with some lines explaining that vulnerabilities can be reported using Github issues etc. However, I don't know if we need a "not public" channel like e-mails (that are still not encrypted as the example is stating). Do we need this sort of triage before publicly disclosing a vulnerability? why?

**Comment by danielpeintner** [comment]
> Ok for the Code of Conduct, just one note: the attribution section has a broken link(?):

Mhh, did not find any broken link. Can you point me to the link so we can report it.

> Not sure about security... I'm ok with having the file with some lines explaining that vulnerabilities can be reported using Github issues etc. However, I don't know if we need a "not public" channel like e-mails (that are still not encrypted as the example is stating). Do we need this sort of triage before publicly disclosing a vulnerability? why?

I somewhat agree. Not really sure whether we actually need it. In https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_572859 it reads "Consider adding a Security ...". No MUST to me.

**Comment by relu91** [comment]
> Mhh, did not find any broken link. Can you point me to the link so we can report it.

Sorry I was thinking that this syntax `[Contributor Covenant][homepage]` was for adding a link. Wouldn't be better to have that as a link? 

> I somewhat agree. Not really sure whether we actually need it. In https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_572859 it reads "Consider adding a Security ...". No MUST to me.

Yeah, it sounds like a suggestion to me too. Since we are not sure and we are not required to provide that document I would simply skip it.

**Comment by danielpeintner** [comment]
FYI, GitHub links already to a code of conduct -> https://github.com/eclipse/.github/blob/master/CODE_OF_CONDUCT.md

![grafik](https://user-images.githubusercontent.com/11281461/156017740-606c2298-6822-453d-94b0-a1ba3d227319.png)

**Comment by danielpeintner** [comment]
w.r.t. Security.md it seems we have to use the generic Eclipse one ?

see https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_606240

**Comment by danielpeintner** [comment]
To my question which Security.md to be used I got the following answer
> you can use your own security.md file, however it's recommended you instruct users into reporting vulnerabilities to [security@eclipse.org](mailto:security@eclipse.org)

see https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_617308

IF we need to point to [security@eclipse.org](mailto:security@eclipse.org) I don't really see the sense in having *our* specific file.
Hence, I suggest to use the generic one like [here](https://github.com/eclipse-ee4j/.github/blob/main/SECURITY.md). I assume we get notified once something has been found.

I created https://github.com/eclipse/thingweb.node-wot/pull/708

**Comment by danielpeintner** [comment]
resolved by https://github.com/eclipse/thingweb.node-wot/pull/708

BTW, Eclipse progress review has concluded successfully!
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_617488
