### ISSUE TITLE
Supporting uriVariables on thing level

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#694]
The TD allows having `uriVariables` on thing level (e.g. for readAll)
https://w3c.github.io/wot-thing-description/#thing

### Exposing
Issue: How can node-wot (when exposing) know which uriVariable has to be used for a given affordance

example for local `uriVariable`
```
actions: {
        increment: {
            description: "Incrementing counter value",
            descriptions: {
                en: "Incrementing counter value",
                de: "Zähler erhöhen",
                it: "incrementare valore",
            },
            uriVariables: {
                step: { type: "integer", minimum: 1, maximum: 250 },
            },
        },
```
Note: example for global `uriVariable `does not contain any mentioning in affordance level !!

### Consumer Side
...

**Comment by relu91** [comment]
https://github.com/relu91/thingweb.node-wot/pull/24 hey daniel ! we have something ready for this issue. I'll forward the PR here. Sorry for not sending this earlier.

**Comment by relu91** [comment]
btw is this issue somehow different from this one: #670 ?

**Comment by danielpeintner** [comment]
Correct, duplicate of https://github.com/eclipse/thingweb.node-wot/issues/670
