### ISSUE TITLE
CoAP example hangs after first GET

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#724]
see https://github.com/eclipse/thingweb.node-wot/pull/721#issuecomment-1080433488 

---------

Maybe I was not very clear... it hangs from the beginning on after the first GET.. NO result is reported.

Note1: I did try locally and then it reports values. It seems it has to do again with reaching out to the web again.
Note2: The PR https://github.com/eclipse/thingweb.node-wot/pull/720 is integrated. So this is not the issue. Maybe the Eclipse vserver?
Note3: Attached the test-file I am using.

```
// example-client.js
Servient = require("@node-wot/core").Servient;
CoapClientFactory = require("@node-wot/binding-coap").CoapClientFactory;

Helpers = require("@node-wot/core").Helpers;

// create Servient and add CoAP binding
let servient = new Servient();
servient.addClientFactory(new CoapClientFactory(null));

let wotHelper = new Helpers(servient);
wotHelper
    .fetch("coap://plugfest.thingweb.io:5683/testthing") // coap://localhost:5683/testthing
    .then(async (td) => {
        // using await for serial execution (note 'async' in then() of fetch())
        try {
            const WoT = await servient.start();
            const thing = await WoT.consume(td);

            // read property
            const read1 = await thing.readProperty("string");
            console.log("string value is: ", await read1.value());
        } catch (err) {
            console.error("Script error:", err);
        }
    })
    .catch((err) => {
        console.error("Fetch error:", err);
    });
```

**Comment by relu91** [comment]
might it be related to this: https://github.com/eclipse/thingweb.node-wot/issues/71 ?

**Comment by danielpeintner** [comment]
> might it be related to this: #71 ?

Mhh, not sure, .. https://github.com/mcollina/node-coap/pull/204 has been merged by now.,,

**Comment by JKRhb** [comment]
We just identified and fixed a problem that was related to the observe parameter in node-coap (see https://github.com/mcollina/node-coap/pull/330) that should actually also fix this issue :) I already made sure that removing the observe parameter from the request options lets the client determinate. After the PR above has been merged and a new version of node-coap has been released, we should check again – we might able to close this issue then.

**Comment by danielpeintner** [comment]
to me https://github.com/eclipse/thingweb.node-wot/issues/741 seems related...

**Comment by JKRhb** [comment]
> 1st Test - Web

Are you using the code form above (with `coap://plugfest.thingweb.io:5683/testthing`) here? Hmm, in my case, the test actually works.

**Comment by danielpeintner** [comment]
> > 1st Test - Web
> 
> Are you using the code form above (with `coap://plugfest.thingweb.io:5683/testthing`) here? Hmm, in my case, the test actually works.

Yes, it just hangs. Maybe it depends on my business network setting!?
Can someone else try?

BTW, what happens locally if there is *no* CoAP server running in your case?

**Comment by JKRhb** [comment]
> Yes, it just hangs. Maybe it depends on my business network setting!?

Oh, that sounds plausible!

> BTW, what happens locally if there is _no_ CoAP server running in your case?

With the server not started, the example stops during the `fetch` operation, timing out after the default CoAP timeout span:

```
[core/helpers] Helpers found scheme 'coap'
[core/servient] Servient creating client for scheme 'coap'
[binding-coap] CoapClientFactory creating client for 'coap'
[core/helpers] WoTImpl fetching TD from 'coap://localhost:5683/testthing' with [CoapClient]
[binding-coap] CoapClient got Form 'contentType' application/td+json
[binding-coap] CoapClient sending GET to coap://localhost:5683/testthing
Fetch error: RetrySendError: No reply in 247 seconds.
    at Timeout.<anonymous> (...thingweb.node-wot\node_modules/coap/dist/lib/retry_send.js:56:25)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  retransmitTimeout: 247
}
```

**Comment by danielpeintner** [comment]
Interesting!
I did not know that the timeout is more than 4 minutes 🙃

Both tests fail in my case after the timeout.
Hence, the web test seems to be an issue on my system/network setting.
