### ISSUE TITLE
CoAP causes build issues

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#728]
In https://github.com/eclipse/thingweb.node-wot/pull/727 I wanted to update all version numbers from `0.8.0` to `0.8.1`.

Doing so I removed `package-lock.json` file and recreated it calling `npm install`.
Unfortunately this caused issues in binding-coap.

I wonder also why we use out-dated libraries.
e.g., "node-coap-client": "1.0.8" vs "node-coap-client": "2.0.2"

@JKRhb do you have a clue why this issue is happening?

![grafik](https://user-images.githubusercontent.com/11281461/161062324-0032aebf-d162-4e58-8e4a-cac42b35cbaf.png)

**Comment by JKRhb** [comment]
Oh, I think this is probably caused by the fact that `@types/bl` is only declared as a devDependency and not as a dependency :/ I will open a PR for that in node-coap

**Comment by JKRhb** [comment]
I opened https://github.com/mcollina/node-coap/pull/333, I hope that will fix the issue.

**Comment by danielpeintner** [comment]
I added those types as devDependencies for the time being
see https://github.com/eclipse/thingweb.node-wot/pull/727/commits/897d3dd32f6d6959a159d79ef9da8fe7e4198210

I think doings sop should remove the issue...

We should remove them again if the root cause is resolved.

**Comment by danielpeintner** [comment]
I reverted https://github.com/eclipse/thingweb.node-wot/commit/897d3dd32f6d6959a159d79ef9da8fe7e4198210 and updated to 1.0.5 but I get new issues in coap-server-test.ts

**Comment by danielpeintner** [comment]
FYI, I see

```
  1) CoAP server implementation
       should read property:
     Uncaught TypeError: Cannot read properties of null (reading 'formIndex')
      at ExposedThing.handleUnobserveProperty (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\core\src\exposed-thing.ts:1277:25)
      at ObserveWriteStream.<anonymous> (src\coap-server.ts:369:43)
```

OR

```
  2) CoAP server implementation
       should read property:
     done() called multiple times in test <CoAP server implementation should read property> of file C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-coap\test\coap-server-test.ts; in addition, done() received error: AssertionError: expected '' to equal '"testValue"'
    at CoapServerTest.<anonymous> (C:\Projects\WoT\thingweb\thingweb.node-wot-danielpeintner\packages\binding-coap\test\coap-server-test.ts:68:82)
```

**Comment by JKRhb** [comment]
It took me a while, but I found the issue that caused the strange behavior in node-coap version 1.0.5 (the observe option was always set) and opened https://github.com/mcollina/node-coap/pull/337 to finally fix it :)
