### ISSUE TITLE
Add unsubscribeEvent implementation

### ISSUE THREAD

**Issue by derwehr** [eclipse/thingweb.node-wot#730]
[chore/ExposedThing/unsubscribeEvent](https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/exposed-thing.ts#L951) has no working implementation.

Would simply clearing the `EventState`'s `legacyListeners` array be sufficient to properly unsubscribe, like I did [here](https://github.com/derwehr/thingweb.node-wot/commit/be79fe15d34a8061739c61d7e8a496afb7839d04)?

If yes I'd be happy to submit a PR.

**Comment by danielpeintner** [comment]
You are referring to deprecated (outdated/old) code which I think should be removed, see https://github.com/eclipse/thingweb.node-wot/pull/731.

**Comment by relu91** [comment]
#731 is now merged; @derwehr do you think that the issue is now solved?

**Comment by derwehr** [comment]
Yes, thank you
