### ISSUE TITLE
In API.md writeable is still in use

### ISSUE THREAD

**Issue by yagizyalcintas** [eclipse/thingweb.node-wot#76]
In `Add a Property definition to the Thing` examples, the `writable` is still in use. Only readOnly and writeOnly should be used.

**Comment by danielpeintner** [comment]
@yagizyalcintas thanks for pointing us to this issue. It should be fixes now (see https://github.com/eclipse/thingweb.node-wot/commit/e5c1c0ed4f515f694cb19ee397363faa0769a508)

**Comment by danielpeintner** [comment]
No further feedback -> seems ok
