### ISSUE TITLE
CLI package does not have installation information 

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#761]
I think most CLI users install (currently) node-wot via GitHub but in case they land at npm, the readme has less information than what the main readme has (https://www.npmjs.com/package/@node-wot/cli vs https://github.com/eclipse/thingweb.node-wot/#optional-steps).

I think the prerequisites section that other packages have would be nice

**Comment by danielpeintner** [comment]
@egekorkan do you plan to work on this?

I noticed some information is also in the main README
https://github.com/eclipse/thingweb.node-wot#cli-tool

I guess we need to also check whether everything is still up-to-date

**Comment by egekorkan** [comment]
I will prepare a PR now
