### ISSUE TITLE
Upgrading to version 0.8.2 fails (because of TS and TM definitions)

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#763]
I just wanted to upgrade the versions to  0.8.2.

Regenerating package-lock.json picks the latest versions for 
* wot-thing-description-types@1.1.0-18-May-2022
* wot-thing-model-types@1.1.0-18-May-2022

I think, somehow there seem to be changes that break compilation w.r.t. to `thing[@context]`

```
packages/td-tools/src/td-parser.ts:28:15 - error TS2322: Type '[] | ["https://www.w3.org/2022/wot/td/v1.1", ...(string | { [k: string]: unknown; })[]] | [unknown, unknown, ...unknown[]]' is not assignable to type '(string | Record<string, unknown>)[]'.
  Type '[unknown, unknown, ...unknown[]]' is not assignable to type '(string | Record<string, unknown>)[]'.
    Type 'unknown' is not assignable to type 'string | Record<string, unknown>'.
      Type 'unknown' is not assignable to type 'Record<string, unknown>'.
        Index signature for type 'string' is missing in type '{}'.

28         const arrayContext: Array<string | Record<string, unknown>> = thing["@context"];
                 ~~~~~~~~~~~~

packages/td-tools/src/td-parser.ts:93:16 - error TS2367: This condition will always return 'true' since the types '"https://www.w3.org/2022/wot/td/v1.1"' and '"https://www.w3.org/2019/wot/td/v1"' have no overlap.

93     } else if (thing["@context"] !== TD.DEFAULT_CONTEXT_V1 && thing["@context"] !== TD.DEFAULT_CONTEXT_V11) {
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We need to check what causes those issues.

**Comment by JKRhb** [comment]
> It seems the _old_ context is no longer allowed!?
> 
> changing it to `"@context": "https://www.w3.org/2022/wot/td/v1.1"` works ..

Hmm, I think the 1.1 context requires the old URI *and* the new one in a particular order (see the assertions in [this section](https://w3c.github.io/wot-thing-description/#thing)).

**Comment by danielpeintner** [comment]
To me this *new* requirement is a breaking change, see https://github.com/w3c/wot-thing-description/issues/1510
Moreover, I wonder how we can deal with it in node-wot. We **cannot** use anymore the auto-generated TS definitions since we cannot deal anymore with *old* v1 TDs.

**Comment by relu91** [comment]
I remember discussing this context problem and we couldn't find a feasible workaround to be actually backward compatible. As far as I can remember the resolution was that if you need to use a TD 1.0 you should use the TD 1.0 schema. I didn't like the resolution and I still don't like it but I am not sure if we can solve this. Let's see how the discussion goes in https://github.com/w3c/wot-thing-description/issues/1510. 

We actually can have multiple types imported as dependencies in node-wot and use those accordingly... see https://stackoverflow.com/a/56134858/925955

**Comment by danielpeintner** [comment]
Thanks @relu91 fro your explanation 👍
1. One aspect is how to solve it in node-wot
2. I don't think the TD solution is correct. Hence I agree with waiting for https://github.com/w3c/wot-thing-description/issues/1510.

**Comment by danielpeintner** [comment]
obsolete by now
