### ISSUE TITLE
Thing level forms does not include op

### ISSUE THREAD

**Issue by yagizyalcintas** [eclipse/thingweb.node-wot#77]
Thing level forms is used for reading/writing all properties but the TD generated by node-wot doesn't include the readAllProperties value for op in forms. 
https://github.com/eclipse/thingweb.node-wot/commit/cd99e8f33f77f067afd644e62b8c57e8c68ee2af doesn't add this feature.

**Comment by danielpeintner** [comment]
FYI: the scripting API works on the *next* API which introduces this capability and node-wot will implement this...

**Comment by danielpeintner** [comment]
https://github.com/eclipse/thingweb.node-wot/commit/f013e33119aadc1c35554e99bd88e83ca05712f7 introduces op on thing level
