### ISSUE TITLE
Commandline Option for --clientonly has been changed

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#772]
In the [readme](https://github.com/eclipse/thingweb.node-wot#no-time-for-explanations---show-me-a-running-example) we mention to run

`node packages\cli\dist\cli.js --clientonly examples\scripts\counter-client.js`

but doing so fails with

```
error: unknown option '--clientonly'
(Did you mean --client-only?)
```

I missed that we changed the option.
IF we want to stick to it, we should update the readme also.

Shall we align documentation or internals/code?

**Comment by relu91** [comment]
ah, probably that was changed when we introduced commander. I think client-only is more aligned with what other CLI tools do. So my take is to update the doc.

**Comment by danielpeintner** [comment]
Note: similar issue for `configfile` vs. `config-file`
