### ISSUE TITLE
emitEvent() refers to undefined variable

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#778]
see https://github.com/eclipse/thingweb.node-wot/blob/efc647961038cddbfb677b7573af680ae212514d/packages/core/src/exposed-thing.ts#L162

the 2nd branch points to `this.eventListener` which does not exist.

https://github.com/eclipse/thingweb.node-wot/blob/efc647961038cddbfb677b7573af680ae212514d/packages/core/src/exposed-thing.ts#L177-L186

Should that be just `this.__eventListeners` ?
@relu91 do you know?

EDIT: To be honest I am not sure what the 2nd branch is for?

**Comment by relu91** [comment]
I think it is a bug. In my understanding `ProtocolHelpers.getFormIndexForOperation` might not find the right formIndex for the operation. Therefore, in that case, we are defaulting to calling every protocol listener attached and sending the event on the wire. Not sure if this is the right policy I have to dig more into the logic of  `ProtocolHelpers.getFormIndexForOperation` and how it is connected with  `emitEvent`

**Comment by danielpeintner** [comment]
> I think it is a bug. In my understanding `ProtocolHelpers.getFormIndexForOperation` might not find the right formIndex for the operation. Therefore, in that case, we are defaulting to calling every protocol listener attached and sending the event on the wire.

I think that was the idea behind, but since it tries to iterate over `this.eventListener` which does not exist it doesn't work.

> Not sure if this is the right policy I have to dig more into the logic of `ProtocolHelpers.getFormIndexForOperation` and how it is connected with `emitEvent`

I think if there is no listener found it shouldn't do anything. Meaning that this entire branch should be removed, according to my understanding.
