### ISSUE TITLE
CoAP CI failures

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#781]
Not sure if it is just a random failure or something we overlooked:
![image](https://user-images.githubusercontent.com/3170227/172184299-659072cd-0c62-4525-87f1-a7a159312047.png)

It seems on mac sometimes we are receiving a earlier than expected (or a different error type)

**Comment by JKRhb** [comment]
Hmm, the CoAP test failures already appeared earlier here: https://github.com/eclipse/thingweb.node-wot/issues/434. Not sure why the issue has come up again.

**Comment by relu91** [comment]
Maybe it is this [ephemeral port thing](https://github.com/eclipse/thingweb.node-wot/issues/553#issuecomment-942716986) again? 56832 seems to fall within the range cited by Wikipedia as:
> Many [Linux kernels](https://en.wikipedia.org/wiki/Linux_kernel) use the port range 32768–60999.

**Comment by JKRhb** [comment]
I opened https://github.com/eclipse/thingweb.node-wot/pull/782 as a simple fix for the problem.
