### ISSUE TITLE
Writing to properties fails in browser

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#785]
Create `foo.html` with the following code:

```
<script src="https://cdn.jsdelivr.net/npm/@node-wot/browser-bundle@latest/dist/wot-bundle.min.js"></script>
<script>
    const servient = new Wot.Core.Servient();
    servient.addClientFactory(new Wot.Http.HttpClientFactory());
    const helpers = new Wot.Core.Helpers(servient);
    servient.start().then((thingFactory) => {
        helpers
            .fetch('http://plugfest.thingweb.io:8083/testthing')
            .then((td) => {
                thingFactory.consume(td).then((thing) => {
                    thing.writeProperty('bool', false);
                });
            })
            .catch((error) => {
                window.alert("Could not fetch TD.\n" + error);
            });
    });
</script>
```

Expected result:
No errors, successful write operation.

Actual result:
Error in console, write operation not performed.

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/14371560/173258886-4fce085e-b2f6-43c7-b7e4-734d6033d681.png">

**Comment by sebastiankb** [comment]
just for record: the [webui app](http://plugfest.thingweb.io/webui/) has the same problem when I call an action:

![image](https://user-images.githubusercontent.com/13832739/175528766-37e9b0a3-7232-4286-a2f7-54dc6a54e5bc.png)

**Comment by danielpeintner** [comment]
@relu91 I am not sure if the issue is *really* solved.
I tried the WebUI and I still run into issues

> Error: Readable.from is not available in the browser

Note:  It is different to the one @sebastiankb and others were seeing before...

To reproduce the problem

1. Build node-wot
2. Open `<node-wot-folder>/examples/browser/index.html` locally in a browser and consume http://plugfest.thingweb.io:8083/testthing
3. Invoke "int-int" action

**Comment by danielpeintner** [comment]
FYI: I updated the online version also.
see http://plugfest.thingweb.io/webui/
