### ISSUE TITLE
Configure/define the URL structure of an ExposedThing

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#795]
At the moment the ExposedThing (or the actual binding) defines the structure of a thing.
e.g. for HTTP, 
* `<thing-name>/properties/<property-name>` for properties
* `<thing-name>/actions/<action-name>` for actions
* `<thing-name>/events/<event-name>` for events

There exist cases where the structure is predefined (by a standard or another document etc) and it should be possible in node-wot to build the URL structure as required.

I was wondering "what" would be easiest way to fulfill this requirement. Are there any proposals/ideas?

_I think offering a way to configure every endpoint might be cumbersome and leads to issues._

_Simpler_ alternatives I see are:
* provide an "url-rewrite" configuration/mechanims in node-wot for each binding (or at least to HTTP and CoAP) that defines for example some simple mappings like
"/building-abc/room-33/click-counter/v1/property-count" --> "/counter/properties/count"
Note1: with this approach we might run into name collisions. 

* do it *OUTSIDE* of node-wot --> one can (and MUST) use another HTTP server with a different port and can refer/forward to any URL.

Note2: offering just an alternative URL for another URL endpoint does not update a TD (this may or may not be an issue)

**Comment by egekorkan** [comment]
Option 2 can be done anytime. I think option 1 would be a nice optional configuration. I think it can be done via the TD given into the produce method or via the binding configuration. We have similar ways for some other configuration so it can be up to taste.

**Comment by sebastiankb** [comment]
@egekorkan 
>I think option 1 would be a nice optional configuration. I think it can be done via the TD given into the produce method

 I was also thinking about this. The developer needs to provide the `forms` and `href` entries when no default URL pattern is desired.

**Comment by egekorkan** [comment]
Option 1 is not bad but we have to make sure that only relative URLs are used since the host part of the URL comes from the servient and not from the binding (which manages the forms href). There was previously a discussion about this at #632 . I propose to keep only one issue and move the comments from to the other.
