### ISSUE TITLE
CLI does not correctly read config files

### ISSUE THREAD

**Issue by hasbel** [eclipse/thingweb.node-wot#83]
Loading a configuration from the command line in the CLI does not work as documented.

In the help, the function is documented as:
```
options:
-f, --configfile=file   load configuration from specified file
```

Doing this does not work.

**Comment by danielpeintner** [comment]
@hasbel do you have time to look into that issue?

**Comment by hasbel** [comment]
@danielpeintner I looked into this when I created the issue and I think I have a fix. I'll create a PR as soon as I get some time.
