### ISSUE TITLE
observeproperty with MQTT publishes Content object and not the value

### ISSUE THREAD

**Issue by ilovemilk** [eclipse/thingweb.node-wot#838]
I have setup up a property that is observable with the new node-wot version 0.8.2 which uses an MQTT broker.

I use `emitPropertyChange` to notify the listener that the property has changed. I only registered a `readPropertyHandler` which returns a string.

```javascript
thing.setPropertyReadHandler("status", async () => "on");

thing.setPropertyWriteHandler("status", async (val) => {
    thing.emitPropertyChange("status");
});
```

If I change the property there is a new message on the broker that the property has changed but it is a `Content` object and not the value of the type string with the content type `application/json`.

If I add a longpolling endpoint everything works fine and I get the value of the property and not the `Content` object.

Am I doing something wrong or is this a bug in the MQTT package?

After some digging I think that this line is the problem:

https://github.com/eclipse/thingweb.node-wot/blob/d28218a7d183f4bf05fe9b54e4a3131be4f072c7/packages/binding-mqtt/src/mqtt-broker-server.ts#L137

We already got a `Content` object and we transform the object to a `Content` object again. Thus, we publish the serialized `Content` object instead of the value to the broker leading to this:

```json
{
  "type": "application/json",
  "body": {
    "_readableState": {
      "objectMode": true,
      "highWaterMark": 1,
      "buffer": {
        "head": null,
        "tail": null,
        "length": 0
      },
      "length": 0,
      "pipes": [],
      "flowing": null,
      "ended": false,
      "endEmitted": false,
      "reading": false,
      "constructed": true,
      "sync": true,
      "needReadable": false,
      "emittedReadable": false,
      "readableListening": false,
      "resumeScheduled": false,
      "errorEmitted": false,
      "emitClose": true,
      "autoDestroy": true,
      "destroyed": false,
      "errored": null,
      "closed": false,
      "closeEmitted": false,
      "defaultEncoding": "utf8",
      "awaitDrainWriters": null,
      "multiAwaitDrain": false,
      "readingMore": false,
      "dataEmitted": false,
      "decoder": null,
      "encoding": null
    },
    "_events": {},
    "_eventsCount": 0
  }
}
```

**Comment by danielpeintner** [comment]
Thanks for reporting the issue and digging into the code. I think you are right and I prepared a fix (see https://github.com/eclipse/thingweb.node-wot/pull/840).
Let's wait for review feedback and please try the fix yourself...

**Comment by ilovemilk** [comment]
Thanks your fix worked for me. Now the value is correctly published!
