### ISSUE TITLE
wot-typescript-definitions should be in dependencies

### ISSUE THREAD

**Issue by hasbel** [eclipse/thingweb.node-wot#84]
Currently, the `wot-typescript-definitions` dependency is listed as a `devDependency` in the `core`module even though many of its type definitions are re-exported. (for example in `wot-impl.d.ts`)

When trying to use `@node-wot/core` as a dependency in a typescript project, an error occurs due to missing type definitions.

As we export some of the types it defines, `wot-typescript-definitions` should be listed as a normal dependency.

**Comment by danielpeintner** [comment]
Mhh, correct. I think `wot-typescript-definitions` is a *core* dependency.

Hence, I assume this needs to be fixed for other packages (e.g., binding-coap etc) also.

I will provide a fix.

**Comment by danielpeintner** [comment]
Related question: in `package.json` of binding-fujitsu there is the following case

```
  "devDependencies": {
    "@node-wot/td-tools": "0.6.1",
    ...
  },
  "dependencies": {
    "@node-wot/core": "0.6.1",
    ...
  }
```
`@node-wot/core` refers to `@node-wot/td-tools` as default dependency. Hence this is broken also, I believe.

According to my understanding `devDependencies` should be used only if the dependency 
* is used for building the code (TypeScript dependencies) or
* if it is necessary for tests only

In any other case it should be put as `dependencies`.

@hasbel  any opinion?

**Comment by hasbel** [comment]
There is no need to add the typescript definitions to the `dependencies` of the bindings. They have `core` as a dependency and `core` should provide the type definitions for them. 

Your understanding of `devDependencies` is correct, but types are a bit special in the sense that they may only be needed during development, but may also be exported as well in some cases.

In general, if a type definition (be it `wot-typescript-definitions` or any other `@type/<name>` from definitelyTyped) is exported, it needs to be included in `dependencies`, otherwise it can be in `devDependencies`.

For example, if we look inside the `dist`folder of a binding, we can see that inside the `*.d.ts`typescript definitions, there is no mention of the `wot-typescript-definitions`. However inside `core`, we can see that they are mentioned in many places, including for example `comsumed-thing.d.ts`. 

As for fujitsu binding, you are right, `@node-wot/td-tools` should be in `dependencies` because is needed for the code to run.

**Comment by danielpeintner** [comment]
> As for fujitsu binding, you are right, @node-wot/td-tools should be in dependencies because is needed for the code to run.

I will look into that more closely but I think in this case we can even safely remove "@node-wot/td-tools" from "devDependencies" without the need of adding it to "dependencies". 

i.e. `@node-wot/core` depends on `@node-wot/td-tools`

Doing so in all `package.json` would clean-up the dependencies...

**Comment by danielpeintner** [comment]
I pushed a commit (see https://github.com/eclipse/thingweb.node-wot/commit/20ce754f429b0296dec499bc5d3dd166e0a86b9a) that cleans-up some dependencies and fixes the problem from @hasbel 

Unfortunately *implicit* dependencies need to be put as an additional dependency if the types are used. I did not find another good solution for it..

@hasbel @h0ru5 
Shall we do some more changes or leave it like this?

**Comment by danielpeintner** [comment]
No response and I assume issue is fixed by now.

Feel free to re-open the issue if this is not the case.
