### ISSUE TITLE
[outreach] Presenting firebase binding in a WoT CG call

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#851]
@hidetak I do not have other means to contact you, thus I am opening this issue.

With @relu91 we have restarted the WoT Community Group at the W3C (https://www.w3.org/community/wot/) and we are organizing meetup events where WoT projects can be presented. I think that your contribution is a really nice one that shows WoT's applicability in different domains and existing platforms. We can talk here if you do not want to exchange emails or you can contact me at the email address at https://github.com/egekorkan .

**Comment by hidetak** [comment]
@egekorkan 

Thank you for your suggestion!
I would be happy to contact you via email.

**Comment by relu91** [comment]
@egekorkan @hidetak I would close this issue since we chat in the email. Feel free to reopen it if needed
