### ISSUE TITLE
Introduce `toBuffer()` method for `Content`?

### ISSUE THREAD

**Issue by JKRhb** [eclipse/thingweb.node-wot#853]
At the moment, in order to turn the stream inside a `Content` object into a buffer, you need to invoke the helper function `readStreamFully` with the `Content`'s `body` as its argument:

```ts
    const buffer = ProtocolHelpers.readStreamFully(content.body);
````

With this issue, I wanted to a propose a slight API change for `Content` (informed by its [`dart_wot` counterpart](https://github.com/namib-project/dart_wot/blob/main/lib/src/core/content.dart#L13)), making working with it a bit more handy.

In particular, I would propose turning it from an interface into a class and introducing a dedicated `toBuffer()` method. That would simplify the code above as follows, making it a bit more readable:

```ts
    const buffer = content.toBuffer();
````

I already have a branch ready which I could turn into a PR if this proposal seems reasonable to you.

**Comment by relu91** [comment]
When we did the big refactoring from having values to streams, I considered the same design. At the time, I discarded the choice for two (disputable) reasons:
1. We were in the middle of big refactoring and I didn't want to introduce additional controversial changes
2. `Content` is an interface, if you introduce a method it means that now you need a concrete class that implements it. I'm coming from the OOP world, so for me, it is pretty natural to have such of `toBuffer` method. But node-wot at its beginnings was more functional style and in that context, it makes more sense to have a utility function (i.e., readStreamFully). 

So the text above is just to provide context to the discussion. As I said my preference would be to change Context to be a class and have the `toBuffer` method.

**Comment by danielpeintner** [comment]
> As I said my preference would be to change Context to be a class and have the `toBuffer` method.

Your thinking and the one from @JKRhb makes sense.
@JKRhb you mentioned you have a branch ready... would you mind opening a PR. I would like to see the amount of changes. Thanks!

BTW, we might need to keep the helper function for compatibility reasons... which makes it a bit hacky.. I guess .. opinions?

**Comment by JKRhb** [comment]
Thank you for your feedback :) I opened #856 as a proposal for this change. As you already mentioned, @danielpeintner, getting rid of the helper function was not entirely possible as it is also used in other contexts, but maybe there is room for some more refactoring/clean up in the future.
