### ISSUE TITLE
NodeJS 12 is EOL

### ISSUE THREAD

**Issue by ctron** [eclipse/thingweb.node-wot#869]
NodeJS 12 is EOL, the current LTS version is 18.

I think the container images and build instructions should be updated accordingly.

**Comment by egekorkan** [comment]
We were using Node 12 since the server where the example scripts are deployed was running it. I have upgraded it to v18 so there should be no need to mention it at all.

**Comment by danielpeintner** [comment]
> there should be no need to mention it at all.

I am not sure what you mean by that. Can you explain in more details?

**Comment by egekorkan** [comment]
> > there should be no need to mention it at all.
> 
> I am not sure what you mean by that. Can you explain in more details?

So there are the following mentions:
- https://github.com/eclipse/thingweb.node-wot#to-use-with-nodejs 
- at the end of the list at https://github.com/eclipse/thingweb.node-wot#trouble-shooting
- https://github.com/eclipse/thingweb.node-wot/blob/master/Dockerfile#L1

**Comment by danielpeintner** [comment]
Ahh, I see

> * https://github.com/eclipse/thingweb.node-wot#to-use-with-nodejs
> 
> * at the end of the list at https://github.com/eclipse/thingweb.node-wot#trouble-shooting

I know what to do here 👍 

> * https://github.com/eclipse/thingweb.node-wot/blob/master/Dockerfile#L1

for the record: same for https://github.com/eclipse/thingweb.node-wot/blob/master/Dockerfile#L25

Since I am not using docker. we still need to pick a given image. What should it be and which version? I guess we would need input from docker users..

**Comment by relu91** [comment]
Reopening to keep track of the README problem.
