### ISSUE TITLE
Bug in MQTT topic parsing

### ISSUE THREAD

**Issue by ctron** [eclipse/thingweb.node-wot#874]
Creating an action, and trying to invoke it with MQTT, I can see the following in the logs (device: `wot1`, action: `reset`):

```
  mqttjs:client sendPacket :: packet: {
  mqttjs:client   cmd: 'subscribe',
  mqttjs:client   subscriptions: [
  mqttjs:client     {
  mqttjs:client       topic: 'wot1/actions/reset',
  mqttjs:client       qos: 0,
  mqttjs:client       nl: false,
  mqttjs:client       rap: false,
  mqttjs:client       rh: 0,
  mqttjs:client       properties: undefined
  mqttjs:client     }
  mqttjs:client   ],
  mqttjs:client   qos: 1,
  mqttjs:client   retain: false,
  mqttjs:client   dup: false,
  mqttjs:client   messageId: 21279
  mqttjs:client } +0ms
[…]
node-wot:binding-mqtt:mqtt-broker-server:warn MqttBrokerServer at undefined received message for invalid topic 'wot1/actions/reset' 
```

So the device subscribes to `wot1/actions/reset` and then claims a command to `wot1/actions/reset` is invalid.

Taking a look at the code, the bug is simple to spot:

https://github.com/eclipse/thingweb.node-wot/blob/68084d2afc60e7e162462e061cdcbee2fab64978/packages/binding-mqtt/src/mqtt-broker-server.ts#L195

It checks for 4 segments. However, the topic of an action command will only have 3! The same error is made a few lines below for properties.

I assume the implementation expects a leading slash, in which cases the indices would match. However, during the subscription the a leading slash is not used.

So the implementation must decide, either use a leading slash for BOTH the topic filter during subscription and the topic parsing during processing. Or never use/expect it.

The way it is implemented right now, it seems just broken.

**Comment by egekorkan** [comment]
We had removed the leading slash some time ago so I am pretty sure that is the reason why it is broken

**Comment by danielpeintner** [comment]
@egekorkan can you take a look?

**Comment by egekorkan** [comment]
@hasanheroglu will have a look at this
