### ISSUE TITLE
node-fetch needs Content-Length explicitly for Streams

### ISSUE THREAD

**Issue by msrasheed** [eclipse/thingweb.node-wot#886]
## Scenario
I am trying to submit a POST request with an action with the following code snippet:
```js
dataToSend = {passive: true};
thing.invokeAction("login", dataToSend).catch((err) => console.log(err));
```
but the request generated looks like this
```http
POST /api/login HTTP/1.1
X-Api-Key: <some_api_key>
Content-Type: application/json
Accept: */*
User-Agent: node-fetch/1.0 (+https://github.com/bitinn/node-fetch)
Accept-Encoding: gzip,deflate
Connection: close
Host: 10.0.1.64:5000
Transfer-Encoding: chunked

10
{"passive":true}
0


```
The thing description I'm using is attached (as a txt file cause GitHub).
[octoprint_td.txt](https://github.com/eclipse/thingweb.node-wot/files/10128491/octoprint_td.txt)

## Cause
Did some digging and was able to reproduce the issue using `node-fetch`
```js
const fetch = require('node-fetch');
const stream = require('stream');

content = Buffer.from(JSON.stringify({passive: true}));
console.log(content.length);

const requestInit = {
  method: "POST",
  body: stream.Readable.from(content)
};

request = new fetch.Request('http://10.0.1.64:5000/api/login', requestInit);
request.headers.append('X-Api-Key', "<some_api_key>");
request.headers.append('Content-Type', "application/json");

console.log(request.headers);

fetch(request).then(resp => {
  console.log(resp.status);
  console.log(resp.body.read().toString());
});
```
The issue is related to [this line](https://github.com/node-fetch/node-fetch/blob/55a4870ae5f805d8ff9a890ea2c652c9977e048e/README.md?plain=1#L549) in the `node-fetch` README that if the body type is a Stream, then Content-Type won't be automatically determined (as far as I know, all parameters are converted to streams and then passed to bindings).

Adding the following remedies the issue
```js
request.headers.append('Content-Length', 16);
```

**Comment by danielpeintner** [comment]
Thanks for your finding and your PR https://github.com/eclipse/thingweb.node-wot/pull/887.
I added some comments in the PR.

**Comment by relu91** [comment]
Thank you for using node-wot! About the issue, I don't think it is a bug. When using [`chunked` transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding) and the body must look like what you are showing:
```
chunk size
<content>
0
```

Maybe your problem is that your server does not support chunked transfer. (?)

**Comment by msrasheed** [comment]
Yeah you're right, the server wasn't handling chunked transfers correctly. Thanks, wasn't aware of chunked transfer encoding before this.

Though it would be nice if the http-binding could add the Content-Length header where applicable to avoid future headaches. Maybe not necessary though I guess if it is supported broadly now (I'm not sure about this).

**Comment by msrasheed** [comment]
Yeah, I was thinking about revising my PR to pass the tests and be a bit more flexible, but I don't really have time for that anytime soon so closing is fine.
