### ISSUE TITLE
HTTP server doesn't take content type of `ExposeThingInit`

### ISSUE THREAD

**Issue by ilovemilk** [eclipse/thingweb.node-wot#902]
The 0.8.2 release removed the possibility to specify another content type in the thing model.

In 0.8.1 it was possible to provide a thing mode like this:
```
    "image": {
      "description": "Shows an image",
      "readOnly": true,
      "observable": false,
      "forms": [
        {
          "contentType": "image/png"
        }
      ]
    }
```

The reason for this is that the parameters of `ProtocolHelpers.updatePropertyFormWithTemplate()` changed from
https://github.com/eclipse/thingweb.node-wot/blob/98a271052a2dd84afa71d8e73079d85a2449ac73/packages/binding-http/src/http-server.ts#L324
to
https://github.com/eclipse/thingweb.node-wot/blob/8659709b76c346ce0c2d5ce768f113bb56e4777c/packages/binding-http/src/http-server.ts#L338

Where the call should be `ProtocolHelpers.updatePropertyFormWithTemplate(form, tdTemplate.properties[propertyName])`.

This is also relevant for
https://github.com/eclipse/thingweb.node-wot/blob/8659709b76c346ce0c2d5ce768f113bb56e4777c/packages/binding-http/src/http-server.ts#L387
and
https://github.com/eclipse/thingweb.node-wot/blob/8659709b76c346ce0c2d5ce768f113bb56e4777c/packages/binding-http/src/http-server.ts#L405

**Comment by danielpeintner** [comment]
relates with https://github.com/eclipse/thingweb.node-wot/issues/862
