### ISSUE TITLE
Move client cache to `Servient` level (?)

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#904]
For some serial protocols (like Modbus), having multiple clients connected to the same endpoint (address+port) creates faulty responses. For other protocols, does it make sense to have such a global cache? Does having them cached per Thing makes sense? 

We could keep the current behavior but we definitely need a configuration variable or something else to indicate that sometimes we want clients to be cached globally. Let's discuss it in this issue

**Comment by egekorkan** [comment]
It may make sense for MQTT as well (there it would apply to the Thing too). It might be interesting in some deployments where multiple Consumer scripts run on a single servient. These scripts would actually get a single published message and be distributed via node-wot, reducing the bandwidth requirements and thus costs (a managed cloud case) in general.

Only problem I can see in protocols (Modbus with baud rate in RTU) that allow different kind of connections. Maybe some clients want to connect with different parameters. In mqtt.js there are some options: https://github.com/mqttjs/MQTT.js#client that would show this problem. However, I am not sure if this actually relevant for us. Plus, even if there is, the developer is free to create multiple servients in this case.

**Comment by danielpeintner** [comment]
It seems that at least on binding level we might need such a configuration.

Maybe, it makes even sense that not only the binding makes a decision but also the user can overrule this decision, right?

**Comment by relu91** [comment]
> Maybe, it makes even sense that not only the binding makes a decision but also the user can overrule this decision, right?

Yeah, maybe some custom property on the form level like `node-wot:caching : ["global", "thing"]` .

>Only problem I can see in protocols (Modbus with baud rate in RTU) that allow different kind of connections. Maybe some clients want to connect with different parameters. In mqtt.js there are some options: https://github.com/mqttjs/MQTT.js#client that would show this problem. However, I am not sure if this actually relevant for us. Plus, even if there is, the developer is free to create multiple servients in this case.

I don't think this is going to be problematic. Remember that we are not caching the connection between the two things but rather the client. Connection pooling is still something that the protocol binding is handling (at least in the current architecture), one example is the Modbus client or the HTTP client for SSE.

**Comment by JKRhb** [comment]
> For some serial protocols (like Modbus), having multiple clients connected to the same endpoint (address+port) creates faulty responses. For other protocols, does it make sense to have such a global cache? Does having them cached per Thing makes sense?
> 

For CoAP, it would definitely make sense as well, e.g., to be able to cache DTLS connections.

**Comment by relu91** [comment]
As discussed in the PR linked above, I think that node-wot already has the ability to let protocol bindings implementers choose whether to have a global instance of their clients or create a new one per ConsumedThing. Thanks to the factory pattern they can choose the logic they want. This logic can even be configured using the servient settings. 

Currently, we really can't state if a form wants a global cached client or a new one... but I am not sure that a TD designer is able to choose one of the two options.

**Comment by relu91** [comment]
>As discussed in the PR linked above, I think that node-wot already has the ability to let protocol bindings implementers choose whether to have a global instance of their clients or create a new one per ConsumedThing. Thanks to the factory pattern they can choose the logic they want. This logic can even be configured using the servient settings.

>Currently, we really can't state if a form wants a global cached client or a new one... but I am not sure that a TD designer is able to choose one of the two options.

I consider the core issue resolved. Feel free to re-open it if needed.
