### ISSUE TITLE
CORS with credentials not working in node-wot HTTP client for browser

### ISSUE THREAD

**Issue by justus237** [eclipse/thingweb.node-wot#933]
CORS with credentials is currently not handled correctly by the HTTP server for any interaction affordance. Testing with Chrome 110.0.5481.177, the preflight request (which must not contain credentials, see [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#requests_with_credentials)) is interpreted as a normal request and checked against the credentials, which always fails and returns HTTP 401. This affects the browser-based WoT client from what I can tell.
Fixing this would require reworking https://github.com/eclipse/thingweb.node-wot/blob/master/packages/binding-http/src/http-server.ts#L726

**Comment by danielpeintner** [comment]
Thanks @justus237 for reporting the issue.

Can you provide a test (even a manual one) that fails with the current code and sketch what should be done instead w.r.t. your understanding. A PR is obviously fine as well!

**Comment by justus237** [comment]
> Can you provide a test (even a manual one) that fails with the current code and sketch what should be done instead w.r.t. your understanding.

So I have a manual test at https://github.com/justus237/node-wot-cors that requires two network hosts, one running a node-wot server (server.js) and another serving index.html, which uses node-wot for the browser. Not sure if you can test something like this with the current test infrastructure for this project, are there end-to-end tests with multiple hosts?

As for sketching what to do, I would add a check for OPTIONS requests in case the credentials check fails, that then falls through to the path segment checker, which then calls `respondUnallowedMethod()`, maybe with a new argument that there was a credentialed preflight request (`function respondUnallowedMethod(res: http.ServerResponse, allowed: string, credentialedPreflight: Boolean): void`). The only difference to how CORS is currently handled in that function is that the `Access-Control-Allow-Origin` header has to be `req.headers.origin`(not the wildcard `*`) and we have to add `Access-Control-Allow-Credentials: true`. That's all that needs to be modified from what I can tell.

There is a lazier version, where you just return GET, PUT, POST, OPTIONS as "allowed" for every OPTIONS request, because at least Chrome seems to ignore the actual methods being returned by preflight requests, when using XMLHttpRequest. This would just require adding a check for OPTIONS when credentials fail and returning the same response every time.

I'm open to creating a PR for either of those, the first option is probably better?

**Comment by danielpeintner** [comment]
Hi @justus237.
Thank you for you clear explanation and the manual test 👍.
Note: we should definitely _save_ this and other manual tests somewhere in the node-wot repo.

I did test out your setup and I see the issue you are pointing at. It is possible to retrieve the TD from the remote host but once you try reading the property CORS issues pop up (with a longer delay, maybe due to my setup?).

> As for sketching what to do, I would add a check for OPTIONS requests in case the credentials check fails, that then falls through to the path segment checker, which then calls `respondUnallowedMethod()`, maybe with a new argument that there was a credentialed preflight request (`function respondUnallowedMethod(res: http.ServerResponse, allowed: string, credentialedPreflight: Boolean): void`). The only difference to how CORS is currently handled in that function is that the `Access-Control-Allow-Origin` header has to be `req.headers.origin`(not the wildcard `*`) and we have to add `Access-Control-Allow-Credentials: true`. That's all that needs to be modified from what I can tell.
> 
> There is a lazier version, where you just return GET, PUT, POST, OPTIONS as "allowed" for every OPTIONS request, because at least Chrome seems to ignore the allowed methods being returned by preflight requests, when using XMLHttpRequest. This would just require adding a check for OPTIONS when credentials fail and returning the same response every time.

I would definitely go for the safer solution since other browsers might behave differently or current _assumptions_ for Chrome might no longer apply for future Chrome releases.

If you can provide a PR this would be great and I am happy to take a look at it!
