### ISSUE TITLE
firestore npm version is 0.8.2

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#945]
For some reason, the latest versions of the firestore binding are not pushed to npm and only 0.8.2 is there. Is this normal?
https://www.npmjs.com/package/@node-wot/binding-firestore

I thought maybe it is due to failing tests?

**Comment by relu91** [comment]
Yes, we removed it from the package list (see https://github.com/eclipse/thingweb.node-wot/blob/master/package.json#L41).

**Comment by egekorkan** [comment]
Was it due to failing tests?

**Comment by relu91** [comment]
> Was it due to failing tests?

Yes
