### ISSUE TITLE
Adding CBOR support

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#953]
Currently, it is not possible to use CBOR in the contentType but it would be good to have it for showing multiple content type usage.

**Comment by danielpeintner** [comment]
Is the section in https://github.com/eclipse/thingweb.node-wot#mediatype-support not enough?

There is a sample code how one can integrate its own codec ...

Note: we cannot (and I believe **should** not) add various codecs. People can add codecs themselves...

**Comment by egekorkan** [comment]
I have created this more for a discussion and to see if there is a general interest in it. The issue came from WoT CG discussions where OCF over CBOR and CoAP ie being done via WoT (node-wot to be specific).

**Comment by relu91** [comment]
> I agree with you in general, @danielpeintner, but I would say that CBOR is fundamental enough for IoT use cases to be supported by the core package (also considering that it is a formal Internet Standard, just as JSON). I think I would rather draw a line at vendor-specific media types or media types limited to a specific protocol like NETCONF.

I would agree with Jan here, I think we can manage to handle also CBOR.

**Comment by danielpeintner** [comment]
I am not opposed of adding CBOR. My main concern is that we keep adding packages and codecs (and the associated libraries).

We once had the idea to maintain just the core part in node-wot and bindings should come on top. 
Adding codec goes in the opposite direction...

**Comment by JKRhb** [comment]
Hmm, would that imply that new and maybe also already existing Codecs should be moved to their own binding packages? (In this case, for example, something like `binding-cbor`?)

My point was simply that if there are Codecs in the core package, then CBOR should probably be one of them. Then again, CBOR is mostly used with CoAP so I can understand your concern that this additional dependency is not really necessary for something like HTTP or MQTT.

**Comment by danielpeintner** [comment]
At the moment codecs are in `core` which I think is not the right place.

I envision something like the following for packages
* binding-http
* binding-coap
* ...
 
and in the same spirit for codecs

* codec-json
* codec-plain-text
* ...

For the "bindings" we are there while for "codecs" we are not. 

In the end, an application can pick the necessary binding(s) and codec(s).

What do you think? Does that make sense or is it to much hurdles?
Any thought appreciated...

**Comment by egekorkan** [comment]
> @egekorkan do you mean "what happens now"?

No no, it was just a question for the future direction but I think you have answered it like I was expecting :)

**Comment by JKRhb** [comment]
See #958 for a simple initial CBOR codec implementation :) I think the question with regard to the PR is whether the CBOR codec should already be added to its own(`codec-cbor` package or if this change should only be made for the next/first major release.

**Comment by danielpeintner** [comment]
What do people think about the proposal to split the codecs from the core package? Any thoughts?

**Comment by relu91** [comment]
> What do people think about the proposal to split the codecs from the core package? Any thoughts?

I support the idea, but I'll do the refactoring in one single dedicated PR.

**Comment by egekorkan** [comment]
> What do people think about the proposal to split the codecs from the core package? Any thoughts?

I think that I would support this but this has two implications/questions for me:

1. Moving each codec to their own folder or moving all codecs to a `codecs` folder? Here I use the folder synonymous with package.
2. Removing the default import of the codecs in the core package. Currently, we have lines like https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts#L17 that include all codecs into the core. Will we remove them and let people add them themselves? This means that each script needs to build _its own_ content-serdes. Even though this logically makes sense, it would worsen the developer experience.

**Comment by danielpeintner** [comment]
I created issue https://github.com/eclipse/thingweb.node-wot/issues/959 to discuss this topic.

According to my understanding there should **not** be a "single" `codecs` folder since this doesn't make sense. The whole idea is to be able to specify which codec is needed and hence which associated libraries et cetera are needed. Otherwise we always get a huge list of external dependencies that in most of the cases are not needed.

Moreover, some codecs should remain in the core package... 
Let continue the discussion in https://github.com/eclipse/thingweb.node-wot/issues/959

**Comment by danielpeintner** [comment]
> 2\. Removing the default import of the codecs in the core package. Currently, we have lines like https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/content-serdes.ts#L17 that include all codecs into the core. Will we remove them and let people add them themselves? This means that each script needs to build _its own_ content-serdes. Even though this logically makes sense, it would worsen the developer experience.

This is not true. What you need to do is the following (extending/resetting the codecs from `core`)

`ContentSerdes.get().addCodec(new CodecImplementedInPackageBla("application/bla"));`
