### ISSUE TITLE
counter example: countAsImage property has wrong contentType in TD

### ISSUE THREAD

**Issue by egekorkan** [eclipse/thingweb.node-wot#965]
Counter at http://plugfest.thingweb.io:8083/counter has a property called countAsImage which is there to test SVG properties. The forms however still have json even though that the code for it at https://github.com/eclipse/thingweb.node-wot/blob/fa1cd439e119563ed8ced6aa9672a2419d02a210/packages/examples/src/scripts/counter.ts#L97 says it should generate an SVG. The property still returns a JSON but formatted as SVG at http://plugfest.thingweb.io:8083/counter/properties/countAsImage . There seems to be a bug somewhere.

**Comment by danielpeintner** [comment]
> The property still returns a JSON but formatted as SVG at http://plugfest.thingweb.io:8083/counter/properties/countAsImage . There seems to be a bug somewhere.

I agree but I also think we need to agree on the expected results.
I assume in the case of SVG we should report the SVG code only without being wrapped into a JSON String, correct?
`<svg xmlns='http://www.w3.org/2000/svg' height='30' width='200'><text x='0' y='15' fill='black'>0</text></svg>`

Another question is what should happen with `readallproperties`, see https://github.com/eclipse/thingweb.node-wot/issues/949#issuecomment-1508184167

What should happen to the SVG value in this case?

**Comment by egekorkan** [comment]
> I assume in the case of SVG we should report the SVG code only without being wrapped into a JSON String, correct?

Yes it should be. If we want to return it as a JSON string, then the contentType should be `application/json` and then data schema should say `"contentMediaType":"image/svg+xml",`.

Regarding `readallproperties`, I am open to ideas but it seems that we have a problem with the TD spec since all forms have JSON as the default content type or have a single contentType. Until that is resolved, I see multiple ways forward that probably deserves its own discussion:

1. There are different `readallproperties` forms per content type. All property values are transformed to that content type upon request. If there are 3 JSON, 3 XML and 5 JPEG, they must be all converted to JSON when the `readallproperties`. This requires solid understanding of the paylod binding concepts.
2. There are different `readallproperties` forms per content type. Different from above, only properties of that content type are returned. In a way, this becomes a `readmultipleproperties` but with a preselected set of properties.
3. There cannot be a `readallproperties` if there are different content types (or the same content type does not exist in all properties). This needs to be an assertion in the TD spec.

In my opinion, these meta operations work only in the simplest case and are littered with issues like security, fixed data schema wrapper, and now content type mismatch.

**Comment by relu91** [comment]
> In my opinion, these meta operations work only in the simplest case and are littered with issues like security, fixed data schema wrapper, and now content type mismatch.

I definitely feel the same. About the wrapper, consider that some implementations might like to return all the values in an array instead of having them neatly returned in an object. In theory, they are a nice thing to have because some platforms actually support this kind of operation, but in practice is really hard to make them work. Consider that also for readmutlitple we still don't have a clear way to convey which properties to select in a protocol-independent format.

**Comment by danielpeintner** [comment]
I created https://github.com/eclipse/thingweb.node-wot/pull/981 which reports the SVG value without quotes...
