### ISSUE TITLE
URI variables do not work when base is used

### ISSUE THREAD

**Issue by 6d77** [eclipse/thingweb.node-wot#97]
When using a base URL in a TD, URI parameter substitution does not work any longer.

During TD parsing, the url module is used to perform URL resolution. During this process, the curly braces `{}` are already replaced by their %-escapes. So the URI variable substitution is no longer able to detect the placeholders and to insert the proper value.

Without base URL the curly braces are passed untouched and template variable substitution works as expected.

**Comment by danielpeintner** [comment]
I wonder *what* is better
* revert the `%7B` and `%7D` back to `{` and `}`
* remove uriVariables before passing it to the url module

@6d77 any opinion, proposal? see PR https://github.com/eclipse/thingweb.node-wot/pull/98

**Comment by 6d77** [comment]
Third option: implement own URL resolver or try to find one which does not %-encode the braces.
I would not recommend option 2, as this might also lead to errors. Consider a base URL like

```
http://hostname:port/api/{var}/more/
```

After removing the variable two consecutive `//` will remain which are likely to be replaced by a single slash, so that you can no longer re-insert the template variable. This is just one complication, many others might arise.

Option 1 has the problem, that it then inhibits writing of URLs containing `%7B` or `%7D`.

**Comment by danielpeintner** [comment]
Third option makes sense.

I updated PR https://github.com/eclipse/thingweb.node-wot/pull/98 by using [url-toolkit](https://www.npmjs.com/package/url-toolkit) library.

@6d77 please approve if you think the fix is ok.

**Comment by danielpeintner** [comment]
fixed https://github.com/eclipse/thingweb.node-wot/pull/98
