### ISSUE TITLE
Mqtt handleAction and handleWriteProperty do not work as expected

### ISSUE THREAD

**Issue by hasanheroglu** [eclipse/thingweb.node-wot#979]
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-mqtt/src/mqtt-broker-server.ts#L269

https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-mqtt/src/mqtt-broker-server.ts#L303

The lines above send just a JSON object or string (in case of a parsing error for handleAction) to `handleInvokeAction` and `handleWriteProperty` function, where functions need a `Content` object instead. And with these non-Content values `InteractionOutput`s are created, after we make a call for `InteractionOutput`s value error occurs because `InteractionOutput`s content is not actually a content but JSON object or string.

I have seen that for other protocol bindings using forms' contentType, `Content` object is created: 
https://github.com/eclipse/thingweb.node-wot/blob/09dfd6ab03805b7b39ab39433880496466d25e67/packages/binding-coap/src/coap-server.ts#L456-L460

Should we also apply same kind of logic here or should we follow some other method?

**Comment by egekorkan** [comment]
For clarification: The JSON.parse way is predating all the other packages that use Content. MQTT package should do the same.

**Comment by hasanheroglu** [comment]
Working on it.
